force-app/main/default/objects/WSParamGoogleApi__mdt/WSParamGoogleApi__mdt.object-meta.xml
<CustomObject>
    <label>WS Param Google Api</label>
    <pluralLabel>WS Params Google Api</pluralLabel>
</CustomObject>

force-app/main/default/objects/WSParamGoogleApi__mdt/fields/MethodeAppel__c.field-meta.xml
<CustomField>
    <fullName>MethodeAppel__c</fullName>
    <label>Methode de l&#39;appel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WSParamGoogleApi__mdt/fields/Parametres__c.field-meta.xml
<CustomField>
    <fullName>Parametres__c</fullName>
    <label>Paramètres</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSParamGoogleApi__mdt/fields/StatutCodeSucces__c.field-meta.xml
<CustomField>
    <fullName>StatutCodeSucces__c</fullName>
    <label>Statut code succès</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WS06_GoogleApi.cls
public abstract class WS06_GoogleApi extends WS01_Generic {
    
    public WS06_GoogleApi() {
    	queryAuth = 'SELECT MethodeAppel__c, Parametres__c, WsEndpoint__c, StatutCodeSucces__c FROM WSParamGoogleApi__mdt';
    }
    
    public override void setRequest(SObject authObject) {
    	WSParamGoogleApi__mdt auth = (WSParamGoogleApi__mdt) authObject;
    	this.successCodeStatus = auth.StatutCodeSucces__c.intValue();
	    this.req.setMethod(auth.MethodeAppel__c);
	    this.req.setEndpoint(auth.WsEndpoint__c + auth.Parametres__c);
        this.req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
    }
}