force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/HistoryAccount__c/HistoryAccount__c.object-meta.xml
<CustomObject>
    <label>Historique de compte</label>
    <nameField>
        <label>Nom de Historique de compte</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historique de comptes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HistoryAccount__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Date d&#39;application</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HistoryAccount__c/fields/Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Entreprise__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historique de comptes</relationshipLabel>
    <relationshipName>Historique_de_comptes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/HistoryAccount__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>Nouvelle valeur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP04_Account_Test.cls
@isTest
public class AP04_Account_Test {
  @isTest static void test() {
        Id rtClientId = Utils.getAccountRecordTypeByDeveloperName(Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_CLIENT);
        Account ent = new Account(Name = 'Entreprise 1', RecordTypeId = rtClientId);
        
        Test.startTest();
        insert ent;
        ent.Name = 'Entreprise Prospect V2';
        update ent;
        ent.Name = 'Entreprise Prospect V3';
        update ent;
        Test.stopTest();
    }
    
  @isTest static void test2() {
        Id rtClientId = Utils.getAccountRecordTypeByDeveloperName(Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_CLIENT);
        Account ent = new Account(Name = 'Entreprise 1', RecordTypeId = rtClientId);

        insert ent;
        ent.Name = 'Entreprise Prospect V2';
        update ent;
        ent.Name = 'Entreprise Prospect V3';
        update ent;
        ent.Name = 'Entreprise Prospect V4';
        update ent;
        List<HistoryAccount__c> listHA = [SELECT id, newValue__c, EffectiveDate__c FROM HistoryAccount__c WHERe entreprise__c = :ent.Id];
        Test.startTest();
        listHA[1].newValue__c = 'Entreprise Prospect V25';
        update listHA[1];
        Date today = Date.today();
        listHA[2].EffectiveDate__c = today.addDays(-1);
        update listHA[2];
        listHA[2].EffectiveDate__c = today.addDays(10);
        update listHA[2];
        
        Datetime dt = Datetime.now().addMinutes(1);
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
        String jobId = System.schedule('Sample_Heading', CRON_EXP, new CronMajAccount() );
        Test.stopTest();
    }    
}