force-app/main/default/objects/associate__c/associate__c.object-meta.xml
<CustomObject>
    <description>Associé d&#39;un projet de création de société</description>
    <label>Associé</label>
    <nameField>
        <label>Nom de l&#39;associé ou Dénomination sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/associate__c/fields/ID_Id_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Id_Card__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Carte d&#39;identité&quot;. null si aucune carte d&#39;identité.</description>
    <label>ID de la carte d&#39;identité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Kbis__c.field-meta.xml
<CustomField>
    <fullName>ID_Kbis__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Extrait de Kbis&quot;. null si aucun Kbis.</description>
    <label>ID Kbis</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Status__c.field-meta.xml
<CustomField>
    <fullName>ID_Status__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Statuts à jour&quot;. null si aucun statut.</description>
    <label>ID Statuts</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Vital_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Vital_Card__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Carte vitale&quot;. null si aucune carte vitale.</description>
    <label>ID de la carte vitale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Projet de création</label>
    <referenceTo>Start__c</referenceTo>
    <relationshipLabel>Associés</relationshipLabel>
    <relationshipName>Associate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/ID_Lease__c.field-meta.xml
<CustomField>
    <fullName>ID_Lease__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Bail commercial&quot;. null si aucune carte vitale.</description>
    <label>ID Bail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Hosted__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Hosted__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Hébergé)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Hébergé)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Lessee__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Lessee__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Locataire)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Locataire)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Owner__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Owner__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Propriétaire)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Propriétaire)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AP12_UploadFile.cls
public with sharing class AP12_UploadFile {

	public static void beforeDelete(Map<Id,ContentDocument> oldMap) {
		//Find type of linked entity
		Map<String, Schema.SObjectType> gd =  Schema.getGlobalDescribe();
		List<SObject> updatedObjects = new List<SObject>();

		List<Associate__c> partners = [SELECT ID_Id_Card__c,ID_Vital_Card__c,ID_Kbis__c,ID_Status__c FROM Associate__c WHERE
		                               ID_Id_Card__c IN :oldMap.keySet() OR
		                               ID_Vital_Card__c IN :oldMap.keySet() OR
		                               ID_Kbis__c IN :oldMap.keySet() OR
		                               ID_Status__c IN :oldMap.keySet()];
		for(Associate__c partner : partners) {
			if(oldMap.containsKey(partner.ID_Id_Card__c)) partner.ID_Id_Card__c = null;
			if(oldMap.containsKey(partner.ID_Vital_Card__c)) partner.ID_Vital_Card__c = null;
			if(oldMap.containsKey(partner.ID_Kbis__c)) partner.ID_Kbis__c = null;
			if(oldMap.containsKey(partner.ID_Status__c)) partner.ID_Status__c = null;
			updatedObjects.add(partner);
		}

		List<Start__c> starts = [SELECT ID_Registered_Office_Owner__c,ID_Registered_Office_Lessee__c,ID_Registered_Office_Hosted__c,ID_Lease__c FROM Start__c WHERE
		                         ID_Registered_Office_Owner__c IN :oldMap.keySet() OR
		                         ID_Registered_Office_Lessee__c IN :oldMap.keySet() OR
		                         ID_Registered_Office_Hosted__c IN :oldMap.keySet() OR
		                         ID_Lease__c IN :oldMap.keySet()];
		for(Start__c start : starts) {
			if(oldMap.containsKey(start.ID_Registered_Office_Owner__c)) start.ID_Registered_Office_Owner__c = null;
			if(oldMap.containsKey(start.ID_Registered_Office_Lessee__c)) start.ID_Registered_Office_Lessee__c = null;
			if(oldMap.containsKey(start.ID_Registered_Office_Hosted__c)) start.ID_Registered_Office_Hosted__c = null;
			if(oldMap.containsKey(start.ID_Lease__c)) start.ID_Lease__c = null;
			updatedObjects.add(start);
		}

		update updatedObjects;
	}

}