force-app/main/default/objects/associate__c/associate__c.object-meta.xml
<CustomObject>
    <description>Associé d&#39;un projet de création de société</description>
    <label>Associé</label>
    <nameField>
        <label>Nom de l&#39;associé ou Dénomination sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/associate__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Prénom de l&#39;associé</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Id_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Id_Card__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Carte d&#39;identité&quot;. null si aucune carte d&#39;identité.</description>
    <label>ID de la carte d&#39;identité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Kbis__c.field-meta.xml
<CustomField>
    <fullName>ID_Kbis__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Extrait de Kbis&quot;. null si aucun Kbis.</description>
    <label>ID Kbis</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Status__c.field-meta.xml
<CustomField>
    <fullName>ID_Status__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Statuts à jour&quot;. null si aucun statut.</description>
    <label>ID Statuts</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Vital_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Vital_Card__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Carte vitale&quot;. null si aucune carte vitale.</description>
    <label>ID de la carte vitale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Projet de création</label>
    <referenceTo>Start__c</referenceTo>
    <relationshipLabel>Associés</relationshipLabel>
    <relationshipName>Associate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/ID_Lease__c.field-meta.xml
<CustomField>
    <fullName>ID_Lease__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Bail commercial&quot;. null si aucune carte vitale.</description>
    <label>ID Bail</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Hosted__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Hosted__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Hébergé)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Hébergé)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Lessee__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Lessee__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Locataire)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Locataire)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Owner__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Owner__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Propriétaire)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Propriétaire)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AP13_UploadFileController.cls
public with sharing class AP13_UploadFileController {

	private static final List<String> START_FIELDS = new List<String> {
		'ID_Registered_Office_Owner__c', 'ID_Registered_Office_Lessee__c',
		'ID_Registered_Office_Hosted__c', 'ID_Lease__c'
	};

	private static final List<String> PARTNER_FIELDS = new List<String> {
		'ID_Id_Card__c', 'ID_Vital_Card__c', 'ID_Kbis__c', 'ID_Status__c'
	};

	@AuraEnabled
	public static void updateDocumentId(Id parentId, String field, Id documentId) {
		Start__c start = getStart(parentId);
		Associate__c partner = getPartner(parentId);
		if(start == null && partner == null)  {
			throw Utils.generateAuraHandledException('Invalid Id provided.');
		}
		if(start != null) {
			if(!START_FIELDS.contains(field)) {
				throw Utils.generateAuraHandledException('Invalid field provided.');
			}

			start.put(field, String.valueOf(documentId));
			update start;
		} else if(partner != null) {
			if(!PARTNER_FIELDS.contains(field))
				throw Utils.generateAuraHandledException('Invalid field provided.');
			partner.put(field, String.valueOf(documentId));
			update partner;
		}
	}

	@AuraEnabled
	public static List<ContentDocumentLink> getFiles(Id record) {
		try {
			Start__c start = getStart(record);
			Associate__c partner = getPartner(record);
			if(start == null && partner == null) return null;

			List<ContentDocumentLink> content = null;
			List<Id> docs                     = new List<Id>();

			if(start != null) {

				for(String field : START_FIELDS)
					docs.add(String.valueOf(start.get(field)));

				content = [SELECT ContentDocument.Title,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :record AND ContentDocumentId IN :docs];
				for(ContentDocumentLink cdl : content) {
					for(String field : START_FIELDS) {
						if(cdl.ContentDocumentId == start.get(field)) {
							cdl.ContentDocument.Title = field;
							break;
						}						
					}
				}
			} else if(partner != null) {

				for(String field : PARTNER_FIELDS)
					docs.add(String.valueOf(partner.get(field)));

				content = [SELECT ContentDocument.Title,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :record AND ContentDocumentId IN :docs];
				for(ContentDocumentLink cdl : content) {
					for(String field : PARTNER_FIELDS) {
						if(cdl.ContentDocumentId == partner.get(field)) {
							cdl.ContentDocument.Title = field;
							break;
						}
					}
				}

			}
			return content;
		} catch(DmlException e) {
			System.debug(e.getStackTraceString());
		}
		return null;
	}

	private static Start__c getStart(Id record) {
		List<Start__c> results = [SELECT Name,ID_Registered_Office_Owner__c,ID_Registered_Office_Lessee__c,ID_Registered_Office_Hosted__c,ID_Lease__c FROM Start__c WHERE Id = :record LIMIT 1];
		return results.size() > 0 ? results[0] : null;
	}

	private static Associate__c getPartner(Id record) {
		List<Associate__c> results = [SELECT FirstName__c,Name,ID_Id_Card__c,ID_Vital_Card__c,ID_Kbis__c,ID_Status__c FROM Associate__c WHERE Id = :record LIMIT 1];
		return results.size() > 0 ? results[0] : null;
	}
}