force-app/main/default/objects/associate__c/associate__c.object-meta.xml
<CustomObject>
    <description>Associé d&#39;un projet de création de société</description>
    <label>Associé</label>
    <nameField>
        <label>Nom de l&#39;associé ou Dénomination sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/associate__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Prénom de l&#39;associé</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Id_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Id_Card__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Carte d&#39;identité&quot;. null si aucune carte d&#39;identité.</description>
    <label>ID de la carte d&#39;identité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Projet de création</label>
    <referenceTo>Start__c</referenceTo>
    <relationshipLabel>Associés</relationshipLabel>
    <relationshipName>Associate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <label>Dénomination Sociale</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Lessee__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Lessee__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Locataire)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Locataire)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ID_Registered_Office_Owner__c.field-meta.xml
<CustomField>
    <fullName>ID_Registered_Office_Owner__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Domiciliation (Propriétaire)&quot;. null si aucune carte vitale.</description>
    <label>ID Domiciliation (Propriétaire)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AP13_UploadFileController_TEST.cls
@isTest
private class AP13_UploadFileController_TEST {

	private static final String PARTNER_NAME = 'John';
	private static final String START_NAME   = 'John Inc.';

	@testSetup static void setup() {
		AP04_Factory.createGenericDataSample();
		List<Lead> leads = [SELECT Id FROM Lead];
		System.assert(!leads.isEmpty());
		Start__c start = AP04_Factory.startFactory(START_NAME, leads.get(0).Id);
		insert start;
		insert AP04_Factory.associateFactory(PARTNER_NAME, start.Id);
	}

	@isTest static void testGetFilesStartEmpty() {
		Start__c start = [SELECT Id FROM Start__c WHERE CompanyName__c = :START_NAME LIMIT 1];
		List<ContentDocumentLink> files = AP13_UploadFileController.getFiles(start.Id);
		System.assertEquals(true, files.isEmpty());
	}

	@isTest static void testGetFilesPartnerEmpty() {
		Associate__c partner = [SELECT Id FROM Associate__c WHERE FirstName__c = :PARTNER_NAME LIMIT 1];
		List<ContentDocumentLink> files = AP13_UploadFileController.getFiles(partner.Id);
		System.assertEquals(true, files.isEmpty());
	}

	@isTest static void testGetFilesStart() {
		Start__c start = [SELECT Id FROM Start__c WHERE CompanyName__c = :START_NAME LIMIT 1];
		start.ID_Registered_Office_Owner__c = Utils.generateDocument('Registered_Office_Owner.txt', 'Registered_Office_Owner', start.Id, 'content');

		update start;

		Test.startTest();
		List<ContentDocumentLink> files = AP13_UploadFileController.getFiles(start.Id);
		Test.stopTest();

		System.assertEquals(1, files.size());
		System.assertEquals('ID_Registered_Office_Owner__c', files.get(0).ContentDocument.Title);
	}

	@isTest static void testGetFilesPartner() {
		Associate__c partner  = [SELECT Id FROM Associate__c WHERE FirstName__c = :PARTNER_NAME LIMIT 1];
		partner.ID_Id_Card__c = Utils.generateDocument('ID_CARD.txt', 'ID_CARD', partner.Id, 'ID card content');

		update partner;

		Test.startTest();
		List<ContentDocumentLink> files = AP13_UploadFileController.getFiles(partner.Id);
		Test.stopTest();
		
		System.assertEquals(1, files.size());
		System.assertEquals('ID_Id_Card__c', files.get(0).ContentDocument.Title);
	}

	@isTest static void testUpdateStart() {
		Start__c start = [SELECT Id FROM Start__c WHERE CompanyName__c = :START_NAME LIMIT 1];
		Id docId = Utils.generateDocument('Registered_Office_Lessee.txt', 'Registered_Office_Lessee', start.Id, 'content');

		Test.startTest();
		AP13_UploadFileController.updateDocumentId(start.Id, 'ID_Registered_Office_Lessee__c', docId);
		Test.stopTest();

		start = [SELECT Id,ID_Registered_Office_Lessee__c FROM Start__c WHERE Id = :start.Id];

		System.assertEquals(docId, start.ID_Registered_Office_Lessee__c);
	}

	@isTest static void testUpdateStartInvalid() {
		Start__c start = [SELECT Id FROM Start__c WHERE CompanyName__c = :START_NAME LIMIT 1];
		Id docId = Utils.generateDocument('Registered_Office_Lessee.txt', 'Registered_Office_Lessee', start.Id, 'content');
		boolean hasError = false;

		Test.startTest();
		try {
			AP13_UploadFileController.updateDocumentId(start.Id, 'Invalid field', docId);
		} catch(Exception e) {
			System.assertEquals('System.AuraHandledException', e.getTypeName());
			System.assertEquals('Invalid field provided.', e.getMessage());
			hasError = true;
		}
		Test.stopTest();

		System.assertEquals(true, hasError);
	}

	@isTest static void testUpdatePartner() {
		Associate__c partner = [SELECT Id FROM Associate__c WHERE FirstName__c = :PARTNER_NAME LIMIT 1];
		Id docId = Utils.generateDocument('ID_CARD.txt', 'ID_CARD', partner.Id, 'ID card content');

		Test.startTest();
		AP13_UploadFileController.updateDocumentId(partner.Id, 'ID_Id_Card__c', docId);
		Test.stopTest();

		partner = [SELECT Id,ID_Id_Card__c FROM Associate__c WHERE Id = :partner.Id];

		System.assertEquals(docId, partner.ID_Id_Card__c);
	}

	@isTest static void testUpdatePartnerInvalid() {
		Associate__c partner = [SELECT Id FROM Associate__c WHERE FirstName__c = :PARTNER_NAME LIMIT 1];
		Id docId = Utils.generateDocument('ID_CARD.txt', 'ID_CARD', partner.Id, 'ID card content');
		boolean hasError = false;

		Test.startTest();
		try {
			AP13_UploadFileController.updateDocumentId(partner.Id, 'Invalid field', docId);
		} catch(Exception e) {
			System.assertEquals('System.AuraHandledException', e.getTypeName());
			System.assertEquals('Invalid field provided.', e.getMessage());
			hasError = true;
		}
		Test.stopTest();

		System.assertEquals(true, hasError);
	}


}