force-app/main/default/objects/associate__c/associate__c.object-meta.xml
<CustomObject>
    <description>Associé d&#39;un projet de création de société</description>
    <label>Associé</label>
    <nameField>
        <label>Nom de l&#39;associé ou Dénomination sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/associate__c/fields/AccreConditions__c.field-meta.xml
<CustomField>
    <fullName>AccreConditions__c</fullName>
    <inlineHelpText>Si demande d&#39;ACCRE, précisez le statut du demandeur</inlineHelpText>
    <label>Conditions ACCRE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demandeur d&#39;emploi indemnisé ou indemnisable</fullName>
            </value>
            <value>
                <fullName>Demandeur d&#39;emploi non indemnisé inscrit à Pôle Emploi au cours des 18 derniers mois</fullName>
            </value>
            <value>
                <fullName>Personne de moins de 30 ans non indemnisée ou reconnue handicapée</fullName>
            </value>
            <value>
                <fullName>Jeune de 18 à 25 ans révolus</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du RSA</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du RMI</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du ASS</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du ATT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/associate__c/fields/AccreInformations__c.field-meta.xml
<CustomField>
    <fullName>AccreInformations__c</fullName>
    <inlineHelpText>Niveau de formation, qualification du dernier emploi occupé, motif d&#39;inscription à pôle emploi.</inlineHelpText>
    <label>Informations ACCRE</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/AccreRequest__c.field-meta.xml
<CustomField>
    <fullName>AccreRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Y-a-t-il une demande d&#39;ACCRE à faire ?</inlineHelpText>
    <label>Demande d&#39;ACCRE ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/BirthCity__c.field-meta.xml
<CustomField>
    <fullName>BirthCity__c</fullName>
    <label>Commune de naissance</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>Date de naissance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/CapitalContribution__c.field-meta.xml
<CustomField>
    <fullName>CapitalContribution__c</fullName>
    <formula>KindShareCapital__c  +  CashShareCapital__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Apport en capital</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/CashShareCapital__c.field-meta.xml
<CustomField>
    <fullName>CashShareCapital__c</fullName>
    <label>Apport en numéraire</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ville</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Civility__c.field-meta.xml
<CustomField>
    <fullName>Civility__c</fullName>
    <label>Civilité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Civility</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/associate__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Prénom de l&#39;associé</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Id_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Id_Card__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Carte d&#39;identité&quot;. null si aucune carte d&#39;identité.</description>
    <label>ID de la carte d&#39;identité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/ID_Vital_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Vital_Card__c</fullName>
    <description>Champ système contenant l&#39;ID du ContentDocument chargé en tant que &quot;Carte vitale&quot;. null si aucune carte vitale.</description>
    <label>ID de la carte vitale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/KindShareCapital__c.field-meta.xml
<CustomField>
    <fullName>KindShareCapital__c</fullName>
    <inlineHelpText>Joindre la liste détaillée</inlineHelpText>
    <label>Apport en nature</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Nationnality__c.field-meta.xml
<CustomField>
    <fullName>Nationnality__c</fullName>
    <label>Nationalité</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/SocialMandat__c.field-meta.xml
<CustomField>
    <fullName>SocialMandat__c</fullName>
    <label>Type de mandat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>President</fullName>
                <label>Président</label>
            </value>
            <value>
                <fullName>DirecteurGeneral</fullName>
                <label>Directeur général</label>
            </value>
            <value>
                <fullName>Gerant</fullName>
                <label>Gérant</label>
            </value>
            <value>
                <fullName>Co-gerant</fullName>
                <isActive>false</isActive>
                <label>Co-gerant</label>
            </value>
            <value>
                <fullName>DirecteurGeneralDelegue</fullName>
                <isActive>false</isActive>
                <label>DirecteurGeneralDelegue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/associate__c/fields/SocialSecurityNumber__c.field-meta.xml
<CustomField>
    <fullName>SocialSecurityNumber__c</fullName>
    <label>Numéro de sécurité sociale</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Projet de création</label>
    <referenceTo>Start__c</referenceTo>
    <relationshipLabel>Associés</relationshipLabel>
    <relationshipName>Associate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Numéro et Rue</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/recordTypes/Personne_Morale.recordType-meta.xml
<RecordType>
    <fullName>Personne_Morale</fullName>
    <active>true</active>
    <label>Personne Morale</label>
</RecordType>

force-app/main/default/objects/associate__c/recordTypes/Personne_Physique.recordType-meta.xml
<RecordType>
    <fullName>Personne_Physique</fullName>
    <active>true</active>
    <label>Personne Physique</label>
</RecordType>

force-app/main/default/objects/Contact/fields/associate__c.field-meta.xml
<CustomField>
    <fullName>associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associé (tech)</label>
    <referenceTo>associate__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FromApp__c.field-meta.xml
<CustomField>
    <fullName>FromApp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FromApp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_Id_Card__c.field-meta.xml
<CustomField>
    <fullName>ID_Id_Card__c</fullName>
    <label>ID de la carte d&#39;identité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SocialSecurityNumber__c.field-meta.xml
<CustomField>
    <fullName>SocialSecurityNumber__c</fullName>
    <label>Numéro de sécurité sociale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Nom du Stakeholder</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stakeholder__c/fields/AccreConditions__c.field-meta.xml
<CustomField>
    <fullName>AccreConditions__c</fullName>
    <label>Conditions ACCRE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demandeur d&#39;emploi indemnisé ou indemnisable</fullName>
            </value>
            <value>
                <fullName>Demandeur d&#39;emploi non indemnisé inscrit à Pôle Emploi au cours des 18 derniers mois</fullName>
            </value>
            <value>
                <fullName>Personne de moins de 30 ans non indemnisée ou reconnue handicapée</fullName>
            </value>
            <value>
                <fullName>Jeune de 18 à 25 ans révolus</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du RSA	Bénéficiaire du RSA</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du RMI	Bénéficiaire du RMI</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du ASS	Bénéficiaire du ASS</fullName>
            </value>
            <value>
                <fullName>Bénéficiaire du ATT	Bénéficiaire du ATT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/AccreInformations__c.field-meta.xml
<CustomField>
    <fullName>AccreInformations__c</fullName>
    <label>Informations ACCRE</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/AccreRequest__c.field-meta.xml
<CustomField>
    <fullName>AccreRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Demande d&#39;ACCRE ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/CapitalContribution__c.field-meta.xml
<CustomField>
    <fullName>CapitalContribution__c</fullName>
    <label>Apport en capital</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stakeholders</relationshipLabel>
    <relationshipName>Parties_Prenantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne Physique</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Parties_PrenantesPP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/PoleEmploiInscriptionDate__c.field-meta.xml
<CustomField>
    <fullName>PoleEmploiInscriptionDate__c</fullName>
    <label>Date d&#39;inscription à Pôle Emploi</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/PrincipalContact__c.field-meta.xml
<CustomField>
    <fullName>PrincipalContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact principal de l&#39;entreprise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/recordTypes/Personne_Morale.recordType-meta.xml
<RecordType>
    <fullName>Personne_Morale</fullName>
    <active>true</active>
    <label>Personne Morale</label>
</RecordType>

force-app/main/default/objects/Stakeholder__c/recordTypes/Personne_Physique.recordType-meta.xml
<RecordType>
    <fullName>Personne_Physique</fullName>
    <active>true</active>
    <label>Personne Physique</label>
</RecordType>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Civility.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Madame</fullName>
    </customValue>
    <customValue>
        <fullName>Monsieur</fullName>
    </customValue>
    <masterLabel>Civilité</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP02_ContactStakeholder.cls
public class AP02_ContactStakeholder {
    public class ICXException extends Exception {}    
    //Méthode permettant de créer un StakeHolder à la création d'un contact. Il rattache le compte au contact.
    public static void onInsert(Map<id,Contact> newMap) { 
        RecordType personnePhysiqueRT = [SELECT id, name from RecordType Where developerName = 'Personne_Physique' AND SObjectType = 'Stakeholder__c'];
        RecordType personneMoraleRT = [SELECT id, name from RecordType Where developerName = 'Personne_Morale' AND SObjectType = 'Stakeholder__c'];
        List<Stakeholder__c> shToInsert = new List<Stakeholder__c>();
        
        set<id> AccountIds = new set<id>();
        set<id> ContactIds = new set<id>(); // Added Isochronix
        for( Contact contact : newMap.values()) {
            AccountIds.add(contact.AccountId);
        }
        List<Stakeholder__c> stakeHolders = [SELECT id, PrincipalContact__c, Company__c, Contact__c FROM Stakeholder__c WHERE Company__c in: AccountIds AND PrincipalContact__c = true];
        
        for(id contactId : newMap.keyset()) {
            Contact newContact = newMap.get(contactId);
            //Faire la vérification sur l'origine du contact, s'il provient d'une app externe, il ne faut pas créer de stakeholder
            if(newContact.FromApp__c == false) {
                System.debug('fromapp false');
                boolean mainContact = true;
                for(StakeHolder__c unSH : stakeHolders) {
                    if(unSH.Company__c == newContact.AccountId) {
                        mainContact = false;
                    }
                }
                Stakeholder__c newSH = new StakeHolder__c(RecordTypeId = personnePhysiqueRT.Id, Contact__c = contactId, Company__c = newContact.AccountId, PrincipalContact__c = mainContact, StartDate__c = Date.today());
                // Isochronix
                // Add contact reference to retrieve Associates informations
                ContactIds.add(contactId);
                shToInsert.add(newSH);
            }
        }
        if(shToInsert.size() > 0) {
            // ---------
            // Isochronix: Map Associate informations ton contact (enhance)
            // ---------
            Contact[] contact_list = [Select id, 
                                      associate__c, associate__r.Start__c, associate__r.CapitalContribution__c, associate__r.Civility__c, associate__r.PostalCode__c, 
                                      associate__r.BirthCity__c, associate__r.AccreConditions__c, associate__r.KindShareCapital__c,associate__r.CashShareCapital__c,
                                      associate__r.PoleEmploiInscriptionDate__c, associate__r.BirthDate__c, associate__r.AccreRequest__c, associate__r.ID_Id_Card__c, 
                                      associate__r.ID_Vital_Card__c, associate__r.AccreInformations__c, associate__r.Nationnality__c, associate__r.Name, associate__r.SocialSecurityNumber__c, 
                                      associate__r.FirstName__c, associate__r.Street__c, associate__r.SocialMandat__c, associate__r.City__c 
                                      From Contact where id In :ContactIds and associate__c != null
                                     ];
            Map<Id, Contact> update_contacts = new Map<Id, Contact>( contact_list ); 
            List<Stakeholder__c> final_shtoinsert = new List<Stakeholder__c>();
            
            for(Stakeholder__c sh: shToInsert) {
                if(update_contacts.containsKey(sh.Contact__c) != true) final_shtoinsert.add(sh);
                else {
                    Contact sh_contact = update_contacts.get(sh.Contact__c);
                    // Get related associate informations
                    Associate__c associate = new Associate__c(
                        Start__c = sh_contact.associate__r.Start__c,
                        Civility__c = sh_contact.associate__r.Civility__c,
                        PostalCode__c = sh_contact.associate__r.PostalCode__c,
                        BirthCity__c = sh_contact.associate__r.BirthCity__c,
                        KindShareCapital__c = sh_contact.associate__r.KindShareCapital__c,
                        CashShareCapital__c  = sh_contact.associate__r.CashShareCapital__c,
                        AccreConditions__c = sh_contact.associate__r.AccreConditions__c,
                        PoleEmploiInscriptionDate__c = sh_contact.associate__r.PoleEmploiInscriptionDate__c,
                        BirthDate__c = sh_contact.associate__r.BirthDate__c,
                        AccreRequest__c = sh_contact.associate__r.AccreRequest__c,
                        ID_Id_Card__c = sh_contact.associate__r.ID_Id_Card__c,
                        ID_Vital_Card__c = sh_contact.associate__r.ID_Vital_Card__c,
                        AccreInformations__c = sh_contact.associate__r.AccreInformations__c,
                        Nationnality__c = sh_contact.associate__r.Nationnality__c,
                        Name = sh_contact.associate__r.Name,
                        SocialSecurityNumber__c = sh_contact.associate__r.SocialSecurityNumber__c,
                        FirstName__c = sh_contact.associate__r.FirstName__c,
                        Street__c = sh_contact.associate__r.Street__c,
                        SocialMandat__c = sh_contact.associate__r.SocialMandat__c,
                        City__c = sh_contact.associate__r.City__c
                    );
                    
                    final_shtoinsert.add( IcxConvertProject.enhanceStakeholder( associate, sh) );   
                }
            }
            
            // ---- END EDIT Isochronix --
            Try {
                insert final_shtoinsert;   
                
            } catch(Exception e) {
                String err = ''+e.getMessage();
                System.debug('Entered Error Trigger '+ err);
                throw new ICXException( err );
            }            
        }
    }
    
    //Méthode permettant de créer un StakeHolder à la mise à jour d'un contact. Il rattache le compte au contact.
    public static void onUpdateContact(Map<id,Contact> oldMap, Map<id,Contact> newMap) {
        System.debug('AP02_ContactStakeholder::onUpdateContact::Begin');
        
        Map<Id, Map<Id, StakeHolder__c>> mapSHByContactIds = new Map<Id,Map<Id, StakeHolder__c>>();
        for(StakeHolder__c sh : [SELECT id, Company__c, Contact__c, PrincipalContact__c FROM Stakeholder__c WHERE Contact__c IN: newMap.keySet()]) {
            Map<Id, StakeHolder__c> shById = mapSHByContactIds.get(sh.Contact__c);
            if(shById == null) {
                shById = new Map<id, StakeHolder__c>();
                mapSHByContactIds.put(sh.Contact__c, shById);
            }
            shById.put(sh.Id, sh);
        }
        Set<Id> setCompanyId = new Set<Id>();
        for(Id contactId : newMap.keySet()) {
            Contact unCtc = newMap.get(contactId);
            setCompanyId.add(unCtc.AccountId);
        }
        
        Map<Id, Map<Id, StakeHolder__c>> mapSHByCompanyIds = new Map<Id,Map<Id, StakeHolder__c>>();
        for(StakeHolder__c sh : [SELECT id, Company__c, Contact__c, PrincipalContact__c FROM Stakeholder__c WHERE Company__c IN: setCompanyId]) {
            Map<Id, StakeHolder__c> shById2 = mapSHByCompanyIds.get(sh.Company__c);
            if(shById2 == null) {
                shById2 = new Map<id, StakeHolder__c>();
                mapSHByCompanyIds.put(sh.Company__c, shById2);
            }
            shById2.put(sh.Id, sh);
        }
        List<Stakeholder__c> shToInsert = new List<Stakeholder__c>();
        for(id contactId : newMap.keySet()) {
            Contact newContact = newMap.get(contactId);
            Contact oldContact = oldMap.get(contactId);
            boolean shAlreadyExists = false;
            boolean mainContact = true;
            if(newContact.AccountId != oldContact.AccountId) {
                for(Id unShId : mapSHByContactIds.get(contactId).keyset()) {
                    StakeHolder__c sh = mapSHByContactIds.get(contactId).get(unShId);
                    if(sh.Company__c == newContact.AccountId) {
                        shAlreadyExists = true;
                    }
                }
                if(mapSHByCompanyIds.containsKey(newContact.AccountId)) {
                for(Id unShId : mapSHByCompanyIds.get(newContact.AccountId).keyset()) {
                    StakeHolder__c sh = mapSHByCompanyIds.get(newContact.AccountId).get(unShId);
                    if(sh.PrincipalContact__c == true) {
                        mainContact = false;
                    }
                }
                }
                if(shAlreadyExists == false) {
                    System.debug('AP02_ContactStakeholder::onUpdateContact::CreationSH');
                    Stakeholder__c newSH = new StakeHolder__c(RecordTypeId = Utils.getStakeholderRecordTypeIdByDeveloperName(Constants.STAKEHOLDER_RECORDTYPE_DEVELOPERNAME_PP), Contact__c = contactId, Company__c = newContact.AccountId, PrincipalContact__c = mainContact, StartDate__c = Date.today());
                    shToInsert.add(newSH);
                }
            } 
        }
        if(shToInsert.size() > 0) insert shToInsert;
    }
    
    //Méthode empêchant la suppression des contacts s'ils sont définis comme principal dans un stakeholder
    public static void beforeDeleteContact(Map<Id,Contact> oldMap) {
        Map<Id,Stakeholder__c> MapStakeholderByIdContact = new Map<Id,Stakeholder__c>();
        for(Stakeholder__c stakeholder : [SELECT Id, PrincipalContact__c, Contact__c FROM Stakeholder__c WHERE PrincipalContact__c = true]) {
            if(MapStakeholderByIdContact.containsKey(stakeholder.Contact__c) == false) {
                MapStakeholderByIdContact.put(stakeholder.Contact__c, stakeholder);
            }
        }
        for(Id idContact : oldMap.keySet()) {
            if(MapStakeholderByIdContact.containsKey(idContact)) {
                Contact ctcError = oldMap.get(idContact);
                ctcError.addError(Label.errorDelMainContact);
            }
        }
    }
}