force-app/main/default/objects/Account/fields/Actif__c.field-meta.xml
<CustomField>
    <fullName>Actif__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Actif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdBureauBaseGI__c.field-meta.xml
<CustomField>
    <fullName>IdBureauBaseGI__c</fullName>
    <description>Le numéro du bureau associé à ce cabinet dans la Base GI. Ne doit pas servir pour les comptes de type Client.</description>
    <label>Id Bureau BaseGI</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/MainPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>MainPhoneNumber__c</fullName>
    <label>Téléphone Principal</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/OnlinePartner__c.field-meta.xml
<CustomField>
    <fullName>OnlinePartner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cabinet Online</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <label>Type de partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Groupe</fullName>
            </value>
            <value>
                <fullName>Hors Groupe</fullName>
            </value>
            <value>
                <fullName>Gratuit</fullName>
            </value>
            <value>
                <fullName>Payant</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
                <isActive>false</isActive>
                <label>Association</label>
            </value>
            <value>
                <fullName>Banque</fullName>
                <isActive>false</isActive>
                <label>Banque</label>
            </value>
            <value>
                <fullName>Marketplace</fullName>
                <isActive>false</isActive>
                <label>Marketplace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <description>Signatures des sms et mail</description>
    <inlineHelpText>Signatures des sms et mails</inlineHelpText>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Contact_Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Partenaire</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Il est indispensable de choisir un contact du Cabinet Partenaire</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Partenaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contact Partenaire)</relationshipLabel>
    <relationshipName>LeadsContactPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <label>Corps du mail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Appointment_Set__c.field-meta.xml
<CustomField>
    <fullName>Is_Appointment_Set__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Case système.
Cochée les champs de RDV ont été renseignés via le composant LeadAppointment.</description>
    <label>RDV planifié</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroCompteBaseGI__c.field-meta.xml
<CustomField>
    <fullName>NumeroCompteBaseGI__c</fullName>
    <description>l&#39;identifiant BaseGI du compte créé à partir de la Lead</description>
    <label>Numero Compte BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Le compte partenaire doit être de type &#39;EC Partenaire&#39;. Pour les Partenariat, seuls les cabinets groupes sont valides.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>EC Partenaire</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partenariat</value>
        </filterItems>
        <filterItems>
            <field>$Source.PartnerType__c</field>
            <operation>equals</operation>
            <value>Groupe</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partenaire)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <label>Type de partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hors Groupe</fullName>
                <default>true</default>
                <label>Hors Groupe</label>
            </value>
            <value>
                <fullName>Groupe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Rendez_vous__c.field-meta.xml
<CustomField>
    <fullName>Rendez_vous__c</fullName>
    <label>Date du rendez-vous</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transfert__c/Transfert__c.object-meta.xml
<CustomObject>
    <label>Transfert</label>
    <nameField>
        <label>Nom de Transfert Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transferts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfert__c/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/ContactPartenaire__c.field-meta.xml
<CustomField>
    <fullName>ContactPartenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Partenaire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WSParamBaseGI__mdt/WSParamBaseGI__mdt.object-meta.xml
<CustomObject>
    <description>Décrit les différents web service à utiliser avec la Base GI et les outils liés</description>
    <label>WS Param BaseGI</label>
    <pluralLabel>WS Params BaseGI</pluralLabel>
</CustomObject>

force-app/main/default/objects/WSParamBaseGI__mdt/fields/StatutCodeSucces__c.field-meta.xml
<CustomField>
    <fullName>StatutCodeSucces__c</fullName>
    <label>Statut code succès</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L-Expert-Comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Tiime</fullName>
    </customValue>
    <customValue>
        <fullName>Trouver-mon-comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Novaa</fullName>
    </customValue>
    <customValue>
        <fullName>Incityz</fullName>
    </customValue>
    <customValue>
        <fullName>Condillac</fullName>
    </customValue>
    <customValue>
        <fullName>Goneo</fullName>
    </customValue>
    <customValue>
        <fullName>Ola Compta</fullName>
    </customValue>
    <customValue>
        <fullName>Le Net Expert Comptable</fullName>
    </customValue>
    <customValue>
        <fullName>Onlicorn</fullName>
    </customValue>
    <customValue>
        <fullName>Pepit</fullName>
    </customValue>
    <customValue>
        <fullName>L-Expert-Comptable Lille</fullName>
    </customValue>
    <customValue>
        <fullName>Evocompta</fullName>
    </customValue>
    <customValue>
        <fullName>Auficom</fullName>
    </customValue>
    <customValue>
        <fullName>Proxi Compta</fullName>
    </customValue>
    <description>liste des marques</description>
    <masterLabel>Marques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP05_AppointmentController_TEST.cls
@isTest
public with sharing class AP05_AppointmentController_TEST {
	
	private static final Integer RECORD_COUNT = 8;

	private static User generateUser() {
		Profile profile = [Select id from Profile where Name = 'TMC' limit 1];
		System.debug('### Profile = ' + profile.id);
		User user = new User(
			FirstName = 'John', LastName = 'Doe',
			Username = 'JohnDoe@example.org', Alias = 'JohnDoe',
			Email = 'JohnDoe@example.org',
			ProfileId = profile.Id,
			TimeZoneSidKey = 'Europe/Paris',
			LanguageLocaleKey = 'fr',
			EmailEncodingKey = 'UTF-8',
			LocaleSidKey = 'fr');
		insert user;
		return user;
	}

	private static Lead generateLead() {
		Lead lead = new Lead(FirstName = 'LeadTestFirst', LastName = 'LeadTestLast', 
							Email = 'lead@example.org', Company = 'CompanyName', MobilePhone = '0601010101');
		insert lead;
		return lead;
	}

	private static List<Account> generateFirms() {
		List<Account> firms = new List<Account>();
		Id recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = :Constants.LEAD_ACCOUNT_RECORDTYPES_FOR_APPOINTMENT[0] AND SObjectType = 'Account'].Id;

		System.debug('### Account RecordType Id = ' + recordTypeId);

		for(Integer i= 0 ; i < RECORD_COUNT ; i++) {
			Account firm = new Account(
				Name = 'TestAccount' + i,
				Actif__c = math.mod(i,2) == 0,
				OnlinePartner__c = math.mod(i,3) == 0,
				RecordTypeId = recordTypeId,
				PartnerType__c = 'Groupe',
				MainPhoneNumber__c = '06000000' + (i < 10 ? '0' + i : String.valueOf(i)));
			firms.add(firm);
		}
		insert firms;

		return firms;
	}

	private static List<Contact> generateContacts(List<Account> firms) {
		List<Contact> contacts = new List<Contact>();
		Id recordTypeId = Utils.getContactRecordTypeIdByDeveloperName(Constants.CONTACT_RECORDTYPE_DEVELOPERNAME_PARTNER);

		System.debug('### Contact RecordType Id = ' + recordTypeId);

		for(Integer i= 0 ; i < RECORD_COUNT ; i++) {
			Contact contact = new Contact(FirstName = 'TestContactFirst' + i, LastName = 'TestContactLast' + i,
				MobilePhone = '06000000' + (i < 10 ? '0' + i : String.valueOf(i)),
				AccountId = firms.get(i).Id);
			if(math.mod(i,2) == 0)
				contact.RecordTypeId = recordTypeId;
			contacts.add(contact);
		}
		insert contacts;

		return contacts;
	}

	@isTest static void testContacts() {
		List<Account> firms    = generateFirms();
		List<Contact> contacts = generateContacts(firms);
		List<Contact> result;
		Account firm;
		
		Test.startTest();

		for(Integer i = 0 ; i < RECORD_COUNT ; i++) {
			firm = firms.get(i);
			result = AP05_AppointmentController.getContacts(firm.Id);
			System.assertEquals(math.mod(i,2) != 0 || !firm.Actif__c, result.size() == 0);
		}
		Test.stopTest();
	}

	@isTest static void testFirms() {
		Lead lead = generateLead();

		Test.startTest();
		List<Account> firms  = generateFirms();
		List<AP11_AccountWrapper> result = AP05_AppointmentController.getFirms(lead.Id);
		Test.stopTest();

		System.assertEquals(RECORD_COUNT / 2, result.size());
	}

	@isTest static void testGetFirm() {
		Test.startTest();
		Account firm = generateFirms()[0];

		Account acc = AP05_AppointmentController.getFirm(firm.id);
		System.assertEquals(true, acc.PartnerType__c != null && acc.PartnerType__c != '');
		System.assertEquals(true, acc.MainPhoneNumber__c != null && acc.MainPhoneNumber__c != '');

		Test.stopTest();
	}

	@isTest static void testUpdateFirm() {
		boolean hasError = false;

		Test.startTest();
		Account firm = generateFirms()[0];
		firm.PartnerType__c = 'Groupe';
		firm.MainPhoneNumber__c= '0102030405';
		update firm;
		Lead lead = generateLead();
		
		AP05_AppointmentController.updateFirm(lead.Id, firm.Id);
		lead = [SELECT id,Partenaire__c,Contact_Partenaire__c FROM Lead WHERE Id = :lead.id];

		System.assertEquals(null, lead.Contact_Partenaire__c, 'Partner contact is not null');
		System.assertEquals(firm.id, lead.Partenaire__c);

		//Test wrong ID
		try {
			AP05_AppointmentController.updateFirm(lead.Id, 'wrongId');
		} catch(Exception e) {
			System.assertEquals('System.StringException', e.getTypeName());
			hasError = true;
		}

		System.assertEquals(true, hasError, 'No exception thrown when wrong id is given');
		hasError = false;

		try {
			AP05_AppointmentController.updateFirm(lead.Id, '0120N000000AOUsAAA');
		} catch(Exception e) {
			System.assertEquals('System.DmlException', e.getTypeName());
			hasError = true;
		}

		System.assertEquals(true, hasError, 'No exception thrown when wrong id is given');
		
		Test.stopTest();

	}
	
	@isTest
	static void testCallBaseGI() {
		AP04_Factory.createGenericDataSample();
		List<Account> accounts = [SELECT Id, Name, IdBureauBaseGI__c FROM Account];
		List<Lead> leads = [SELECT Id, name, Partenaire__c, Contact_Partenaire__c FROM Lead];
		List<Contact> contacts = [SELECT Id, Name, AccountId FROM Contact];
		
		accounts.get(0).IdBureauBaseGI__c = 75;
		update accounts;
		
		leads.get(0).Partenaire__c = accounts.get(0).Id;
		leads.get(0).Contact_Partenaire__c = contacts.get(0).Id;
		update leads;
		
		WSParamBaseGI__mdt auth = new WSParamBaseGI__mdt(MasterLabel = 'AccountCreationFromLead', MethodeAppel__c = 'POST', StatutCodeSucces__c = 200);
		
		Test.startTest();
		AP05_AppointmentController.sendLeadToBaseGI(leads.get(0).Id);
		Test.stopTest();
		
		leads = [SELECT ID, NumeroCompteBaseGI__c FROM Lead WHERE Id = :leads.get(0).Id];
		System.assertEquals(1, leads.get(0).NumeroCompteBaseGI__c);
	}
	
	@isTest
	static void testChangeStatusToECaTrouver() {
		User user = AP04_Factory.UserStandardFactory(1, 'nomPourTes', 'PrenomDeTest' , 'userTest@test.fr')[0];
		insert user;

		System.runAs(user){
			Lead c = AP04_Factory.newWebLeadsFactory(1)[0];
			c.City = 'Paris';
			insert c;
		}
		Lead oldLead = [SELECT Id,Status FROM Lead WHERE OwnerId=:user.Id][0];
		System.debug(oldLead.Status);

		Test.startTest();
		AP05_AppointmentController.changeStatusToECaTrouver(oldLead.Id);
		Test.stopTest();
		
		Lead newLead = [SELECT Id,Status FROM Lead WHERE Id=:oldlead.Id][0];
		System.debug(newLead.Status);

		System.assertNotEquals(oldLead.Status, newLead.Status);
		System.assertEquals(Constants.LEAD_STATUS_EC_A_TROUVER, newLead.Status);
	}
	
	@isTest
	static void testNewTransfert() {
		AP04_Factory.createGenericDataSample();
		List<Lead> leads = [SELECT Id, name, Is_Appointment_Set__c FROM Lead];
		leads.get(0).Is_Appointment_Set__c = true;
		update leads.get(0);
		
		Test.startTest();
		AP05_AppointmentController.changeAptPlannedForNewTransfert(leads.get(0).Id, false);
		Test.stopTest();
		
		leads = [SELECT ID, Is_Appointment_Set__c FROM Lead WHERE Id = :leads.get(0).Id];
		System.assertEquals(false, leads.get(0).Is_Appointment_Set__c);
	}
    
    @isTest
    static void testsendEmailForRdv(){
        AP04_Factory.createGenericDataSample();
        Lead l = [SELECT Id, Branding__c,Email, Email_Body__c, Rendez_vous__c, OwnerId FROM Lead][0];
        Contact c = [SELECT Id FROM Contact][0];
        Transfert__c t = new Transfert__c(Name='testTransfert', Lead__c=l.Id, ContactPartenaire__c=c.Id, OwnerId=l.OwnerId);
        insert t;
        
        List<Event> events = [SELECT Id FROM Event];
        System.assert(events.isEmpty());
        
        Test.startTest();
      	AP05_AppointmentController.sendEmailForRdv(t.Id, l.ID, c.Id, l.Branding__c, l.Email, 'corp du mail !', DateTime.now(), 'Au bureau');
        Test.stopTest();
        
        events = [SELECT Id FROM Event];
        System.assert(events.size() == 1);
    }
}