force-app/main/default/objects/Account/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prestataire B2B</fullName>
            </value>
            <value>
                <fullName>Prestataire B2C</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>HCR</fullName>
            </value>
            <value>
                <fullName>BTP</fullName>
            </value>
            <value>
                <fullName>Immobilier</fullName>
            </value>
            <value>
                <fullName>LMNP</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Agricole</fullName>
            </value>
            <value>
                <fullName>Industrie</fullName>
            </value>
            <value>
                <fullName>Production/Artiste</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <description>Signatures des sms et mail</description>
    <inlineHelpText>Signatures des sms et mails</inlineHelpText>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Evaluation_a_priori__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_a_priori__c</fullName>
    <label>Qualité de la lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Star</fullName>
                <label>⭐</label>
            </value>
            <value>
                <fullName>2Stars</fullName>
                <label>⭐⭐</label>
            </value>
            <value>
                <fullName>3Stars</fullName>
                <label>⭐⭐⭐</label>
            </value>
            <value>
                <fullName>4Stars</fullName>
                <label>⭐⭐⭐⭐</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L-Expert-Comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Tiime</fullName>
    </customValue>
    <customValue>
        <fullName>Trouver-mon-comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Novaa</fullName>
    </customValue>
    <customValue>
        <fullName>Incityz</fullName>
    </customValue>
    <customValue>
        <fullName>Condillac</fullName>
    </customValue>
    <customValue>
        <fullName>Goneo</fullName>
    </customValue>
    <customValue>
        <fullName>Ola Compta</fullName>
    </customValue>
    <customValue>
        <fullName>Le Net Expert Comptable</fullName>
    </customValue>
    <customValue>
        <fullName>Onlicorn</fullName>
    </customValue>
    <customValue>
        <fullName>Pepit</fullName>
    </customValue>
    <customValue>
        <fullName>L-Expert-Comptable Lille</fullName>
    </customValue>
    <customValue>
        <fullName>Evocompta</fullName>
    </customValue>
    <customValue>
        <fullName>Auficom</fullName>
    </customValue>
    <customValue>
        <fullName>Proxi Compta</fullName>
    </customValue>
    <description>liste des marques</description>
    <masterLabel>Marques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP15_ControllerLeadResume_TEST.cls
@isTest
public with sharing class AP15_ControllerLeadResume_TEST {

	@isTest 
	static void testLabels() {
		Map<String, String> labels = AP15_ControllerLeadResume.getLabels();
		System.assertEquals(9, labels.size());
	}
	
	@isTest 
	static void testPickListOptions() {
		List<String> fieldNames = new List<String>();
		fieldNames.add('Evaluation_a_priori__c');
		fieldNames.add('Activity__c');
		fieldNames.add('Branding__c');
		List<Map<String, String>> res = AP15_ControllerLeadResume.getPicklistOptions(fieldNames);
		System.assertEquals(3, res.size());
		for(Map<String, String> field : res){
			System.assertEquals(false, field.isEmpty());
		}
	}
	
	@isTest
	static void testNextCallWithBranding(){
		User user = AP04_Factory.UserStandardFactory(1, 'nomPourTes', 'PrenomDeTest' , 'userTest@test.fr')[0];
        insert user;

        System.runAs(user){
            Lead c = AP04_Factory.newWebLeadsFactory(1)[0];
            insert c;
        }
        
		Lead oldLead = [SELECT Id,Status FROM Lead WHERE OwnerId=:user.Id][0];
        String newStatus='';
		Test.startTest();
		newStatus = AP15_ControllerLeadResume.nextCall(oldLead.Id, 'Call 1','Tiime');

		        
        System.debug('Avant : '+oldLead.Status+' , Après : '+newStatus);

        System.assertNotEquals(oldLead.Status, newStatus);
	}
	
	@isTest
	static void testNextCallWithoutBranding(){
		User user = AP04_Factory.UserStandardFactory(1, 'nomPourTes', 'PrenomDeTest' , 'userTest@test.fr')[0];
        insert user;

        System.runAs(user){
            Lead c = AP04_Factory.newWebLeadsFactory(1)[0];
            insert c;
        }
        
		Lead lead = [SELECT Id,Status FROM Lead WHERE OwnerId=:user.Id][0];
        String newStatus='';
        Boolean flag=false;
        try{
			Test.startTest();
			newStatus = AP15_ControllerLeadResume.nextCall(lead.Id, 'Call 1',null);
			Test.stopTest();
        }catch(Exception e){
        	flag=true;
        }
        finally{
        	System.AssertEquals(true,flag);
        }
		
	}
	
	@isTest
	static void testGetStatus(){
		User user = AP04_Factory.UserStandardFactory(1, 'nomPourTes', 'PrenomDeTest' , 'userTest@test.fr')[0];
        insert user;

        System.runAs(user){
            Lead c = AP04_Factory.newWebLeadsFactory(1)[0];
            insert c;
        }
        
		Lead laLead = [SELECT Id,Status FROM Lead WHERE OwnerId=:user.Id][0];
        System.debug(laLead.Status);
        
		Test.startTest();
		String status = AP15_ControllerLeadResume.getStatus(laLead.Id);
		Test.stopTest();
		
		System.assertNotEquals(status, null);
        System.assertEquals(laLead.Status, status);
	}
	
	@isTest
    static void testGetContactPartenariat(){
        Account acc = AP04_factory.partnerAccountsFactory(1)[0];
        insert acc;
        List<Contact> contacts = AP04_factory.partnerContactsFactory(3,acc.Id);
        insert contacts;
        
        contacts = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];
        
        Test.startTest();
        List<Contact> contactsReturned = AP15_ControllerLeadResume.getContactPartenariat(acc.Id);
        Test.stopTest();
        
        System.assertEquals(contacts.size(), contactsReturned.size());
  }
    
    @isTest
    static void testGetLeadEnAttenteId (){
        System.assert(AP15_ControllerLeadResume.getLeadEnAttenteId() != null);
    }
}