force-app/main/default/objects/Account/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>seo</fullName>
                <label>SEO</label>
            </value>
            <value>
                <fullName>paid-search</fullName>
                <label>Paid Search</label>
            </value>
            <value>
                <fullName>native</fullName>
                <label>Native</label>
            </value>
            <value>
                <fullName>paid-social-media</fullName>
                <label>Paid Social Media</label>
            </value>
            <value>
                <fullName>affiliation</fullName>
                <label>Affiliation</label>
            </value>
            <value>
                <fullName>partenariats</fullName>
                <label>Partenariats</label>
            </value>
            <value>
                <fullName>events</fullName>
                <label>Events</label>
            </value>
            <value>
                <fullName>reco-client</fullName>
                <label>Reco client</label>
            </value>
            <value>
                <fullName>presse</fullName>
                <label>Presse</label>
            </value>
            <value>
                <fullName>webinar</fullName>
                <label>Webinar</label>
            </value>
            <value>
                <fullName>inconnu</fullName>
                <label>Inconnu</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdBureauBaseGI__c.field-meta.xml
<CustomField>
    <fullName>IdBureauBaseGI__c</fullName>
    <description>Le numéro du bureau associé à ce cabinet dans la Base GI. Ne doit pas servir pour les comptes de type Client.</description>
    <label>Id Bureau BaseGI</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>Forme juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NumberBGI__c.field-meta.xml
<CustomField>
    <fullName>NumberBGI__c</fullName>
    <description>Le numéro de dossier enregistré dans la BaseGI. Ce numéro doit être unique.</description>
    <externalId>true</externalId>
    <label>Numéro Dossier BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prestataire B2B</fullName>
            </value>
            <value>
                <fullName>Prestataire B2C</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>HCR</fullName>
            </value>
            <value>
                <fullName>BTP</fullName>
            </value>
            <value>
                <fullName>Immobilier</fullName>
            </value>
            <value>
                <fullName>LMNP</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Agricole</fullName>
            </value>
            <value>
                <fullName>Industrie</fullName>
            </value>
            <value>
                <fullName>Production/Artiste</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ActivityDetails__c.field-meta.xml
<CustomField>
    <fullName>ActivityDetails__c</fullName>
    <label>Détails activité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>seo</fullName>
                <label>SEO</label>
            </value>
            <value>
                <fullName>paid-search</fullName>
                <label>Paid Search</label>
            </value>
            <value>
                <fullName>native</fullName>
                <label>Native</label>
            </value>
            <value>
                <fullName>paid-social-media</fullName>
                <label>Paid Social Media</label>
            </value>
            <value>
                <fullName>affiliation</fullName>
                <label>Affiliation</label>
            </value>
            <value>
                <fullName>partenariats</fullName>
                <label>Partenariats</label>
            </value>
            <value>
                <fullName>events</fullName>
                <label>Events</label>
            </value>
            <value>
                <fullName>reco-client</fullName>
                <label>Reco client</label>
            </value>
            <value>
                <fullName>presse</fullName>
                <label>Presse</label>
            </value>
            <value>
                <fullName>webinar</fullName>
            </value>
            <value>
                <fullName>inconnu</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>inbound</fullName>
                <isActive>false</isActive>
                <label>Inbound</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Echeance_de_besoin_de_creation__c.field-meta.xml
<CustomField>
    <fullName>Echeance_de_besoin_de_creation__c</fullName>
    <label>Echéance de besoin de création</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immédiat</fullName>
            </value>
            <value>
                <fullName>1 mois</fullName>
            </value>
            <value>
                <fullName>3 mois</fullName>
            </value>
            <value>
                <fullName>6 mois et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>Forme Juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SASUSAS</fullName>
                <label>SASU / SAS</label>
            </value>
            <value>
                <fullName>EURLSARL</fullName>
                <label>EURL / SARL</label>
            </value>
            <value>
                <fullName>EntrepriseIndividuelle</fullName>
                <label>Entreprise Individuelle</label>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>SCI</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>NeSaitPas</fullName>
                <label>Ne sait pas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TypeOfNeed__c.field-meta.xml
<CustomField>
    <fullName>TypeOfNeed__c</fullName>
    <label>Type de besoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Création</fullName>
            </value>
            <value>
                <fullName>Comptabilité</fullName>
            </value>
            <value>
                <fullName>Création et Comptabilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UtmMedium__c.field-meta.xml
<CustomField>
    <fullName>UtmMedium__c</fullName>
    <label>Utm Medium</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cpc</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>social</fullName>
            </value>
            <value>
                <fullName>chat</fullName>
            </value>
            <value>
                <fullName>banner</fullName>
            </value>
            <value>
                <fullName>print</fullName>
            </value>
            <value>
                <fullName>offline</fullName>
            </value>
            <value>
                <fullName>gmail</fullName>
            </value>
            <value>
                <fullName>youtube</fullName>
            </value>
            <value>
                <fullName>outbrain</fullName>
            </value>
            <value>
                <fullName>nom-de-la-regie</fullName>
            </value>
            <value>
                <fullName>webself</fullName>
            </value>
            <value>
                <fullName>ligatus</fullName>
            </value>
            <value>
                <fullName>sesame</fullName>
            </value>
            <value>
                <fullName>salon-entrepreneur-19</fullName>
            </value>
            <value>
                <fullName>qonto</fullName>
            </value>
            <value>
                <fullName>LiveMentor</fullName>
            </value>
            <value>
                <fullName>Normandie Incubation</fullName>
            </value>
            <value>
                <fullName>taboola</fullName>
            </value>
            <value>
                <fullName>twitter</fullName>
            </value>
            <value>
                <fullName>form-sidebar-crea</fullName>
            </value>
            <value>
                <fullName>LP-Bilan-Rattrapage</fullName>
            </value>
            <value>
                <fullName>Adwords</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UtmSource__c.field-meta.xml
<CustomField>
    <fullName>UtmSource__c</fullName>
    <label>Utm_source</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSParamBaseGI__mdt/WSParamBaseGI__mdt.object-meta.xml
<CustomObject>
    <description>Décrit les différents web service à utiliser avec la Base GI et les outils liés</description>
    <label>WS Param BaseGI</label>
    <pluralLabel>WS Params BaseGI</pluralLabel>
</CustomObject>

force-app/main/default/objects/WSParamBaseGI__mdt/fields/AttributsGet__c.field-meta.xml
<CustomField>
    <fullName>AttributsGet__c</fullName>
    <description>Une liste des arguments à renseigner pour le web service. Fonctionne pour les Web Service utilisant la méthode GET. Les attributs, s&#39;ils sont plusieurs, sont séparés par un &#39;;&#39;</description>
    <label>AttributsGet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSParamBaseGI__mdt/fields/CleAuth__c.field-meta.xml
<CustomField>
    <fullName>CleAuth__c</fullName>
    <label>Clé Auth</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSParamBaseGI__mdt/fields/Domaine__c.field-meta.xml
<CustomField>
    <fullName>Domaine__c</fullName>
    <description>Le domaine du web service à appeler</description>
    <label>Domaine</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSParamBaseGI__mdt/fields/StatutCodeSucces__c.field-meta.xml
<CustomField>
    <fullName>StatutCodeSucces__c</fullName>
    <label>Statut code succès</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WSParamBaseGI__mdt/fields/TypeAuth__c.field-meta.xml
<CustomField>
    <fullName>TypeAuth__c</fullName>
    <description>Le type d&#39;authentification</description>
    <label>Type Auth</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bearer</fullName>
                <default>true</default>
                <label>Bearer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WSParamBaseGI__mdt/fields/WsEndpoint__c.field-meta.xml
<CustomField>
    <fullName>WsEndpoint__c</fullName>
    <description>Le endpoint du web service sans le nom de domaine.</description>
    <label>WS Endpoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LegalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASS</fullName>
    </customValue>
    <customValue>
        <fullName>EARL</fullName>
    </customValue>
    <customValue>
        <fullName>EIRL</fullName>
    </customValue>
    <customValue>
        <fullName>EURL</fullName>
    </customValue>
    <customValue>
        <fullName>GAEC</fullName>
    </customValue>
    <customValue>
        <fullName>GFA</fullName>
    </customValue>
    <customValue>
        <fullName>GIE</fullName>
    </customValue>
    <customValue>
        <fullName>GPT</fullName>
    </customValue>
    <customValue>
        <fullName>IND</fullName>
    </customValue>
    <customValue>
        <fullName>SA</fullName>
    </customValue>
    <customValue>
        <fullName>SARL</fullName>
    </customValue>
    <customValue>
        <fullName>SAS</fullName>
    </customValue>
    <customValue>
        <fullName>SASU</fullName>
    </customValue>
    <customValue>
        <fullName>SC</fullName>
    </customValue>
    <customValue>
        <fullName>SCCV</fullName>
    </customValue>
    <customValue>
        <fullName>SCEA</fullName>
    </customValue>
    <customValue>
        <fullName>SCI</fullName>
    </customValue>
    <customValue>
        <fullName>SCIC</fullName>
    </customValue>
    <customValue>
        <fullName>SCM</fullName>
    </customValue>
    <customValue>
        <fullName>SCOP</fullName>
    </customValue>
    <customValue>
        <fullName>SCP</fullName>
    </customValue>
    <customValue>
        <fullName>SCS</fullName>
    </customValue>
    <customValue>
        <fullName>SDF</fullName>
    </customValue>
    <customValue>
        <fullName>SELARL</fullName>
    </customValue>
    <customValue>
        <fullName>SELARLU</fullName>
    </customValue>
    <customValue>
        <fullName>SELAS</fullName>
    </customValue>
    <customValue>
        <fullName>SELASU</fullName>
    </customValue>
    <customValue>
        <fullName>SEP</fullName>
    </customValue>
    <customValue>
        <fullName>SISA</fullName>
    </customValue>
    <customValue>
        <fullName>SNC</fullName>
    </customValue>
    <masterLabel>Formes juridiques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WS03_BaseGI.cls
public abstract without sharing class WS03_BaseGI extends WS01_Generic {
    
    // Generic attributes and methods begin
    
    public WS03_BaseGI() {
    	queryAuth = 'SELECT CleAuth__c, Domaine__c, MethodeAppel__c, TypeAuth__c, WsEndpoint__c, StatutCodeSucces__c, AttributsGet__c FROM WSParamBaseGI__mdt';
    }
    
    public override void setRequest(Sobject authObject) {
    	WSParamBaseGI__mdt auth = (WSParamBaseGI__mdt) authObject;
	    
    	this.successCodeStatus = auth.StatutCodeSucces__c.intValue();
	    this.req.setHeader(Constants.WS_BAGI_HEADER_AUTH, auth.TypeAuth__c + ' ' + auth.CleAuth__c);
	    this.req.setEndpoint(auth.Domaine__c + auth.WsEndpoint__c + (auth.AttributsGet__c != null ? buildUrlParams(auth.AttributsGet__c) : ''));
	    this.req.setMethod(auth.MethodeAppel__c);
    
    }
    
    // La méthode va analyser les différents attributs énoncés. S'ils sont plusieurs, ils sont séparés par des ';'
    private String buildUrlParams(String attributsGet) {
    	String resultUrl = '';
    	for(String attribut : attributsGet.split(Constants.TECH_FIELD_MULTI_PICKLIST_SEPARATOR)) {
    		resultUrl += '?' + attribut + '=';
    	}
    	return resultUrl;
    }
    
    //private class WS03_Exception extends Exception {}
    
    // Generic attributes and methods end
    
    
    
    
    
    public class WsAccountFromLeadResponse {
    	public Integer code;
    	public String erreur;
    	public Integer numeroDossier;
    	public Integer idIndividu;
    	
    	public WsAccountFromLeadResponse(Integer code, String erreur, Integer numeroDossier, Integer idIndividu) {
    		this.code = code;
    		this.erreur = erreur;
    		this.numeroDossier = numeroDossier;
    		this.idIndividu = idIndividu;
    	}
    }
    
    public class WsAccountFromLeadWrapper {
    	private String leadId;
    	private String nomEntreprise;
    	private String nomLead;
    	private String emailLead;
    	private String telephoneLead;
    	private Integer idBureau;
    	private String prenomReferent;
    	private String nomReferent;
    	private String prenomContact;
    	private String nomContact;
    	private String codePostal;
    	private String ville;
    	private String adresse;
		private String typeBesoin;
		private String echeanceBesoin;
		private String statutLegal;
		private String activite;
		private String detailsActivite;
		private String utmSource;
		private String utmMedium;
		private boolean isExternalPartner;
    	
    	public WsAccountFromLeadWrapper(Lead lead, Account partenaire, Contact contactPartenaire, User referent) {
    		if(lead != null) {
    			this.leadId = lead.Id;
	    		this.nomEntreprise = checkCompanyName(lead.Company);
	    		this.nomLead = lead.Name;
	    		this.emailLead = lead.Email;
	    		this.telephoneLead = convertPhoneNumber(lead.MobilePhone);
	    		this.codePostal = lead.PostalCode;
	    		this.ville = lead.City;
	    		this.adresse = lead.Street;
				this.typeBesoin = lead.TypeOfNeed__c;
				this.echeanceBesoin = lead.Echeance_de_besoin_de_creation__c; 
				this.statutLegal = lead.LegalStatus__c; 
				this.activite = lead.Activity__c; 
				this.detailsActivite = lead.ActivityDetails__c; 
				this.utmSource = lead.UtmSource__c; 
				this.utmMedium = lead.UtmMedium__c;
				this.isExternalPartner = setIsExternalPartner(lead.Canal__c);
    		}
    		if(partenaire != null) {
    			this.idBureau = partenaire.IdBureauBaseGI__c.intValue();
    		}
    		if(contactPartenaire != null) {
	    		this.prenomContact = contactPartenaire.FirstName;
	    		this.nomContact = contactPartenaire.LastName;
    		}
    		if(referent != null) {
	    		this.prenomReferent = referent.FirstName;
	    		this.nomReferent = referent.LastName;
    		}
    	}
    	
    	public String generateJSON() {
    		return JSON.serialize(this);
    	}
    	
    	public void modifyLeadName(String newValue) {
    		this.nomLead = this.nomLead + newValue;
    	}
    	
    	private String convertPhoneNumber(String phoneNumber) {
    		return Utils.convertPhoneNumber(phoneNumber);
    	}
    	
    	private String checkCompanyName(String srcName) {
    		return (srcName != Constants.WS_BAGI_GENERIC_COMPANY_NAME ? srcName : '');
    	}
    	
    	private boolean setIsExternalPartner(String canal) {
    		return canal == Constants.LEAD_CANAL_PARTENARIATS;
    	}
    }
    
    public class WsConvertedAccountResponse {
    	public Integer code;
    	public String erreur;
    	public String url;
    	
    	public WsConvertedAccountResponse(Integer code, String erreur, String url) {
    		this.code = code;
    		this.erreur = erreur;
    		this.url = url;
    	}
    }
    
    public class WsConvertedAccountWrapper {
    	private Integer numeroDossier;
    	private String prenomContact;
    	private String nomContact;
    	private String telephoneContact;
    	private String emailContact;
    	private String adresse;
    	private String codePostal;
    	private String ville;
    	private String branding;
    	private List<WS03_BaseGI.MissionBGI> missions;
    	//private List<String> offres;
    	
    	
    	public WsConvertedAccountWrapper(Account account, Contact contact, List<Mission__c> missions) {
    		if(account != null) {
    			if((account.NumberBGI__c) != null) {
    				this.numeroDossier = account.NumberBGI__c.intValue();
    			}
    			this.adresse = account.BillingStreet;
    			this.codePostal = account.BillingPostalCode;
    			this.ville = account.BillingCity;
    			if(!account.opportunities.isEmpty()) {
    				this.branding = account.opportunities.get(0).Branding__c;
    			}
    		}
    		if(contact != null) {
    			this.prenomContact = contact.FirstName;
    			this.nomContact = contact.LastName;
    			this.telephoneContact = contact.MobilePhone;
    			this.emailContact = contact.Email;
    		}
    		this.missions = new List<WS03_BaseGI.MissionBGI>();
    		for(Mission__c m : missions) {
    			this.missions.add(new WS03_BaseGI.MissionBGI(
    				Integer.valueOf(m.MissionBgiId__c), 
    				m.Price__c, 
    				m.MissionName__c, 
    				m.OfferName__c, 
    				m.Comment__c
    			));
    		}
    	}
    	
    	public String generateJSON() {
    		return JSON.serialize(this);
    	}
    }
    
    public class WsGetOffresResponse {
    	public Integer code;
    	public String erreur;
    	public List<OffreBGI> offres;
    	
    	public WsGetOffresResponse(Integer code, String erreur, List<OffreBGI> offres) {
    		this.code = code;
    		this.erreur = erreur;
    		this.offres = offres;
    	}
    }
    
    // WS GetOffres
    public class OffreBGI {
    	private Integer id {get;set;}
    	private String designation {get;set;}
    	private List<MissionBGI> missions;
    	
    	public OffreBGI(Integer id, String designation, List<MissionBGI> missions) {
    		this.id = id;
    		this.designation = designation;
    		this.missions = missions;
    	}
    	public List<MissionBGI> getMissions() {
    		return this.missions;
    	}
    	public void setMissions(List<WS03_BaseGI.MissionBGI> missions) {
    		this.missions = missions;
    	}
    	public void addMission(WS03_BaseGI.MissionBGI mission) {
    		this.missions.add(mission);
    	}
    }
    
    public class MissionBGI {
    	private Integer id;
    	private Integer idMarque;
    	private Decimal tarif;
    	private Decimal tarifDeBase;
    	private String libelle;
    	private String periodicite;
    	private String commentaire;
    	private String offerName;
    	private Integer offerId;
    	public MissionBGI() {}
    	public MissionBGI(Integer id, Integer idMarque, Decimal tarif, String libelle, String periodicite) {
    		this.id = id;
    		this.idMarque = idMarque;
    		this.tarif = tarif;
    		this.libelle = libelle;
    	}
    	public MissionBGI(String id, Decimal tarif, Decimal tarifDeBase, String libelle, boolean periodicite, String commentaire, String offerName, String offerId) {
    		this.id = Integer.valueOf(id);
    		this.tarif = tarif;
    		this.tarifDeBase = tarifDeBase;
    		this.libelle = libelle;
    		this.periodicite = (periodicite ? 'M' : 'A');
    		this.commentaire = commentaire;
    		this.offerName = offerName;
    		this.offerId = Integer.valueOf(offerId);
    	}
    	public MissionBGI(Integer id, Decimal tarif, String libelle, String offerName, String commentaire) {
    		this.id = id;
    		this.tarif = tarif;
    		this.libelle = libelle;
    		this.offerName = offerName;
    		this.commentaire = commentaire;
    	}
    	public String getCommentaire(){return this.commentaire;}
    	public Integer getId(){return this.id;}
    	public String getLibelle(){return this.libelle;}
    	public String getOfferName(){return this.offerName;}
    	public Decimal getTarif(){return this.tarif;}
    	public Decimal getTarifDeBase(){return this.tarifDeBase;}
    	public String getPeriodicite(){return this.periodicite;}
    	public Integer getOfferId(){return this.offerId;}
    }
}