force-app/main/default/objects/Account/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>seo</fullName>
                <label>SEO</label>
            </value>
            <value>
                <fullName>paid-search</fullName>
                <label>Paid Search</label>
            </value>
            <value>
                <fullName>native</fullName>
                <label>Native</label>
            </value>
            <value>
                <fullName>paid-social-media</fullName>
                <label>Paid Social Media</label>
            </value>
            <value>
                <fullName>affiliation</fullName>
                <label>Affiliation</label>
            </value>
            <value>
                <fullName>partenariats</fullName>
                <label>Partenariats</label>
            </value>
            <value>
                <fullName>events</fullName>
                <label>Events</label>
            </value>
            <value>
                <fullName>reco-client</fullName>
                <label>Reco client</label>
            </value>
            <value>
                <fullName>presse</fullName>
                <label>Presse</label>
            </value>
            <value>
                <fullName>webinar</fullName>
                <label>Webinar</label>
            </value>
            <value>
                <fullName>inconnu</fullName>
                <label>Inconnu</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdBureauBaseGI__c.field-meta.xml
<CustomField>
    <fullName>IdBureauBaseGI__c</fullName>
    <description>Le numéro du bureau associé à ce cabinet dans la Base GI. Ne doit pas servir pour les comptes de type Client.</description>
    <label>Id Bureau BaseGI</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>Forme juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prestataire B2B</fullName>
            </value>
            <value>
                <fullName>Prestataire B2C</fullName>
            </value>
            <value>
                <fullName>Startup</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>HCR</fullName>
            </value>
            <value>
                <fullName>BTP</fullName>
            </value>
            <value>
                <fullName>Immobilier</fullName>
            </value>
            <value>
                <fullName>LMNP</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Agricole</fullName>
            </value>
            <value>
                <fullName>Industrie</fullName>
            </value>
            <value>
                <fullName>Production/Artiste</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ActivityDetails__c.field-meta.xml
<CustomField>
    <fullName>ActivityDetails__c</fullName>
    <label>Détails activité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>seo</fullName>
                <label>SEO</label>
            </value>
            <value>
                <fullName>paid-search</fullName>
                <label>Paid Search</label>
            </value>
            <value>
                <fullName>native</fullName>
                <label>Native</label>
            </value>
            <value>
                <fullName>paid-social-media</fullName>
                <label>Paid Social Media</label>
            </value>
            <value>
                <fullName>affiliation</fullName>
                <label>Affiliation</label>
            </value>
            <value>
                <fullName>partenariats</fullName>
                <label>Partenariats</label>
            </value>
            <value>
                <fullName>events</fullName>
                <label>Events</label>
            </value>
            <value>
                <fullName>reco-client</fullName>
                <label>Reco client</label>
            </value>
            <value>
                <fullName>presse</fullName>
                <label>Presse</label>
            </value>
            <value>
                <fullName>webinar</fullName>
            </value>
            <value>
                <fullName>inconnu</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>inbound</fullName>
                <isActive>false</isActive>
                <label>Inbound</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Contact_Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Partenaire</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Il est indispensable de choisir un contact du Cabinet Partenaire</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Partenaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contact Partenaire)</relationshipLabel>
    <relationshipName>LeadsContactPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Echeance_de_besoin_de_creation__c.field-meta.xml
<CustomField>
    <fullName>Echeance_de_besoin_de_creation__c</fullName>
    <label>Echéance de besoin de création</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immédiat</fullName>
            </value>
            <value>
                <fullName>1 mois</fullName>
            </value>
            <value>
                <fullName>3 mois</fullName>
            </value>
            <value>
                <fullName>6 mois et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>Forme Juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SASUSAS</fullName>
                <label>SASU / SAS</label>
            </value>
            <value>
                <fullName>EURLSARL</fullName>
                <label>EURL / SARL</label>
            </value>
            <value>
                <fullName>EntrepriseIndividuelle</fullName>
                <label>Entreprise Individuelle</label>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>SCI</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>NeSaitPas</fullName>
                <label>Ne sait pas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroCompteBaseGI__c.field-meta.xml
<CustomField>
    <fullName>NumeroCompteBaseGI__c</fullName>
    <description>l&#39;identifiant BaseGI du compte créé à partir de la Lead</description>
    <label>Numero Compte BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroIndividuBaseGI__c.field-meta.xml
<CustomField>
    <fullName>NumeroIndividuBaseGI__c</fullName>
    <description>l&#39;identifiant BaseGI de l&#39;individu créé à partir de la Lead</description>
    <label>Numero Individu BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Le compte partenaire doit être de type &#39;EC Partenaire&#39;. Pour les Partenariat, seuls les cabinets groupes sont valides.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>EC Partenaire</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partenariat</value>
        </filterItems>
        <filterItems>
            <field>$Source.PartnerType__c</field>
            <operation>equals</operation>
            <value>Groupe</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partenaire)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TypeOfNeed__c.field-meta.xml
<CustomField>
    <fullName>TypeOfNeed__c</fullName>
    <label>Type de besoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Création</fullName>
            </value>
            <value>
                <fullName>Comptabilité</fullName>
            </value>
            <value>
                <fullName>Création et Comptabilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UtmMedium__c.field-meta.xml
<CustomField>
    <fullName>UtmMedium__c</fullName>
    <label>Utm Medium</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cpc</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>social</fullName>
            </value>
            <value>
                <fullName>chat</fullName>
            </value>
            <value>
                <fullName>banner</fullName>
            </value>
            <value>
                <fullName>print</fullName>
            </value>
            <value>
                <fullName>offline</fullName>
            </value>
            <value>
                <fullName>gmail</fullName>
            </value>
            <value>
                <fullName>youtube</fullName>
            </value>
            <value>
                <fullName>outbrain</fullName>
            </value>
            <value>
                <fullName>nom-de-la-regie</fullName>
            </value>
            <value>
                <fullName>webself</fullName>
            </value>
            <value>
                <fullName>ligatus</fullName>
            </value>
            <value>
                <fullName>sesame</fullName>
            </value>
            <value>
                <fullName>salon-entrepreneur-19</fullName>
            </value>
            <value>
                <fullName>qonto</fullName>
            </value>
            <value>
                <fullName>LiveMentor</fullName>
            </value>
            <value>
                <fullName>Normandie Incubation</fullName>
            </value>
            <value>
                <fullName>taboola</fullName>
            </value>
            <value>
                <fullName>twitter</fullName>
            </value>
            <value>
                <fullName>form-sidebar-crea</fullName>
            </value>
            <value>
                <fullName>LP-Bilan-Rattrapage</fullName>
            </value>
            <value>
                <fullName>Adwords</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UtmSource__c.field-meta.xml
<CustomField>
    <fullName>UtmSource__c</fullName>
    <label>Utm_source</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LegalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASS</fullName>
    </customValue>
    <customValue>
        <fullName>EARL</fullName>
    </customValue>
    <customValue>
        <fullName>EIRL</fullName>
    </customValue>
    <customValue>
        <fullName>EURL</fullName>
    </customValue>
    <customValue>
        <fullName>GAEC</fullName>
    </customValue>
    <customValue>
        <fullName>GFA</fullName>
    </customValue>
    <customValue>
        <fullName>GIE</fullName>
    </customValue>
    <customValue>
        <fullName>GPT</fullName>
    </customValue>
    <customValue>
        <fullName>IND</fullName>
    </customValue>
    <customValue>
        <fullName>SA</fullName>
    </customValue>
    <customValue>
        <fullName>SARL</fullName>
    </customValue>
    <customValue>
        <fullName>SAS</fullName>
    </customValue>
    <customValue>
        <fullName>SASU</fullName>
    </customValue>
    <customValue>
        <fullName>SC</fullName>
    </customValue>
    <customValue>
        <fullName>SCCV</fullName>
    </customValue>
    <customValue>
        <fullName>SCEA</fullName>
    </customValue>
    <customValue>
        <fullName>SCI</fullName>
    </customValue>
    <customValue>
        <fullName>SCIC</fullName>
    </customValue>
    <customValue>
        <fullName>SCM</fullName>
    </customValue>
    <customValue>
        <fullName>SCOP</fullName>
    </customValue>
    <customValue>
        <fullName>SCP</fullName>
    </customValue>
    <customValue>
        <fullName>SCS</fullName>
    </customValue>
    <customValue>
        <fullName>SDF</fullName>
    </customValue>
    <customValue>
        <fullName>SELARL</fullName>
    </customValue>
    <customValue>
        <fullName>SELARLU</fullName>
    </customValue>
    <customValue>
        <fullName>SELAS</fullName>
    </customValue>
    <customValue>
        <fullName>SELASU</fullName>
    </customValue>
    <customValue>
        <fullName>SEP</fullName>
    </customValue>
    <customValue>
        <fullName>SISA</fullName>
    </customValue>
    <customValue>
        <fullName>SNC</fullName>
    </customValue>
    <masterLabel>Formes juridiques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WS03_BaseGI_CreateDossierBGI.cls
public with sharing class WS03_BaseGI_CreateDossierBGI extends WS03_BaseGI {
    
    public WS03_BaseGI_CreateDossierBGI() {
    	prepareRequest(Constants.WS_BAGI_ACC_CREA_FROM_LEAD_AUTH_NAME);
    	this.isFromAuraComponent = true;
		this.mustLogError = true;
    }
    
    public override HttpResponse callMock(HttpRequest req) {
    	MockHttpResponse mock = new MockHttpResponse();
    	return mock.respondCreateAccountFromLead(this.req);
    }
    
    public void createAccountFromLead(Id leadId) {
    	
    	List<Lead> leads = [SELECT Id, Company, FirstName, LastName, Name, Email, MobilePhone, OwnerId, City, PostalCode, Street, NumeroCompteBaseGI__c, NumeroIndividuBaseGI__c,
		TypeOfNeed__c, Echeance_de_besoin_de_creation__c, LegalStatus__c, Activity__c, ActivityDetails__c, UtmSource__c, UtmMedium__c, partenaire__c, Canal__c, 
    		partenaire__r.IdBureauBaseGI__c, Contact_Partenaire__r.FirstName, Contact_Partenaire__r.LastName FROM Lead WHERE Id = :leadId AND NumeroCompteBaseGI__c = null];
    	if(!leads.isEmpty()) {
    		Lead lead = leads.get(0);
	    	if(lead != null && lead.partenaire__c != null && lead.partenaire__r.IdBureauBaseGI__c != null) {
		    		
			    User user = [SELECT FirstName, LastName FROM User WHERE Id = :lead.OwnerId];
			    	
			    WS03_BaseGI.WsAccountFromLeadWrapper wrapper = new WS03_BaseGI.WsAccountFromLeadWrapper(lead, lead.partenaire__r, lead.Contact_Partenaire__r, user);
			    this.req.setBody(wrapper.generateJSON());
			    //System.debug(req.getBody());
			    //System.debug(req);
			    
			    handleWsRequest(wrapper, lead, 0);
	    	}
    	}
    }
    
    private void handleWsRequest(WsAccountFromLeadWrapper wrapper, Lead lead, Integer deepGauge) {
    	deepGauge++;
    	HttpResponse resp = sendRequest();
    	
    	if(resp != null) {
		    WS03_BaseGI.WsAccountFromLeadResponse respObject = (WS03_BaseGI.WsAccountFromLeadResponse) JSON.deserializeStrict(resp.getBody(), WsAccountFromLeadResponse.class);//Untyped
		    	
		   	if(String.IsNotBlank(respObject.erreur)) {
		   		if(respObject.code == Constants.WS_BAGI_ERROR_CODE_DUPLICATE && deepGauge == 1) {
		   			wrapper.modifyLeadName(' ' + DateTime.now().format(('dd-MM-YYYY HH\'h\'mm')));
		   			this.req.setBody(wrapper.generateJSON());
		   			handleWsRequest(wrapper, lead, deepGauge);
		   		} else {
		   			//Utils.createLogError('Erreur lors de création du dossier BGI pour la lead Id ' + lead.Id + ': ' + respObject.erreur);
		   			throw new AuraHandledException('Erreur lors de création du dossier BaseGI pour la lead Id ' + lead.Id + ': ' + respObject.erreur);
		   		}
		   	} else {
	    		lead.NumeroCompteBaseGI__c = respObject.numeroDossier;
	    		lead.NumeroIndividuBaseGI__c = respObject.idIndividu;
	    		update lead;
	    	}
	    }
    }
}