force-app/main/default/objects/Account/fields/AnnualTurnover__c.field-meta.xml
<CustomField>
    <fullName>AnnualTurnover__c</fullName>
    <label>Chiffre d&#39;affaires Annuel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-39</fullName>
                <label>0 - 39K€</label>
            </value>
            <value>
                <fullName>40-99</fullName>
                <label>40 - 99K€</label>
            </value>
            <value>
                <fullName>100-249</fullName>
                <label>100 - 249K€</label>
            </value>
            <value>
                <fullName>250-999</fullName>
                <label>250 - 999K€</label>
            </value>
            <value>
                <fullName>1000-2999</fullName>
                <label>1000 - 2999K€</label>
            </value>
            <value>
                <fullName>3000-9999</fullName>
                <label>3000 - 9999K€</label>
            </value>
            <value>
                <fullName>10000-99999</fullName>
                <label>10000 - 99999K€</label>
            </value>
            <value>
                <fullName>100000-*</fullName>
                <label>100000K€ et plus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LastNetIncome__c.field-meta.xml
<CustomField>
    <fullName>LastNetIncome__c</fullName>
    <description>Champs nécessaire à Wallet</description>
    <label>Dernier résultat en K€</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-4</fullName>
            </value>
            <value>
                <fullName>5-9</fullName>
            </value>
            <value>
                <fullName>10-49</fullName>
            </value>
            <value>
                <fullName>50-149</fullName>
            </value>
            <value>
                <fullName>150-499</fullName>
            </value>
            <value>
                <fullName>500-*</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>Forme juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>Nombre d&#39;employés</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-9</fullName>
            </value>
            <value>
                <fullName>10-99</fullName>
            </value>
            <value>
                <fullName>100-249</fullName>
            </value>
            <value>
                <fullName>250 et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ValidatedForAppWallet__c.field-meta.xml
<CustomField>
    <fullName>ValidatedForAppWallet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validée pour l’App Wallet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/WalletStatus__c.field-meta.xml
<CustomField>
    <fullName>WalletStatus__c</fullName>
    <label>Statut Wallet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CGUPending</fullName>
                <label>CGU</label>
            </value>
            <value>
                <fullName>TIIMEPending</fullName>
                <label>Nouveau</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <label>Incomplet</label>
            </value>
            <value>
                <fullName>KYCPending</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>KYCRefused</fullName>
                <label>KYC Refusé</label>
            </value>
            <value>
                <fullName>KYCValidated</fullName>
                <label>KYC Validé</label>
            </value>
            <value>
                <fullName>CBOrdered</fullName>
                <label>CB Commandée</label>
            </value>
            <value>
                <fullName>CBActivated</fullName>
                <label>CB Activée</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Fermé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/BirthPlace__c.field-meta.xml
<CustomField>
    <fullName>BirthPlace__c</fullName>
    <label>Ville de naissance</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IncomPerTranche__c.field-meta.xml
<CustomField>
    <fullName>IncomPerTranche__c</fullName>
    <label>Revenus par Tranche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 - 18 K€</fullName>
            </value>
            <value>
                <fullName>19 - 23 K€</fullName>
            </value>
            <value>
                <fullName>24 - 27K€</fullName>
            </value>
            <value>
                <fullName>28 - 35K€</fullName>
            </value>
            <value>
                <fullName>36 - 56K€</fullName>
            </value>
            <value>
                <fullName>57K€ ou plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationalité</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NativeCountry__c.field-meta.xml
<CustomField>
    <fullName>NativeCountry__c</fullName>
    <label>Pays de naissance</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Networth__c.field-meta.xml
<CustomField>
    <fullName>Networth__c</fullName>
    <label>Patrimoine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 - 2K€</fullName>
            </value>
            <value>
                <fullName>3 - 22K€</fullName>
            </value>
            <value>
                <fullName>23 - 128K€</fullName>
            </value>
            <value>
                <fullName>129 - 319K€</fullName>
            </value>
            <value>
                <fullName>420 - 464K€</fullName>
            </value>
            <value>
                <fullName>465K€ et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Nom du Stakeholder</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stakeholder__c/fields/ActualBeneficiary__c.field-meta.xml
<CustomField>
    <fullName>ActualBeneficiary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>se coche automatiquement si + de 25% des part dans son entreprise</description>
    <label>Bénéficiaire effectif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stakeholders</relationshipLabel>
    <relationshipName>Parties_Prenantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne Physique</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Parties_PrenantesPP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Type de personne physique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mandataire social</fullName>
                <default>true</default>
                <label>Mandataire social</label>
            </value>
            <value>
                <fullName>Bénéficiaire Effectif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/JobTitleBank__c.field-meta.xml
<CustomField>
    <fullName>JobTitleBank__c</fullName>
    <label>Fonction</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/MainStakeholder__c.field-meta.xml
<CustomField>
    <fullName>MainStakeholder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permet d&#39;identifier le Stakeholder propriétaire du Wallet</description>
    <label>Stakeholder Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Officer__c.field-meta.xml
<CustomField>
    <fullName>Officer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandataire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/LegalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASS</fullName>
    </customValue>
    <customValue>
        <fullName>EARL</fullName>
    </customValue>
    <customValue>
        <fullName>EIRL</fullName>
    </customValue>
    <customValue>
        <fullName>EURL</fullName>
    </customValue>
    <customValue>
        <fullName>GAEC</fullName>
    </customValue>
    <customValue>
        <fullName>GFA</fullName>
    </customValue>
    <customValue>
        <fullName>GIE</fullName>
    </customValue>
    <customValue>
        <fullName>GPT</fullName>
    </customValue>
    <customValue>
        <fullName>IND</fullName>
    </customValue>
    <customValue>
        <fullName>SA</fullName>
    </customValue>
    <customValue>
        <fullName>SARL</fullName>
    </customValue>
    <customValue>
        <fullName>SAS</fullName>
    </customValue>
    <customValue>
        <fullName>SASU</fullName>
    </customValue>
    <customValue>
        <fullName>SC</fullName>
    </customValue>
    <customValue>
        <fullName>SCCV</fullName>
    </customValue>
    <customValue>
        <fullName>SCEA</fullName>
    </customValue>
    <customValue>
        <fullName>SCI</fullName>
    </customValue>
    <customValue>
        <fullName>SCIC</fullName>
    </customValue>
    <customValue>
        <fullName>SCM</fullName>
    </customValue>
    <customValue>
        <fullName>SCOP</fullName>
    </customValue>
    <customValue>
        <fullName>SCP</fullName>
    </customValue>
    <customValue>
        <fullName>SCS</fullName>
    </customValue>
    <customValue>
        <fullName>SDF</fullName>
    </customValue>
    <customValue>
        <fullName>SELARL</fullName>
    </customValue>
    <customValue>
        <fullName>SELARLU</fullName>
    </customValue>
    <customValue>
        <fullName>SELAS</fullName>
    </customValue>
    <customValue>
        <fullName>SELASU</fullName>
    </customValue>
    <customValue>
        <fullName>SEP</fullName>
    </customValue>
    <customValue>
        <fullName>SISA</fullName>
    </customValue>
    <customValue>
        <fullName>SNC</fullName>
    </customValue>
    <masterLabel>Formes juridiques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactsValidationCtrl.cls
public class ContactsValidationCtrl {
    /*
     * @author Wailly LUA
     * @date 03/10/2018 (dd/mm/yyyy)
     * @description : method launch from ContactsValidation component to fetch all the stakeholders link to the accountId sent from parameters
     * @params :      
     *      accountId : Id of the Account
     */
    @AuraEnabled
    public static Stakeholder__c[] getStakeHolders(Id accountId){
        System.debug('### ContactsValidationCtrl getStakeHolders accountId=='+accountId);
        return [SELECT Id, Company__r.ValidatedForAppWallet__c, Contact__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Birthdate, 
        Contact__r.Salutation, Contact__r.BirthPlace__c, Contact__r.Nationality__c, Contact__r.Email, 
        Contact__r.MobilePhone, Contact__r.NativeCountry__c, Contact__r.IncomPerTranche__c, Contact__r.Networth__c, JobTitleBank__c, ContactType__c, MainStakeholder__c
        //FROM Stakeholder__c];
        FROM Stakeholder__c WHERE (ActualBeneficiary__c = true OR Officer__c = true) AND Company__c = :accountId];
    }

    /*
     * @author Wailly LUA
     * @date 03/10/2018 (dd/mm/yyyy)
     * @description : method launch from ContactsValidation component to update the stakeholder AND the contact linked to the stakeholder (annuaire)
     * @params :      
     *      contact : Id of the Stakeholder to update
     */
    @AuraEnabled
    public static void updateContact(Stakeholder__c contact){
        System.debug('### ContactsValidationCtrl updateContact BEGIN');
        System.debug('### ContactsValidationCtrl updateContact contact=='+contact);
        try{            
        	Stakeholder__c stakeHolder = new Stakeholder__c(Id=contact.Id);
        	stakeHolder.JobTitleBank__c = contact.JobTitleBank__c;
        	stakeHolder.ContactType__c = contact.ContactType__c;

        	Contact annuaire = new Contact(Id = contact.Contact__c);
        	annuaire.FirstName = contact.Contact__r.FirstName; 
        	annuaire.LastName = contact.Contact__r.LastName;
            annuaire.Birthdate = contact.Contact__r.BirthDate;
        	annuaire.BirthPlace__c = contact.Contact__r.BirthPlace__c;
        	annuaire.Nationality__c = contact.Contact__r.Nationality__c;
        	annuaire.Email = contact.Contact__r.Email; 
        	annuaire.MobilePhone = contact.Contact__r.MobilePhone; 
        	annuaire.NativeCountry__c = contact.Contact__r.NativeCountry__c; 
        	annuaire.IncomPerTranche__c = contact.Contact__r.IncomPerTranche__c; 
        	annuaire.Networth__c = contact.Contact__r.Networth__c;
            
            update annuaire;
            update stakeHolder;
            
        }catch(DmlException dmlEx){
            System.debug('### ContactsValidationCtrl updateContact dmlEx.getDmlMessage(0)=='+dmlEx.getDmlMessage(0));
            throw new AuraHandledException(dmlEx.getDmlMessage(0));
        }catch(Exception ex){
        	System.debug('### ContactsValidationCtrl updateContact ex.getDmlMessage(0)=='+ex.getMessage());
    		throw new AuraHandledException(ex.getMessage());
        }
        System.debug('### ContactsValidationCtrl updateContact END');
    }

    /*
     * @author Wailly LUA
     * @date 03/10/2018 (dd/mm/yyyy)
     * @description : generic method to fetch picklist value from specific object
     * @return :
     *      allOptions : Map<Integer,List<String>>, contains values of picklist
     *                   allOptions[0] = picklist values of IncomPerTranche__c
     *                   allOptions[1] = picklist values of Networth__c
     *                   allOptions[2] = picklist values of ContactType__c
     */
    @AuraEnabled
    public static Map<Integer,List<String>> fetchPicklistValues(){
        List<String> incomOptions = getSelectOptions('Contact','IncomPerTranche__c');
        List<String> networthOptions = getSelectOptions('Contact','Networth__c');
        List<String> contactTypeOptions = getSelectOptions('Stakeholder__c','ContactType__c');
        
        System.debug('### incomOptions=='+incomOptions);
        System.debug('### networthOptions=='+networthOptions);
        System.debug('### contactTypeOptions=='+contactTypeOptions);
        Map<Integer,List<String>> allOptions = new Map<Integer, List<String>>();

        allOptions.put(0,incomOptions);
        allOptions.put(1,networthOptions);
        allOptions.put(2,contactTypeOptions);

        return allOptions;
    }

    /*
     * @author Wailly LUA
     * @date 26/09/2018 (dd/mm/yyyy)
     * @description : generic method to fetch picklist value from specific object
     * @params :      
     *      objectType : Type of Object to fetch
     *      fieldName : Picklist field which we want to fetch the values
     * @return :
     *      lst : List of String, contains values of specific picklist sent from parameter
     */
	 public static List<String> getSelectOptions(String objType, string fieldName) {
		List<String> allOpts = new list<String>();

        Schema.DescribeSObjectResult objDescribe = Schema.getGlobalDescribe().get(objType).getDescribe();
		Map<String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
		list<Schema.PicklistEntry> values = fieldMap.get(fieldName).getDescribe().getPickListValues();

		// Add these values to the selectoption list.
		for (Schema.PicklistEntry a: values) {
			allOpts.add(a.getValue());
		}
		System.debug('### ContactsValidationCtrl getSelectOptions allOpts ---->' + allOpts);
		return allOpts;
	 }

     /*
     * @author Jérémy LAMBERT
     * @date 04/12/2018 (dd/mm/yyyy)
     * @description : HTTP Call to Chronos to enable Wallet for the main stakeholder of the given record
     * @params :      
     *      recordId : Account record Id
     */
     @AuraEnabled
     public static void enableWallet(String recordId) {
     	System.debug('### ContatctsValisationCtrl - begin enableWallet');
        List<Account> accounts = [SELECT Id,ValidatedForAppWallet__c FROM Account WHERE Id = :recordId];
        if(accounts.size() <= 0)
            throw new AuraHandledException('L\'entreprise n\'existe pas.');
        AP10_ChronosEnableWallet.enableWallet(recordId);
        
        Account account = accounts.get(0);
        account.ValidatedForAppWallet__c = true;
        update account;
        System.debug('### ContatctsValisationCtrl - end enableWallet');
     }
     
     @AuraEnabled
     public static void changeStatusWallet(Id accountId) {
     	update new Account(Id = accountId, WalletStatus__c = Constants.ACCOUNT_WALLET_STATUS_CGU_PENDING);
     }

     @AuraEnabled
     public static Map<String, Map<String, String>> getCompanyPicklistValues() {
        Map<String, Map<String, String>> result = new Map<String, Map<String, String>>();
        result.put('turnovers', Utils.getPicklistOptions('Account', 'AnnualTurnover__c'));
        result.put('employees', Utils.getPicklistOptions('Account', 'NumberOfEmployees__c'));
        result.put('incomes', Utils.getPicklistOptions('Account', 'LastNetIncome__c'));
        result.put('legalForms', Utils.getPicklistOptionsWithNoneOption('Account', 'LegalStatus__c', true));
        result.put('contactSalutation', Utils.getPicklistOptionsWithNoneOption('Contact','Salutation', true));
        return result;
     }
}