force-app/main/default/objects/Account/fields/AnnualTurnover__c.field-meta.xml
<CustomField>
    <fullName>AnnualTurnover__c</fullName>
    <label>Chiffre d&#39;affaires Annuel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-39</fullName>
                <label>0 - 39K€</label>
            </value>
            <value>
                <fullName>40-99</fullName>
                <label>40 - 99K€</label>
            </value>
            <value>
                <fullName>100-249</fullName>
                <label>100 - 249K€</label>
            </value>
            <value>
                <fullName>250-999</fullName>
                <label>250 - 999K€</label>
            </value>
            <value>
                <fullName>1000-2999</fullName>
                <label>1000 - 2999K€</label>
            </value>
            <value>
                <fullName>3000-9999</fullName>
                <label>3000 - 9999K€</label>
            </value>
            <value>
                <fullName>10000-99999</fullName>
                <label>10000 - 99999K€</label>
            </value>
            <value>
                <fullName>100000-*</fullName>
                <label>100000K€ et plus</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ApeCode__c.field-meta.xml
<CustomField>
    <fullName>ApeCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code APE</label>
    <referenceTo>ApeCode__c</referenceTo>
    <relationshipLabel>Entreprises</relationshipLabel>
    <relationshipName>entreprises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChronosId__c.field-meta.xml
<CustomField>
    <fullName>ChronosId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Identifiant de la company dans Chronos</description>
    <externalId>true</externalId>
    <label>Id chronos</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CompanyCreated__c.field-meta.xml
<CustomField>
    <fullName>CompanyCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entreprise créée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastNetIncome__c.field-meta.xml
<CustomField>
    <fullName>LastNetIncome__c</fullName>
    <description>Champs nécessaire à Wallet</description>
    <label>Dernier résultat en K€</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-4</fullName>
            </value>
            <value>
                <fullName>5-9</fullName>
            </value>
            <value>
                <fullName>10-49</fullName>
            </value>
            <value>
                <fullName>50-149</fullName>
            </value>
            <value>
                <fullName>150-499</fullName>
            </value>
            <value>
                <fullName>500-*</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>Forme juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MainEmail__c.field-meta.xml
<CustomField>
    <fullName>MainEmail__c</fullName>
    <label>Email principal</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/MainPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>MainPhoneNumber__c</fullName>
    <label>Téléphone Principal</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <label>Nombre d&#39;employés</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-9</fullName>
            </value>
            <value>
                <fullName>10-99</fullName>
            </value>
            <value>
                <fullName>100-249</fullName>
            </value>
            <value>
                <fullName>250 et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDate__c</fullName>
    <label>Date d&#39;immatriculation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ShareCapital__c.field-meta.xml
<CustomField>
    <fullName>ShareCapital__c</fullName>
    <label>Capital social</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <externalId>true</externalId>
    <label>SIRET</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApeCode__c/ApeCode__c.object-meta.xml
<CustomObject>
    <label>Code APE</label>
    <nameField>
        <label>Nom de Code APE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codes APE</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuthChronos__mdt/AuthChronos__mdt.object-meta.xml
<CustomObject>
    <label>AuthChronos</label>
    <pluralLabel>AuthsChronos</pluralLabel>
</CustomObject>

force-app/main/default/objects/AuthChronos__mdt/fields/audience__c.field-meta.xml
<CustomField>
    <fullName>audience__c</fullName>
    <label>audience</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuthChronos__mdt/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client_id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuthChronos__mdt/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client_secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuthChronos__mdt/fields/grant_type__c.field-meta.xml
<CustomField>
    <fullName>grant_type__c</fullName>
    <label>grant_type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuthChronos__mdt/fields/realm__c.field-meta.xml
<CustomField>
    <fullName>realm__c</fullName>
    <label>realm</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuthChronos__mdt/fields/scope__c.field-meta.xml
<CustomField>
    <fullName>scope__c</fullName>
    <label>scope</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuthChronos__mdt/fields/url_chronos_api__c.field-meta.xml
<CustomField>
    <fullName>url_chronos_api__c</fullName>
    <label>url_chronos_api</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BirthPlace__c.field-meta.xml
<CustomField>
    <fullName>BirthPlace__c</fullName>
    <label>Ville de naissance</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ChronosId__c.field-meta.xml
<CustomField>
    <fullName>ChronosId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Identifiant unique du User dans Chronos</description>
    <externalId>true</externalId>
    <label>Id Chronos</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationalité</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NativeCountry__c.field-meta.xml
<CustomField>
    <fullName>NativeCountry__c</fullName>
    <label>Pays de naissance</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Nom du Stakeholder</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stakeholder__c/fields/ActualBeneficiary__c.field-meta.xml
<CustomField>
    <fullName>ActualBeneficiary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>se coche automatiquement si + de 25% des part dans son entreprise</description>
    <label>Bénéficiaire effectif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/ChronosId__c.field-meta.xml
<CustomField>
    <fullName>ChronosId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id chronos</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stakeholders</relationshipLabel>
    <relationshipName>Parties_Prenantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne Physique</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Parties_PrenantesPP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/MainStakeholder__c.field-meta.xml
<CustomField>
    <fullName>MainStakeholder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permet d&#39;identifier le Stakeholder propriétaire du Wallet</description>
    <label>Stakeholder Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Officer__c.field-meta.xml
<CustomField>
    <fullName>Officer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandataire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/ShareCapital__c.field-meta.xml
<CustomField>
    <fullName>ShareCapital__c</fullName>
    <formula>Company__r.ShareCapital__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capital social</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/LegalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASS</fullName>
    </customValue>
    <customValue>
        <fullName>EARL</fullName>
    </customValue>
    <customValue>
        <fullName>EIRL</fullName>
    </customValue>
    <customValue>
        <fullName>EURL</fullName>
    </customValue>
    <customValue>
        <fullName>GAEC</fullName>
    </customValue>
    <customValue>
        <fullName>GFA</fullName>
    </customValue>
    <customValue>
        <fullName>GIE</fullName>
    </customValue>
    <customValue>
        <fullName>GPT</fullName>
    </customValue>
    <customValue>
        <fullName>IND</fullName>
    </customValue>
    <customValue>
        <fullName>SA</fullName>
    </customValue>
    <customValue>
        <fullName>SARL</fullName>
    </customValue>
    <customValue>
        <fullName>SAS</fullName>
    </customValue>
    <customValue>
        <fullName>SASU</fullName>
    </customValue>
    <customValue>
        <fullName>SC</fullName>
    </customValue>
    <customValue>
        <fullName>SCCV</fullName>
    </customValue>
    <customValue>
        <fullName>SCEA</fullName>
    </customValue>
    <customValue>
        <fullName>SCI</fullName>
    </customValue>
    <customValue>
        <fullName>SCIC</fullName>
    </customValue>
    <customValue>
        <fullName>SCM</fullName>
    </customValue>
    <customValue>
        <fullName>SCOP</fullName>
    </customValue>
    <customValue>
        <fullName>SCP</fullName>
    </customValue>
    <customValue>
        <fullName>SCS</fullName>
    </customValue>
    <customValue>
        <fullName>SDF</fullName>
    </customValue>
    <customValue>
        <fullName>SELARL</fullName>
    </customValue>
    <customValue>
        <fullName>SELARLU</fullName>
    </customValue>
    <customValue>
        <fullName>SELAS</fullName>
    </customValue>
    <customValue>
        <fullName>SELASU</fullName>
    </customValue>
    <customValue>
        <fullName>SEP</fullName>
    </customValue>
    <customValue>
        <fullName>SISA</fullName>
    </customValue>
    <customValue>
        <fullName>SNC</fullName>
    </customValue>
    <masterLabel>Formes juridiques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP10_ChronosEnableWallet.cls
public with sharing class AP10_ChronosEnableWallet {

	public class InvalidPhoneException extends Exception {}

	// Dummy classes for JSON Serialization
	
    private class Company {
		public String  legal_form      			{ get; set; }
		public String  name            			{ get; set; }
		public String  phone           			{ get; set; }
		public Boolean company_created 			{ get; set; }
		public String  siret           			{ get; set; }
		public String  street          			{ get; set; }
		public String  postal_code     			{ get; set; }
		public String  city            			{ get; set; }
        public String  main_email            	{ get; set; }
        public ApeCode  ape_code            	{ get; set; }
        public String  registration_date        { get; set; }
        public String  annual_turnover          { get; set; }
        public String  employees_range          { get; set; }
        public String  last_net_income_range	{ get; set; }
        public String  country          		{ get; set; }
		//public Decimal share_capital   { get; set; }
	}
    
	private class User {
		public String lastname  			{ get; set; }
		public String firstname 			{ get; set; }
		public String email     			{ get; set; }
		public String phone     			{ get; set; }
        public String civility     			{ get; set; }
        public String birth_date     		{ get; set; }
        public String mailing_street     	{ get; set; }
        public String mailing_postal_code	{ get; set; }
        public String mailing_city     		{ get; set; }
        public String mailing_country     	{ get; set; }
        public String nationality     		{ get; set; }
        public String birth_place     		{ get; set; }
        public String birth_country     	{ get; set; }
        public List<Company> companies		{ get; set; }
	}

	

	private class WalletParameters {
		public String lastname  			{ get; set; }
		public String firstname 			{ get; set; }
		public String email     			{ get; set; }
		public String phone     			{ get; set; }
        public String civility     			{ get; set; }
        public String birth_date     		{ get; set; }
        public String mailing_street     	{ get; set; }
        public String mailing_postal_code	{ get; set; }
        public String mailing_city     		{ get; set; }
        public String mailing_country     	{ get; set; }
        public String nationality     		{ get; set; }
        public String birth_place     		{ get; set; }
        public String birth_country     	{ get; set; }
        public List<Company> companies		{ get; set; }
		
		//public User    user    { get; set; }
		//public Company company { get; set; }
	}
    
    private class ApeCode {
        public String code 	{ get;set; }
        
        public ApeCode(String code) {
            this.code = code;
        }
    } 

	// Two identical classes because attributes
	// can be different in the future
	private class ChronosUserResponse {
		public Integer id { get; set; }
	}

	private class ChronosCompanyResponse {
		public Integer id { get; set; }
	}

	private class ChronosResponse {
		public ChronosUserResponse    user    { get; set; }
		public ChronosCompanyResponse company { get; set; }
	}

	//-------------------------------------------------------------------------

	/*
	 * @author Jérémy LAMBERT
	 * @date 04/12/2018 (dd/mm/yyyy)
	 * @description : Get the Id of the main stakeholder for the given account
	 * @params :
	 *      recordId : Account record Id
	 * @return :
	 *      stakeholder : record of the main stakeholder, throws AuraHandledException on error
	 */
	@TestVisible
	private static StakeHolder__c getMainStakeholder(String accountId) {
		List<Stakeholder__c> stakeholders = 
            [SELECT Id, Contact__c, Contact__r.Salutation, Contact__r.FirstName, Contact__r.LastName, Contact__r.Email, Contact__r.MobilePhone, Contact__r.Birthdate, 
             Contact__r.MailingStreet, Contact__r.MailingPostalCode, Contact__r.MailingCity, Contact__r.MailingCountry, Contact__r.Nationality__c,
             Contact__r.BirthPlace__c, Contact__r.NativeCountry__c, Contact__r.ChronosId__c FROM Stakeholder__c WHERE (ActualBeneficiary__c = true OR Officer__c = true) AND MainStakeholder__c = true AND Company__c = :accountId];
		if(stakeholders.size() == 1) {
			return stakeholders[0];
		} else if(stakeholders.size() > 1)
			throw Utils.generateAuraHandledException('Plusieurs stakeholder principaux.');

		throw Utils.generateAuraHandledException('Aucun stakeholder trouvé.');
	}

	private static User getUser(StakeHolder__c sh, Id companyId) {
		User user = new User();
		user.firstname = sh.Contact__r.FirstName;
		user.lastname = sh.Contact__r.LastName;
		user.email = sh.Contact__r.Email;
		user.phone = formatPhoneNumber(sh.Contact__r.MobilePhone);
        user.civility = sh.Contact__r.Salutation;
		user.birth_date = formatDateForChronos(sh.Contact__r.Birthdate);
		user.mailing_street = sh.Contact__r.MailingStreet;
		user.mailing_postal_code = sh.Contact__r.MailingPostalCode;
		user.mailing_city = sh.Contact__r.MailingCity;
		user.mailing_country = sh.Contact__r.MailingCountry;
		user.nationality = sh.Contact__r.Nationality__c;
		user.birth_place = sh.Contact__r.BirthPlace__c;
		user.birth_country = sh.Contact__r.NativeCountry__c;
        user.companies = new List<Company> {getCompany(companyId)};

		return user;
	}

	/*
	 * @author Jérémy LAMBERT
	 * @date 03/05/2019 (dd/mm/yyyy)
	 * @description : Generate Company object from given Account Id
	 * @params :
	 *      recordId : Account record Id
	 * @return :
	 *      company : the company object to be serialized, throws AuraHandledException on error
	 */
	private static Company getCompany(Id companyId) {
		List<Account> accounts = [SELECT Id, LegalStatus__c, Name, MainPhoneNumber__c, CompanyCreated__c, Siret__c, BillingStreet,BillingCity,BillingPostalCode, BillingCountry, 
                                  ShareCapital__c, MainEmail__c, ApeCode__r.Name, RegistrationDate__c, AnnualTurnover__c, NumberOfEmployees__c, LastNetIncome__c 
                                  FROM Account WHERE Id = :companyId];
		if(accounts.size() == 1) {
			Account account = accounts[0];
			Company company = new Company();
			company.legal_form = account.LegalStatus__c;
			company.name = account.Name;
			company.phone = formatPhoneNumber(account.MainPhoneNumber__c);
			company.company_created = account.CompanyCreated__c;
			company.siret = account.Siret__c;
			company.street = account.BillingStreet;
			company.postal_code = account.BillingPostalCode;
			company.city = account.BillingCity;
            company.main_email = account.MainEmail__c;
            company.ape_code = new ApeCode(account.ApeCode__r.Name);
            company.registration_date = formatDateForChronos(account.RegistrationDate__c);
            company.annual_turnover = account.AnnualTurnover__c;
            company.employees_range = account.NumberOfEmployees__c;
            company.last_net_income_range = account.LastNetIncome__c;
            company.country = account.BillingCountry;
			//company.share_capital = account.ShareCapital__c;
			return company;
		}

		throw Utils.generateAuraHandledException('Aucune entreprise trouvée.');
	}

	/*
	 * @author Jérémy LAMBERT
	 * @date 03/05/2019 (dd/mm/yyyy)
	 * @description : Generate the JSON body for wallet activation.
	 * @params :
	 *      recordId : Account record Id
	 *      mainStakeholder : the main stakeholder of the Account
	 * @return :
	 *      body : the json body ready to be sent to Chronos, throws AuraHandledException on error
	 */
	private static String generateBody(Id recordId, Stakeholder__c sh) {
		WalletParameters params = new WalletParameters();

		//params.user    = getUser(mainStakeholder, Id.valueOf(recordId));
		//User user = new User();
		params.firstname = sh.Contact__r.FirstName;
		params.lastname = sh.Contact__r.LastName;
		params.email = sh.Contact__r.Email;
		params.phone = formatPhoneNumber(sh.Contact__r.MobilePhone);
        params.civility = sh.Contact__r.Salutation;
		params.birth_date = formatDateForChronos(sh.Contact__r.Birthdate);
		params.mailing_street = sh.Contact__r.MailingStreet;
		params.mailing_postal_code = sh.Contact__r.MailingPostalCode;
		params.mailing_city = sh.Contact__r.MailingCity;
		params.mailing_country = sh.Contact__r.MailingCountry;
		params.nationality = sh.Contact__r.Nationality__c;
		params.birth_place = sh.Contact__r.BirthPlace__c;
		params.birth_country = sh.Contact__r.NativeCountry__c;
        params.companies = new List<Company> {getCompany(Id.valueOf(recordId))};
		//params.company = getCompany(Id.valueOf(recordId));

		return JSON.serialize(params);
	}

	/*
	 * @author Jérémy LAMBERT
	 * @date 13/05/2019 (dd/mm/yyyy)
	 * @description : Format a phone number to the "+33" format. Returns
	 * the input number if already using good format.
	 * @params :
	 *      phone : the phone number to format
	 * @return :
	 *      formattedPhone : the formatted phone number
	 */
	@TestVisible
	private static String formatPhoneNumber(String phone) {
		if(phone != null) {
			if(phone.startsWith('0')) {
				return phone.replaceFirst('0', '+33');
			} else if(!phone.startsWith('+33')) {
				throw new InvalidPhoneException('Invalid phone number.');
			}
		}

		return phone;
	}
    
    private static String formatDateForChronos(Date dateValue) {
        String dateResult;
        if(dateValue != null) {
            dateResult = dateValue.year() + '-' + 
                (dateValue.month().format().length() == 1 ?  '0' + dateValue.month() : dateValue.month().format()) + '-' +
                (dateValue.day().format().length() == 1 ?  '0' + dateValue.day() : dateValue.day().format());
        }
        return dateResult;
    }

	/*
	 * @author Jérémy LAMBERT
	 * @date 04/12/2018 (dd/mm/yyyy)
	 * @description : HTTP Call to Chronos to enable Wallet for the main stakeholder of the given record
	 * @params :
	 *      recordId : Account record Id
	 */
	public static void enableWallet(String recordId) {

		AuthChronos__mdt auth = null;
		AuthChronos__mdt[] authList = [SELECT audience__c,client_secret__c,client_id__c,grant_type__c,
										realm__c,scope__c,url_chronos_api__c
										FROM AuthChronos__mdt
										WHERE DeveloperName=:Label.ChronosEnvironement];
		if(!authList.isEmpty()) {
			auth = authList[0];
		} else {
			throw new AuraHandledException('No Chronos Auth found.');
		}

		StakeHolder__c sh = getMainStakeholder(recordId);

		String authToken = WS02_Chronos.getToken(auth);
		String cache = 'no-cache';
		String endpoint = auth.url_chronos_api__c + '/v1/wallet/users/activation';
		String body = generateBody(recordId, sh);
		
		String response = WS02_Chronos.sendJsonChronos(authToken, cache, endpoint, body);
		ChronosResponse data = (ChronosResponse) JSON.createParser(response).readValueAs(ChronosResponse.class);

		Account account = new Account(Id = recordId);
		account.ChronosId__c = String.valueOf(data.company.id);
		update account;

		sh.Contact__r.ChronosId__c = String.valueOf(data.user.id);
		update sh.Contact__r;
	}

}