force-app/main/default/objects/Account/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OrigineWebsite__c.field-meta.xml
<CustomField>
    <fullName>OrigineWebsite__c</fullName>
    <label>Site d&#39;origine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Ocompta</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>LEC</fullName>
            </value>
            <value>
                <fullName>Sesame</fullName>
            </value>
            <value>
                <fullName>Start.fr</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>LNEC</fullName>
                <label>Le Net Expert Comptable</label>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Ola-compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Partenaire)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/associate__c/associate__c.object-meta.xml
<CustomObject>
    <description>Associé d&#39;un projet de création de société</description>
    <label>Associé</label>
    <nameField>
        <label>Nom de l&#39;associé ou Dénomination sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/associate__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Prénom de l&#39;associé</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Projet de création</label>
    <referenceTo>Start__c</referenceTo>
    <relationshipLabel>Associés</relationshipLabel>
    <relationshipName>Associate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/associate__c.field-meta.xml
<CustomField>
    <fullName>associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associé (tech)</label>
    <referenceTo>associate__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/enquetedeSatisfaction__c.object-meta.xml
<CustomObject>
    <label>Enquête de Satisfaction</label>
    <nameField>
        <displayFormat>SATISF-{0000}</displayFormat>
        <label>Enquête de Satisfaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquêtes de Satisfaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <formula>TEXT( Lead__r.Branding__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branding</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Cabinet</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquêtes de Satisfaction</relationshipLabel>
    <relationshipName>enquetesdeSatisfaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/OrigineWebsite__c.field-meta.xml
<CustomField>
    <fullName>OrigineWebsite__c</fullName>
    <formula>TEXT( Lead__r.OrigineWebsite__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site d&#39;origine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquêtes de Satisfaction</relationshipLabel>
    <relationshipName>SatisfactionSurvey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <description>Signatures des sms et mail</description>
    <inlineHelpText>Signatures des sms et mails</inlineHelpText>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/OrigineWebsite__c.field-meta.xml
<CustomField>
    <fullName>OrigineWebsite__c</fullName>
    <label>Branding d&#39;entrée</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
                <label>Trouver mon comptable.com</label>
            </value>
            <value>
                <fullName>LEC</fullName>
                <label>L&#39;Expert-Comptable.com</label>
            </value>
            <value>
                <fullName>Sesame</fullName>
            </value>
            <value>
                <fullName>Start.fr</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola-compta</fullName>
            </value>
            <value>
                <fullName>LNEC</fullName>
                <label>Le Net Expert Comptable</label>
            </value>
            <value>
                <fullName>LEC Lille</fullName>
                <label>L-Expert-Comptable Lille</label>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxicompta</fullName>
            </value>
            <value>
                <fullName>Progressive</fullName>
                <label>Progressive / Novaa</label>
            </value>
            <value>
                <fullName>Companeo</fullName>
            </value>
            <value>
                <fullName>Qonto</fullName>
            </value>
            <value>
                <fullName>TiimeAE</fullName>
            </value>
            <value>
                <fullName>Blog du dirigeant</fullName>
            </value>
            <value>
                <fullName>Ocompta</fullName>
                <isActive>false</isActive>
                <label>Ocompta</label>
            </value>
            <value>
                <fullName>Queexi</fullName>
                <isActive>false</isActive>
                <label>Queexi</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Nom du Stakeholder</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stakeholder__c/fields/ActualBeneficiary__c.field-meta.xml
<CustomField>
    <fullName>ActualBeneficiary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>se coche automatiquement si + de 25% des part dans son entreprise</description>
    <label>Bénéficiaire effectif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Associate__c.field-meta.xml
<CustomField>
    <fullName>Associate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Associé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stakeholders</relationshipLabel>
    <relationshipName>Parties_Prenantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne Physique</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Parties_PrenantesPP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/MainStakeholder__c.field-meta.xml
<CustomField>
    <fullName>MainStakeholder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permet d&#39;identifier le Stakeholder propriétaire du Wallet</description>
    <label>Stakeholder Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Officer__c.field-meta.xml
<CustomField>
    <fullName>Officer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandataire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <label>Dénomination Sociale</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/Crea__c.field-meta.xml
<CustomField>
    <fullName>Crea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L-Expert-Comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Tiime</fullName>
    </customValue>
    <customValue>
        <fullName>Trouver-mon-comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Novaa</fullName>
    </customValue>
    <customValue>
        <fullName>Incityz</fullName>
    </customValue>
    <customValue>
        <fullName>Condillac</fullName>
    </customValue>
    <customValue>
        <fullName>Goneo</fullName>
    </customValue>
    <customValue>
        <fullName>Ola Compta</fullName>
    </customValue>
    <customValue>
        <fullName>Le Net Expert Comptable</fullName>
    </customValue>
    <customValue>
        <fullName>Onlicorn</fullName>
    </customValue>
    <customValue>
        <fullName>Pepit</fullName>
    </customValue>
    <customValue>
        <fullName>L-Expert-Comptable Lille</fullName>
    </customValue>
    <customValue>
        <fullName>Evocompta</fullName>
    </customValue>
    <customValue>
        <fullName>Auficom</fullName>
    </customValue>
    <customValue>
        <fullName>Proxi Compta</fullName>
    </customValue>
    <description>liste des marques</description>
    <masterLabel>Marques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP04_Factory.cls
/*******************************************************
Nom ......... : AP04_Factory.cls
Description	  : Classe Factory pour la création d'instances pour les TEST
            
Auteur ...... : JEAN-BAPTISTE Félix 
********************************************************/
public class AP04_Factory {
	
	public static void createGenericDataSample() {
		// Create Accounts
		// Create a partner account
		List<Account> partnerAccounts = partnerAccountsFactory(2);
		partnerAccounts.get(1).Name = Constants.LEAD_BRANDING_TIIME;
		insert partnerAccounts;
		
		// Create Client Accounts
		List<Account> clientAccounts = clientAccountsFactory(1);
		insert clientAccounts;
		
		
		// Create Contacts
		// Create partner contacts
		List<Contact> partnerContacts = partnerContactsFactory(3, partnerAccounts.get(0).Id);
		partnerContacts.addAll(partnerContactsFactory(1, partnerAccounts.get(1).Id));
		insert partnerContacts;
		
		// Create client contact
		List<Contact> clientContacts = clientContactsFactory(1, clientAccounts.get(0).Id);
		insert clientContacts;
		
		// Create Leads
		// Create leads from a web site
		List<Lead> webLeads = newWebLeadsFactory(4);
		insert webLeads;
		
	}
	
	

	// Leads
	
	public static List<Lead> newWebLeadsFactory(Integer nbLeads) {
		String origineWebsite = Lead.OrigineWebsite__c.getDescribe().getPicklistValues().get(0).getValue();
		String branding = Lead.Branding__c.getDescribe().getPicklistValues().get(0).getValue();
		List<Lead> leads = new List<Lead>();
		for(Integer i = 1; i <= nbLeads; i++) {
			leads.add(leadFactory(origineWebsite, chooseSalutation(i), 'firstname', 'lastname'+i, 'lead'+i+'@tiime.fr', '0612345789', 'firstname lastname'+i, branding));
		}
		return leads;
	}
	
	public static Lead leadFactory(String origineWebsite, String salutation, String fName, String lName, String email, String mobilePhone, String company, String branding) {
		return new Lead(OrigineWebsite__c = origineWebsite, Salutation = salutation, FirstName = fName, LastName = lName, Email = email, MobilePhone = mobilePhone, Company = company, Branding__c = branding);
	}
	
    public static List<Lead> LeadFactory(Integer nbLeads, String phone, String lName, String corp){
        List<Lead> leads = new list<Lead>();
        for(Integer i=1; i<=nbLeads; i++){
            leads.add(new Lead(MobilePhone=phone, LastName=lName+i, Company=corp));
        }
        return leads;
     }

	// Users
     public static List<User> UserStandardFactory(Integer nbUser, String lName,String fName , String userN){

     	Profile standardProfile = [Select id from Profile where Name =: 'Utilisateur standard' or Name =: 'Standard User' limit 1];
        List<User> users = new list<User>();
        for(Integer i=1; i<=nbUser; i++){
            users.add(new User(
            	LastName = lName+i,
                FirstName = fName+i,
                Alias = lName.substring(0,2)+fName.substring(0,2),
                Email = userN,
                Username = userN,
                ProfileId = standardProfile.Id,
                TimeZoneSidKey = 'Europe/Paris',
                LanguageLocaleKey = 'fr',
                EmailEncodingKey = 'UTF-8',
                LocaleSidKey = 'fr'
            ));
        }
        return users;
     }
     
     public static List<User> userSpecificProfileFactory(Integer nbUser, String lName,String fName , String userN, String profileName){

     	Profile profile = [Select id from Profile where Name =:profileName limit 1];
        List<User> users = new list<User>();
        for(Integer i=1; i<=nbUser; i++){
            users.add(new User(
            	LastName = lName+i,
                FirstName = fName+i,
                Alias = lName.substring(0,2)+fName.substring(0,2),
                Email = userN,
                Username = userN,
                ProfileId = profile.Id,
                TimeZoneSidKey = 'Europe/Paris',
                LanguageLocaleKey = 'fr',
                EmailEncodingKey = 'UTF-8',
                LocaleSidKey = 'fr'
            ));
        }
        return users;
     }

     public static List<User> UserAdminFactory(Integer nbUser, String lName,String fName , String userN){

     	Profile adminProfile = [Select id from Profile where Name = 'Administrateur système' or Name = 'System Administrator' limit 1];
        List<User> users = new list<User>();
        for(Integer i=1; i<=nbUser; i++){
            users.add(new User(
                LastName = lName+i,
                FirstName = fName+i,
                Alias = lName.substring(0,2)+fName.substring(0,2),
                Email = userN,
                Username = userN,
                ProfileId = adminProfile.Id,
                TimeZoneSidKey = 'Europe/Paris',
                LanguageLocaleKey = 'fr',
                EmailEncodingKey = 'UTF-8',
                LocaleSidKey = 'fr'
            ));
        }
        return users;
     }
     
     // Accounts
     public static List<Account> partnerAccountsFactory(Integer nbAccount) {
     	List<Account> accounts = new List<Account>();
     	Id recordTypeId = Utils.getAccountRecordTypeByDeveloperName(Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_PARTNER);
     	for(Integer i = 1; i <= nbAccount; i++) {
     		accounts.add(accountFactory('PartnerAccountN'+i, recordTypeId));
     	}
     	return accounts;
     }
     
     public static List<Account> clientAccountsFactory(Integer nbAccount) {
     	List<Account> accounts = new List<Account>();
     	Id recordTypeId = Utils.getAccountRecordTypeByDeveloperName(Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_CLIENT);
     	for(Integer i = 1; i <= nbAccount; i++) {
     		accounts.add(accountFactory('ClientAccountN'+i, recordTypeId));
     	}
     	return accounts;
     }
     
     public static Account accountFactory(String name, Id recordTypeId) {
     	return new Account(Name = name, RecordTypeId = recordTypeId);
     }
     
     // Contacts
     public static List<Contact> partnerContactsFactory(Integer nbContacts, Id entrepriseId) {
     	List<Contact> contacts = new List<Contact>();
     	
     	for(Integer i = 1; i <= nbContacts; i++) {
     		contacts.add(contactFactory(
     		chooseSalutation(i), 'partnerFirstname', 'partnerLastname'+i, 'partnerContact'+i+'@tiime.fr', entrepriseId, Utils.getContactRecordTypeIdByDeveloperName(Constants.CONTACT_RECORDTYPE_DEVELOPERNAME_PARTNER)
     		));
     	}
     	return contacts;
     }
     
     public static List<Contact> clientContactsFactory(Integer nbContacts, Id entrepriseId) {
     	List<Contact> contacts = new List<Contact>();
     	
     	for(Integer i = 1; i <= nbContacts; i++) {
     		contacts.add(contactFactory(
     		chooseSalutation(i), 'clientFirstname', 'clientLastname'+i, 'clientContact'+i+'@tiime.fr', entrepriseId, Utils.getContactRecordTypeIdByDeveloperName(Constants.CONTACT_RECORDTYPE_DEVELOPERNAME_CLIENT)
     		));
     	}
     	return contacts;
     }
     
     public static Contact contactFactory(String salutation, string fName, String lName, String email, Id entrepriseId, Id recordtypeId) {
     	return new Contact(Salutation = salutation, FirstName = fName, LastName = lName, Email = email, AccountId = entrepriseId, RecordTypeId = recordtypeId);
     }
     
     private static String chooseSalutation(Integer i) {
     	return Contact.Salutation.getDescribe().getPicklistValues().get(Math.mod(i, 2)).getValue();
     }
     
     //Stakeholder
	public static List<Account> generateStakeholderTestCases() {
		List<Account> companies = new List<Account>();
		List<Contact> contacts = new List<Contact>();
		List<Stakeholder__c> stakeholders = new List<Stakeholder__c>();
		Id recordTypeId = Utils.getAccountRecordTypeByDeveloperName(Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_PARTNER);

		companies.add(accountFactory('NO_SH', recordTypeId));
		companies.add(accountFactory('ONE_SH', recordTypeId));
		companies.add(accountFactory('MULTIPLE_PRIMARY_SH_NO_BENEFICIARY', recordTypeId));
		companies.add(accountFactory('SINGLE_PRIMARY_SH_NO_BENEFICAIRY', recordTypeId));
		companies.add(accountFactory('MULTIPLE_PRIMARY_SH', recordTypeId));
		companies.add(accountFactory('SINGLE_PRIMARY_SH', recordTypeId));

		insert companies;
		
		for(Account a : companies) {
			contacts.add(contactFactory('madame', 'TestContact', 'Test', 'Test@test.com', a.Id, Utils.getContactRecordTypeIdByDeveloperName(Constants.CONTACT_RECORDTYPE_DEVELOPERNAME_CLIENT)));
		}
		insert contacts;

		stakeholders.add(stakeholderFactory(false, false, false, companies[1].Id, contacts[1].Id));

		stakeholders.add(stakeholderFactory(false, false, true, companies[2].Id, contacts[2].Id));
		stakeholders.add(stakeholderFactory(false, false, true, companies[2].Id, contacts[2].Id));

		stakeholders.add(stakeholderFactory(false, false, true, companies[3].Id, contacts[3].Id));
		stakeholders.add(stakeholderFactory(false, false, false, companies[3].Id, contacts[3].Id));

		stakeholders.add(stakeholderFactory(false, true, true, companies[4].Id, contacts[4].Id));
		stakeholders.add(stakeholderFactory(true, false, true, companies[4].Id, contacts[4].Id));

		stakeholders.add(stakeholderFactory(true, false, true, companies[5].Id, contacts[5].Id));
		stakeholders.add(stakeholderFactory(true, false, false, companies[5].Id, contacts[5].Id));
		stakeholders.add(stakeholderFactory(true, true, false, companies[5].Id, contacts[5].Id));
		stakeholders.add(stakeholderFactory(false, true, false, companies[5].Id, contacts[5].Id));

		insert stakeholders;
		return companies;
	}

	public static Stakeholder__c stakeholderFactory(Boolean actualBeneficiary, Boolean officer, Boolean mainStakeHolder, Id company, Id contact) {
		return new Stakeholder__c(ActualBeneficiary__c = actualBeneficiary, Officer__c = officer, MainStakeholder__c = mainStakeHolder, Company__c = company, Contact__c = contact);
	}

	//Associate__c
	public static List<Associate__c> associatesFactory(Integer count, Id startId) {
		List<Associate__c> partners = new List<Associate__c>();

		for(Integer i = 0 ; i < count ; i++) {
			partners.add(associateFactory('Associate ' + i, startId));
		}
		return partners;
	}

	public static Associate__c associateFactory(String firstName, Id startId) {
		return new Associate__c(FirstName__c = firstName, Start__c = startId);
	}

	//Start
	public static Start__c startFactory(String companyName, Id leadId) {
		return new Start__c(CompanyName__c = companyName, Crea__c = leadId);
	}
	
	//Enquête de Satisfaction
	public static enquetedeSatisfaction__c createEnqueteSatisfaction(Id accountID, Id leadId){
		Id recordTypeId = Utils.getEnqueteRecordTypeByDeveloperName(Constants.ENQUETE_RECORDTYPE_DEVELOPERNAME_J10);
		enquetedeSatisfaction__c enquete = new enquetedeSatisfaction__c(RecordTypeId=recordTypeId, Partner__c=accountID, Lead__c=leadId);
		return enquete;
	}
	public static List<enquetedeSatisfaction__c> enqueteFactory(Integer nbEnquetes, Id accountID, Id leadId){
		List<enquetedeSatisfaction__c> enquetes = new List<enquetedeSatisfaction__c>();

		for(Integer i = 0 ; i < nbEnquetes ; i++) {
			enquetes.add(createEnqueteSatisfaction(accountID,leadId));
		}
		return enquetes;
	}

 }