force-app/main/default/objects/Account/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Etage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RDC</fullName>
            </value>
            <value>
                <fullName>1er</fullName>
            </value>
            <value>
                <fullName>2ème</fullName>
            </value>
            <value>
                <fullName>3ème</fullName>
            </value>
            <value>
                <fullName>4ème</fullName>
            </value>
            <value>
                <fullName>5ème</fullName>
            </value>
            <value>
                <fullName>6ème</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <description>Signatures des sms et mail</description>
    <inlineHelpText>Signatures des sms et mails</inlineHelpText>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Le compte partenaire doit être de type &#39;EC Partenaire&#39;. Pour les Partenariat, seuls les cabinets groupes sont valides.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>EC Partenaire</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partenariat</value>
        </filterItems>
        <filterItems>
            <field>$Source.PartnerType__c</field>
            <operation>equals</operation>
            <value>Groupe</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partenaire)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/Crea__c.field-meta.xml
<CustomField>
    <fullName>Crea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/Transfert__c.object-meta.xml
<CustomObject>
    <label>Transfert</label>
    <nameField>
        <label>Nom de Transfert Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transferts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfert__c/fields/AppointmentType__c.field-meta.xml
<CustomField>
    <fullName>AppointmentType__c</fullName>
    <label>Type de Rendez-vous</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Téléphonique</fullName>
            </value>
            <value>
                <fullName>Au bureau</fullName>
            </value>
            <value>
                <fullName>Chez le client</fullName>
            </value>
            <value>
                <fullName>Transfert direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/ContactPartenaire__c.field-meta.xml
<CustomField>
    <fullName>ContactPartenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Partenaire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L-Expert-Comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Tiime</fullName>
    </customValue>
    <customValue>
        <fullName>Trouver-mon-comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Novaa</fullName>
    </customValue>
    <customValue>
        <fullName>Incityz</fullName>
    </customValue>
    <customValue>
        <fullName>Condillac</fullName>
    </customValue>
    <customValue>
        <fullName>Goneo</fullName>
    </customValue>
    <customValue>
        <fullName>Ola Compta</fullName>
    </customValue>
    <customValue>
        <fullName>Le Net Expert Comptable</fullName>
    </customValue>
    <customValue>
        <fullName>Onlicorn</fullName>
    </customValue>
    <customValue>
        <fullName>Pepit</fullName>
    </customValue>
    <customValue>
        <fullName>L-Expert-Comptable Lille</fullName>
    </customValue>
    <customValue>
        <fullName>Evocompta</fullName>
    </customValue>
    <customValue>
        <fullName>Auficom</fullName>
    </customValue>
    <customValue>
        <fullName>Proxi Compta</fullName>
    </customValue>
    <description>liste des marques</description>
    <masterLabel>Marques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Batch_Confirmation_SMS.cls
public class Batch_Confirmation_SMS implements queueable, Database.AllowsCallouts {

	public static void execute(System.QueueableContext queueableContext) {
		// Retrieve events with specificities
		// specificities : Event related to a start__c record, Event with StartDateTime Tomorrow, Event with Confirmation SMS Send checkbox unchecked
		// LIMIT 50
		DateTime todayDateTime = DateTime.now();
		DateTime tomorrowDateTime = DateTime.now().addDays(1);
		DateTime nextFourHours = DateTime.now().addHours(4);
		DateTime nextTwentyThreeHours = DateTime.now().addHours(23);
		List<Event> rawEvents = [SELECT Id, WhatId, WhoId, StartDateTime, OwnerId, Owner.FirstName, Owner.LastName, ConfirmationSmsSend__c FROM Event WHERE StartDateTime < :tomorrowDateTime AND StartDateTime > :todayDateTime AND (StartDateTime > :nextTwentyThreeHours OR StartDateTime < :nextFourHours) AND ConfirmationSmsSend__c = false LIMIT 50];
		
		// Filter records depending on the WhatId Related Object Type, We want Start__c or Transfert__c objects right now. 
		// These two types are treated separatly.
		List<Event> startEvents = new List<Event>();
		List<Event> transfertEvents = new List<Event>();
		Set<String> whatIdSet = new Set<String>();
		String tempWhatId;
		for(Event e : rawEvents) {
			tempWhatId = e.WhatId;
			if(tempWhatId != null) {
				if(tempWhatId.startsWith(Constants.START_OBJECT_PREFIX_ID)) {
					startEvents.add(e);
					whatIdSet.add(e.WhatId);
				} else if(tempWhatId.startsWith(Constants.TRANSFERT_OBJECT_PREFIX_ID)) {
					transfertEvents.add(e);
					whatIdSet.add(e.WhatId);
				}
			}
		}
		
		List<Event> eventsToUpdate = handleStartEvents(startEvents, whatIdSet);
		eventsToUpdate.addAll(handleTransfertEvents(transfertEvents, whatIdSet));
		
		if(!eventsToUpdate.isEmpty()) {
			update eventsToUpdate;
		}
		
		if(!Test.isRunningTest()) {
			System.enqueueJob(new Batch_Confirmation_SMS());
		}
	}
	
	private static List<Event> handleStartEvents(List<Event> startEvents, Set<String> whatIdSet) {
		// Retrieve LeadIds and Data such as Phone numbers
		Map<Id, Start__c> startMap = new Map<Id, Start__c>([SELECT Id, Crea__c, Crea__r.MobilePhone FROM Start__c WHERE Id IN :whatIdSet]);
		
		List<Event> eventsToUpdate = new List<Event>();
		for(Event e : startEvents) {
			if(startMap.containsKey(e.WhatId)) {
				Utils_CustomEmailTemplateDesigner smsDesigner = new Utils_CustomEmailTemplateDesigner(
					new Lead(Id = startMap.get(e.WhatId).Crea__c), 
					new User(Id = e.OwnerId, FirstName = e.Owner.FirstName, LastName = e.Owner.LastName), 
					e,
					null,
					null,
					Constants.EVENT_CREA_TIIME_CONFIRMATION_SMS_CONTENT
				);
				
				if(SMS.sendSMS(startMap.get(e.WhatId).Crea__r.MobilePhone, smsDesigner.formatLeadEmailTemplate(), startMap.get(e.WhatId).Crea__c, false)) {
					e.ConfirmationSmsSend__c = true;
					eventsToUpdate.add(e);
				}
			}
		}
		
		return eventsToUpdate;
	}
	
	private static List<Event> handleTransfertEvents(List<Event> transfertEvents, Set<String> whatIdSet) {
		// Retrieve LeadIds and Data such as Phone numbers
		Map<Id, Transfert__c> transfertMap = new Map<Id, Transfert__c>([SELECT Id, AppointmentType__c, Lead__c, Lead__r.FirstName, Lead__r.MobilePhone, Lead__r.Branding__c,  Partenaire__c, Partenaire__r.BillingStreet, Partenaire__r.BillingCity, Partenaire__r.BillingPostalCode, Partenaire__r.BillingCountry, Partenaire__r.Floor__c, ContactPartenaire__c, ContactPartenaire__r.MobilePhone FROM Transfert__c WHERE Id IN :whatIdSet]);
		
		List<Event> eventsToUpdate = new List<Event>();
		for(Event e : transfertEvents) {
			if(transfertMap.containsKey(e.WhatId)) {
				Utils_CustomEmailTemplateDesigner smsDesigner = new Utils_CustomEmailTemplateDesigner(
					new Lead(
						Id = transfertMap.get(e.WhatId).Lead__c, 
						FirstName = transfertMap.get(e.WhatId).Lead__r.FirstName,
						Branding__c = transfertMap.get(e.WhatId).Lead__r.Branding__c
					), 
					new User(
						Id = e.OwnerId, 
						FirstName = e.Owner.FirstName, 
						LastName = e.Owner.LastName
					), 
					e, 
					new Account(
						BillingStreet = transfertMap.get(e.WhatId).Partenaire__r.BillingStreet,
						BillingCity = transfertMap.get(e.WhatId).Partenaire__r.BillingCity,
						BillingPostalCode = transfertMap.get(e.WhatId).Partenaire__r.BillingPostalCode,
						BillingCountry = transfertMap.get(e.WhatId).Partenaire__r.BillingCountry,
						Floor__c = transfertMap.get(e.WhatId).Partenaire__r.Floor__c
					),
					new Contact(MobilePhone = transfertMap.get(e.WhatId).ContactPartenaire__r.MobilePhone),
					(transfertMap.get(e.WhatId).AppointmentType__c == Constants.LEAD_RDV_TYPE_TELEPHONIQUE ? Constants.EVENT_CAB_ONLINE_CONFIRMATION_SMS_CONTENT : Constants.EVENT_CAB_TIIME_CONFIRMATION_SMS_CONTENT)
				);
				
				if(SMS.sendSMS(transfertMap.get(e.WhatId).Lead__r.MobilePhone, smsDesigner.formatLeadEmailTemplate(), transfertMap.get(e.WhatId).Lead__c, false)) {
					e.ConfirmationSmsSend__c = true;
					eventsToUpdate.add(e);
				}
			}
		}
		
		return eventsToUpdate;
	}
	
}