force-app/main/default/objects/Account/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/associate__c/associate__c.object-meta.xml
<CustomObject>
    <description>Associé d&#39;un projet de création de société</description>
    <label>Associé</label>
    <nameField>
        <label>Nom de l&#39;associé ou Dénomination sociale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/associate__c/fields/CashShareCapital__c.field-meta.xml
<CustomField>
    <fullName>CashShareCapital__c</fullName>
    <label>Apport en numéraire</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Ville</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Prénom de l&#39;associé</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/KindShareCapital__c.field-meta.xml
<CustomField>
    <fullName>KindShareCapital__c</fullName>
    <inlineHelpText>Joindre la liste détaillée</inlineHelpText>
    <label>Apport en nature</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Associés</relationshipLabel>
    <relationshipName>AssociatesOpp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/associate__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Projet de création</label>
    <referenceTo>Start__c</referenceTo>
    <relationshipLabel>Associés</relationshipLabel>
    <relationshipName>Associate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/associate__c.field-meta.xml
<CustomField>
    <fullName>associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associé (tech)</label>
    <referenceTo>associate__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <description>Signatures des sms et mail</description>
    <inlineHelpText>Signatures des sms et mails</inlineHelpText>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L-Expert-Comptable.com</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>Trouver-mon-comptable.com</fullName>
            </value>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola Compta</fullName>
            </value>
            <value>
                <fullName>Le Net Expert Comptable</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>L-Expert-Comptable Lille</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxi Compta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LeadFullName__c.field-meta.xml
<CustomField>
    <fullName>LeadFullName__c</fullName>
    <label>Nom de la Lead</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/Crea__c.field-meta.xml
<CustomField>
    <fullName>Crea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>StartsOpp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L-Expert-Comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Tiime</fullName>
    </customValue>
    <customValue>
        <fullName>Trouver-mon-comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Novaa</fullName>
    </customValue>
    <customValue>
        <fullName>Incityz</fullName>
    </customValue>
    <customValue>
        <fullName>Condillac</fullName>
    </customValue>
    <customValue>
        <fullName>Goneo</fullName>
    </customValue>
    <customValue>
        <fullName>Ola Compta</fullName>
    </customValue>
    <customValue>
        <fullName>Le Net Expert Comptable</fullName>
    </customValue>
    <customValue>
        <fullName>Onlicorn</fullName>
    </customValue>
    <customValue>
        <fullName>Pepit</fullName>
    </customValue>
    <customValue>
        <fullName>L-Expert-Comptable Lille</fullName>
    </customValue>
    <customValue>
        <fullName>Evocompta</fullName>
    </customValue>
    <customValue>
        <fullName>Auficom</fullName>
    </customValue>
    <customValue>
        <fullName>Proxi Compta</fullName>
    </customValue>
    <description>liste des marques</description>
    <masterLabel>Marques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IcxConvertProjectTest.cls
@isTest
class IcxConvertProjectTest {
    
    Public Static Lead lead;
    Public Static Account acc;
    Public Static Contact ctc;
    Public Static Opportunity opp;
    Public Static Start__c project;
    Public Static Start__c project2;
    Public Static Associate__c associate;
    Public Static Associate__c associate2;
    
    Static {
        lead = new Lead( Company = 'test acme', email='test@acme.com', MobilePhone = '0607080910', firstName = 'leadName', LastName='leadLastName', Branding__c = 'Novaa');
        Insert lead;
        
        project = new Start__c( Crea__c = lead.Id);
        Insert project;
        
        associate = new Associate__c( firstName__c = 'leadName',  Start__c = project.Id, lead__c = lead.Id, KindShareCapital__c = 500, CashShareCapital__c= 100, City__c = 'Paris');
        Insert associate;
        
        acc = new Account(Name='test cie');
        insert acc;
        
        ctc = new contact(accountId = acc.Id, lastName='Lname', firstName='fname', email='email@gee.com');
        insert ctc;
        
        opp = new Opportunity(Name='test opp', accountId=acc.id, amount=100, closeDate= date.today()+1, stageName=Opportunity.stagename.getDescribe().getPicklistValues()[0].getValue(), LeadFullName__c = lead.FirstName + ' ' + lead.LastName);
        insert opp;
        
        project2 = new Start__c( Opportunity__c  = opp.Id, Crea__c = lead.Id);
        Insert project2;
        
        associate2 = new Associate__c( name= 'Lname', firstName__c = 'fname',  Start__c = project2.Id, Opportunity__c = opp.Id, KindShareCapital__c = 500, CashShareCapital__c= 100, City__c = 'Paris');
        Insert associate2;
    }
    
    static testmethod void convertProject() {
        test.StartTest();
        IcxConvertProject.RequestConversion[] reqs = new IcxConvertProject.RequestConversion[]{};
        IcxConvertProject.RequestConversion reqLead = new IcxConvertProject.RequestConversion();
        reqLead.itemId = lead.Id;        
        reqs.add( reqLead );
            
		IcxConvertProject.convertProject( reqs );        
        test.StopTest();
    }

    static testmethod void convertProject2() {
        test.StartTest();
        IcxConvertProject.RequestConversion[] reqs = new IcxConvertProject.RequestConversion[]{};
        IcxConvertProject.RequestConversion req = new IcxConvertProject.RequestConversion();
        req.itemId = opp.Id;
        reqs.add( req );
            
		IcxConvertProject.convertProject( reqs );      
        test.StopTest();
    }
    
    
}