force-app/main/default/objects/Account/fields/DateKbisReceive__c.field-meta.xml
<CustomField>
    <fullName>DateKbisReceive__c</fullName>
    <label>Date Kbis reçu</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/KbisReceive__c.field-meta.xml
<CustomField>
    <fullName>KbisReceive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kbis reçu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberBGI__c.field-meta.xml
<CustomField>
    <fullName>NumberBGI__c</fullName>
    <description>Le numéro de dossier enregistré dans la BaseGI. Ce numéro doit être unique.</description>
    <externalId>true</externalId>
    <label>Numéro Dossier BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/KbisReceive__c.field-meta.xml
<CustomField>
    <fullName>KbisReceive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kbis Tiime recu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/KbisReceptionDate__c.field-meta.xml
<CustomField>
    <fullName>KbisReceptionDate__c</fullName>
    <label>Date de réception KBIS</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroCompteBaseGI__c.field-meta.xml
<CustomField>
    <fullName>NumeroCompteBaseGI__c</fullName>
    <description>l&#39;identifiant BaseGI du compte créé à partir de la Lead</description>
    <label>Numero Compte BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/Crea__c.field-meta.xml
<CustomField>
    <fullName>Crea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/ProjectStatus__c.field-meta.xml
<CustomField>
    <fullName>ProjectStatus__c</fullName>
    <label>Statut du projet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call conseil</fullName>
                <default>true</default>
                <label>Call conseil</label>
            </value>
            <value>
                <fullName>Prise d&#39;informations</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Kbis reçu</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
            <value>
                <fullName>Confirmation d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>Confirmation d&#39;informations</label>
            </value>
            <value>
                <fullName>Prise de connaissance</fullName>
                <isActive>false</isActive>
                <label>Prise de connaissance</label>
            </value>
            <value>
                <fullName>Stand-by</fullName>
                <isActive>false</isActive>
                <label>Stand-by</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WS08_FinalKbisReceived.cls
@RestResource(urlMapping='/bgi/v1/finalKbisReceived/*')
global without sharing class WS08_FinalKbisReceived {

	@HttpPost
    global static String newKbisReceived() {
    	String errorMessage = null;
    	RestRequest req = RestContext.request;
    	System.debug(req);
    	try {
	    	Blob blobBody = req.requestBody;
	    	System.debug(blobBody);
	    	WS08_FinalKbisReceived.KbisInfoDTO kbis = (WS08_FinalKbisReceived.KbisInfoDTO) JSON.deserializeStrict( req.requestBody.toString(), KbisInfoDTO.class);
	    	manageKbisReception(kbis);
    	} catch(Exception e) {
    		System.debug(e);
    		errorMessage = e.getMessage();
       	}
       	
    	return errorMessage == null ? 'OK': errorMessage;
    }
	
	@TestVisible
    private static void manageKbisReception(KbisInfoDTO kbis) {
    	if(kbis != null) {
    		// On recherche une lead non convertie (encore modifiable) corespondant à ce numéro de dossier.
    		List<Lead> leads = [SELECT Id, KbisReceive__c, KbisReceptionDate__c, NumeroCompteBaseGI__c FROM Lead WHERE NumeroCompteBaseGI__c = :kbis.numeroDossier AND IsConverted = false AND KbisReceive__c = false];
    		if(!leads.isEmpty()) {
    			Lead leadToUpdate = leads.get(0);
    			leadToUpdate.KbisReceive__c = true;
    			leadToUpdate.KbisReceptionDate__c = kbis.receivedKbisDate;
    			update leadToUpdate;
    			
    			// Le projet de création peut être passé au statut Kbis reçu
    			changeStartStatus(leadToUpdate.NumeroCompteBaseGI__c.intValue());
    		} else {
    			// Si aucune lead n'a été trouvée, cela peut signifier qu'elle a été convertie. On cherche donc un compte ayant le même numéro de dossier.
    			List<Account> accounts = [SELECT Id, KbisReceive__c, DateKbisReceive__c, NumberBGI__c FROM Account WHERE NumberBGI__c = :kbis.numeroDossier AND KbisReceive__c = false];
    			if(!accounts.isEmpty()) {
    				Account accountToUpdate = accounts.get(0);
    				accountToUpdate.KbisReceive__c = true;
    				accountToUpdate.DateKbisReceive__c = kbis.receivedKbisDate;
    				update accountToUpdate;
    				
    				// Le projet de création peut être passé au statut Kbis reçu
    				changeStartStatus(accountToUpdate.NumberBGI__c.intValue());
    			} else {
    				throw new WS08_Exception('Aucun compte ou lead trouvé dans Salesforce avec l\'identifiant ' + kbis.numeroDossier +'.');
    			}
    		}
    	} else {
    		throw new WS08_Exception('Impossible de lire le corps de la requête.');
    	}
    }
	
	private static void changeStartStatus(Integer numeroDossier) {
		List<Start__c> projetsCrea = [SELECT Id, ProjectStatus__c FROM Start__c WHERE  Crea__r.NumeroCompteBaseGI__c = :numeroDossier];
		if(!projetsCrea.isEmpty()) {
			projetsCrea.get(0).ProjectStatus__c = Constants.START_STATUS_KBIS;
			update projetsCrea.get(0);
		}
	}
	
	
	public class KbisInfoDTO {
    	private Integer numeroDossier;
    	private DateTime receivedKbisDate;
    	private Time receptionHour = Time.newInstance(9, 0, 0, 0);
    	
    	public KbisInfoDTO(Integer numeroDossier) {
    		this.numeroDossier = numeroDossier;
    	}
    	public KbisInfoDTO(Integer numeroDossier, Date receivedKbisDate) {
    		this.numeroDossier = numeroDossier;
    		this.receivedKbisDate = DateTime.newInstance(receivedKbisDate, this.receptionHour);
    	}
    	public KbisInfoDTO(Integer numeroDossier, String receivedKbisDate) {
    		this.numeroDossier = numeroDossier;
    		this.receivedKbisDate = DateTime.newInstance(Date.valueOf(receivedKbisDate), this.receptionHour);
    	}
    	
    }
	
	private class WS08_Exception extends Exception {}

}