force-app/main/default/objects/Account/fields/DateKbisReceive__c.field-meta.xml
<CustomField>
    <fullName>DateKbisReceive__c</fullName>
    <label>Date Kbis reçu</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/KbisReceive__c.field-meta.xml
<CustomField>
    <fullName>KbisReceive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kbis reçu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberBGI__c.field-meta.xml
<CustomField>
    <fullName>NumberBGI__c</fullName>
    <description>Le numéro de dossier enregistré dans la BaseGI. Ce numéro doit être unique.</description>
    <externalId>true</externalId>
    <label>Numéro Dossier BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Contact_Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Partenaire</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Il est indispensable de choisir un contact du Cabinet Partenaire</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Partenaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contact Partenaire)</relationshipLabel>
    <relationshipName>LeadsContactPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/KbisReceive__c.field-meta.xml
<CustomField>
    <fullName>KbisReceive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kbis Tiime recu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/KbisReceptionDate__c.field-meta.xml
<CustomField>
    <fullName>KbisReceptionDate__c</fullName>
    <label>Date de réception KBIS</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NumeroCompteBaseGI__c.field-meta.xml
<CustomField>
    <fullName>NumeroCompteBaseGI__c</fullName>
    <description>l&#39;identifiant BaseGI du compte créé à partir de la Lead</description>
    <label>Numero Compte BaseGI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Le compte partenaire doit être de type &#39;EC Partenaire&#39;. Pour les Partenariat, seuls les cabinets groupes sont valides.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>EC Partenaire</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partenariat</value>
        </filterItems>
        <filterItems>
            <field>$Source.PartnerType__c</field>
            <operation>equals</operation>
            <value>Groupe</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partenaire)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WS08_FinalKbisReceived_TEST.cls
@isTest
public with sharing class WS08_FinalKbisReceived_TEST {
    private static final Integer NUMBER_DOSSIER_BGI = 99999;
    @testSetup
    static void setupData() {
    	AP04_Factory.createGenericDataSample();
    	
    	List<Lead> leads = [SELECT Id, NumeroCompteBaseGI__c, Partenaire__c, KbisReceive__c, KbisReceptionDate__c FROM Lead WHERE IsConverted = false];
    	System.assert(!leads.isEmpty());
    	System.assertEquals(false, leads.get(0).KbisReceive__c);
    	System.assertEquals(null, leads.get(0).KbisReceptionDate__c);
    	Account tiimeAccount;
    	List<Account> tiimeAccounts = [SELECT Id, (SELECT Id FROM Contacts) FROM Account WHERE Name = :Constants.LEAD_BRANDING_TIIME];
    	tiimeAccount = (tiimeAccounts.isEmpty() ? null : tiimeAccounts.get(0));
    	leads.get(0).NumeroCompteBaseGI__c = NUMBER_DOSSIER_BGI;
    	leads.get(0).Partenaire__c = tiimeAccount.Id;
    	leads.get(0).Contact_Partenaire__c = tiimeAccount.Contacts.get(0).Id;
    	update leads.get(0);
    }
    
    @isTest
    static void testSimpleLeadSignature() {
    	List<Lead> leads = [SELECT Id, NumeroCompteBaseGI__c, KbisReceive__c FROM Lead WHERE IsConverted = false];
    	Integer nbUnconvertedLeads = leads.size();
    	
    	List<Account> accounts = [SELECT Id FROM Account WHERE NumberBGI__c = :NUMBER_DOSSIER_BGI];
    	System.assert(accounts.isEmpty());
    	
    	WS08_FinalKbisReceived.KbisInfoDTO dto = new WS08_FinalKbisReceived.KbisInfoDTO(NUMBER_DOSSIER_BGI, Date.newInstance(2019, 07, 08));
    	
    	Test.startTest();
    	WS08_FinalKbisReceived.manageKbisReception(dto);
    	Test.stopTest();
    	
    	// On devrait avoir trouvé une lead et celle ci devrait avoir été mise à jour
    	Lead leadConverted = [SELECT Id, NumeroCompteBaseGI__c, KbisReceive__c, KbisReceptionDate__c FROM Lead WHERE Id = :leads.get(0).Id];
    	System.assertEquals(true, leadConverted.KbisReceive__c);
    	System.assertNotEquals(null, leadConverted.KbisReceptionDate__c);
    }
    
    @isTest
    static void testSimpleAccountSignature() {
    	List<Lead> leads = [SELECT Id FROM Lead WHERE NumeroCompteBaseGI__c = :NUMBER_DOSSIER_BGI];
    	System.assert(!leads.isEmpty());
    	
    	LeadConverterProcessAE converter = new LeadConverterProcessAE(leads.get(0).Id);
    	converter.launchLeadConversion();
    	
    	List<Account> accounts = [SELECT Id, KbisReceive__c, DateKbisReceive__c FROM Account WHERE NumberBGI__c = :NUMBER_DOSSIER_BGI];
    	System.assertEquals(1, accounts.size());
    	System.assertEquals(false, accounts.get(0).KbisReceive__c);
    	System.assertEquals(null, accounts.get(0).DateKbisReceive__c);
    	
    	WS08_FinalKbisReceived.KbisInfoDTO dto = new WS08_FinalKbisReceived.KbisInfoDTO(NUMBER_DOSSIER_BGI, '2019-07-08');
    	
    	Test.startTest();
    	WS08_FinalKbisReceived.manageKbisReception(dto);
    	Test.stopTest();
    	
    	// On devrait avoir la case cochée sur le compte.
    	accounts = [SELECT Id, KbisReceive__c, DateKbisReceive__c FROM Account WHERE NumberBGI__c = :NUMBER_DOSSIER_BGI];
    	System.assertEquals(true, accounts.get(0).KbisReceive__c);
    	System.assertNotEquals(null, accounts.get(0).DateKbisReceive__c);
    }
}