force-app/main/default/objects/Account/fields/ValidatedForAppWallet__c.field-meta.xml
<CustomField>
    <fullName>ValidatedForAppWallet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validée pour l’App Wallet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BirthPlace__c.field-meta.xml
<CustomField>
    <fullName>BirthPlace__c</fullName>
    <label>Ville de naissance</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IncomPerTranche__c.field-meta.xml
<CustomField>
    <fullName>IncomPerTranche__c</fullName>
    <label>Revenus par Tranche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 - 18 K€</fullName>
            </value>
            <value>
                <fullName>19 - 23 K€</fullName>
            </value>
            <value>
                <fullName>24 - 27K€</fullName>
            </value>
            <value>
                <fullName>28 - 35K€</fullName>
            </value>
            <value>
                <fullName>36 - 56K€</fullName>
            </value>
            <value>
                <fullName>57K€ ou plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationalité</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NativeCountry__c.field-meta.xml
<CustomField>
    <fullName>NativeCountry__c</fullName>
    <label>Pays de naissance</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Networth__c.field-meta.xml
<CustomField>
    <fullName>Networth__c</fullName>
    <label>Patrimoine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 - 2K€</fullName>
            </value>
            <value>
                <fullName>3 - 22K€</fullName>
            </value>
            <value>
                <fullName>23 - 128K€</fullName>
            </value>
            <value>
                <fullName>129 - 319K€</fullName>
            </value>
            <value>
                <fullName>420 - 464K€</fullName>
            </value>
            <value>
                <fullName>465K€ et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Nom du Stakeholder</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stakeholder__c/fields/ActualBeneficiary__c.field-meta.xml
<CustomField>
    <fullName>ActualBeneficiary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>se coche automatiquement si + de 25% des part dans son entreprise</description>
    <label>Bénéficiaire effectif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stakeholders</relationshipLabel>
    <relationshipName>Parties_Prenantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne Physique</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Parties_PrenantesPP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Type de personne physique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mandataire social</fullName>
                <default>true</default>
                <label>Mandataire social</label>
            </value>
            <value>
                <fullName>Bénéficiaire Effectif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/JobTitleBank__c.field-meta.xml
<CustomField>
    <fullName>JobTitleBank__c</fullName>
    <label>Fonction</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactsValidationCtrl_TEST.cls
/*
* @author Wailly LUA  (Wailly.lua@carrenet.com)
* @date 03/10/2018 (dd/mm/yyyy)
* @description Test class for ContactsValidationCtrl_TEST
*/
@isTest
public class ContactsValidationCtrl_TEST{
    static Account entreprise;
    static Contact contactToUpdate;
    static Stakeholder__c stakeHolder;
    /*
     * @author LUA Wailly (Wailly.lua@carrenet.com)
     * @date 03/10/2018 (dd/mm/yyyy)
     * @description Initialise test environment with datas
     */
    static void initOrg(){ 
        
        Id rtClientId = Utils.getAccountRecordTypeByDeveloperName(Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_CLIENT);

        entreprise = new Account(Name = 'Entreprise Contact Validation', RecordTypeId = rtClientId);
        insert entreprise;

        contactToUpdate = new Contact(FirstName = 'Contact FirstName', MobilePhone = '0600000000', LastName = 'Contact Validation', 
                                        AccountId = entreprise.Id);
        insert contactToUpdate;

        stakeHolder = [SELECT Id, JobTitleBank__c, ContactType__c, 
                        Contact__c, Contact__r.LastName, Contact__r.MobilePhone, Contact__r.FirstName, 
                        Contact__r.BirthDate, Contact__r.BirthPlace__c, Contact__r.Nationality__c, Contact__r.Email, 
                        Contact__r.NativeCountry__c, Contact__r.IncomPerTranche__c, Contact__r.Networth__c
                        FROM Stakeholder__c WHERE Company__c = :entreprise.Id AND Contact__c = :contactToUpdate.Id];
        stakeHolder.ActualBeneficiary__c = true;
        update stakeHolder;
    }

    /*
     * @author LUA Wailly (Wailly.lua@carrenet.com)
     * @date 03/10/2018 (dd/mm/yyyy)
     */
    @isTest
    static void getStakeHoldersTest(){    
        initOrg();
        Test.startTest();
            Stakeholder__c[] result = ContactsValidationCtrl.getStakeHolders(entreprise.Id);
            System.assertEquals(1, result.size());
        Test.stopTest();
    }

    /*
     * @author LUA Wailly (Wailly.lua@carrenet.com)
     * @date 03/10/2018 (dd/mm/yyyy)
     */
    @isTest
    static void updateContactTest(){    
        initOrg();
        Test.startTest();
            stakeHolder.JobTitleBank__c = 'Fonctionnaire';
            ContactsValidationCtrl.updateContact(stakeHolder);

            Stakeholder__c stakeHolderToCheck = [SELECT Id,JobTitleBank__c FROM Stakeholder__c WHERE Id = :stakeHolder.Id];
            System.assertEquals('Fonctionnaire', stakeHolderToCheck.JobTitleBank__c);
            
        Test.stopTest();
    }

    /*
     * @author LUA Wailly (Wailly.lua@carrenet.com)
     * @date 03/10/2018 (dd/mm/yyyy)
     */
    /*@isTest
    static void updateAccountTest(){    
        Test.startTest();   
            initOrg();
            ContactsValidationCtrl.updateAccount(entreprise.Id);
            Account entrepriseToCheck = [SELECT Id, ValidatedForAppWallet__c FROM Account WHERE Id = :entreprise.Id];
            System.assertEquals(true, entrepriseToCheck.ValidatedForAppWallet__c);
        Test.stopTest();
    }*/

    /*
     * @author LUA Wailly (Wailly.lua@carrenet.com)
     * @date 03/10/2018 (dd/mm/yyyy)
     */
    @isTest
    static void fetchPicklistValuesTest(){    
        Test.startTest();  
            Map<Integer,List<String>> result = ContactsValidationCtrl.fetchPicklistValues();
            List<String> incomOptions = result.get(0);
            List<String> networthOptions = result.get(1);
            List<String> contactTypeOptions = result.get(2);

            System.assertNotEquals(0, incomOptions.size());
            System.assertNotEquals(0, networthOptions.size());
            System.assertNotEquals(0, contactTypeOptions.size());

        Test.stopTest();
    }

    /*
     * @author LAMBERT Jérémy (jeremy.lambert@tiime.fr)
     * @date 02/01/2019 (dd/mm/yyyy)
     */
    @isTest static void testGetCompanyPicklistValues() {
        Test.startTest();
        Map<String, Map<String, String>> result = ContactsValidationCtrl.getCompanyPicklistValues();

        System.assertEquals(5, result.size());
        System.assertEquals(true, result.containsKey('turnovers'));
        System.assertEquals(true, result.containsKey('employees'));
        System.assertEquals(true, result.containsKey('incomes'));
        System.assertEquals(true, result.containsKey('legalForms'));
        System.assertEquals(true, result.containsKey('contactSalutation'));

        System.assertNotEquals(0, result.get('turnovers').size());
        System.assertNotEquals(0, result.get('employees').size());
        System.assertNotEquals(0, result.get('incomes').size());
        System.assertNotEquals(0, result.get('legalForms').size());
        System.assertNotEquals(0, result.get('contactSalutation').size());
        Test.stopTest();
    }
}