force-app/main/default/objects/User/fields/BypassAllTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassAllTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cocher ce champ si l&#39;utilisateur souhaite ne déclencher aucune action de type Trigger.</description>
    <label>BypassAllTriggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <description>Contient les noms des actions gérées par du code. Les valeurs sélectionnées ne seront pas déclenchées pour cet utilisateur.</description>
    <inlineHelpText>Les valeurs sélectionnées ne seront pas déclenchées pour cet utilisateur.</inlineHelpText>
    <label>BypassTriggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP01_SetEventPhoneFromWhoId</fullName>
            </value>
            <value>
                <fullName>AP02_ContactStakeholder</fullName>
            </value>
            <value>
                <fullName>AP02_EventFromLead</fullName>
            </value>
            <value>
                <fullName>AP03_StakeHolder</fullName>
            </value>
            <value>
                <fullName>AP04_Account</fullName>
            </value>
            <value>
                <fullName>AP06_SendEmailFromLead</fullName>
            </value>
            <value>
                <fullName>AP12_UploadFile</fullName>
            </value>
            <value>
                <fullName>AP16_ManageRecordTypeFromHeroku</fullName>
            </value>
            <value>
                <fullName>AP19_MainContact</fullName>
                <isActive>false</isActive>
                <label>AP19_MainContact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PAD_TEST.cls
/**
* author:		Kévin Melliand
* date:			14/12/2018
* description:	Classe testant PAD. Couverture du code à 100%.
*/
@isTest
public class PAD_TEST {
    
    private static List<Schema.PicklistEntry> pleList = User.BypassTriggers__c.getDescribe().getPicklistValues();
    
    private static String usernamePad = 'test.pad@tiime.fr';
    private static String usernameAllPad = 'test.allpad@tiime.fr';
    private static String usernameNoPad = 'test.nopad@tiime.fr';
    
    private static Integer startValue = 1;
    private static Integer endValue = 2;
    
    
    
    @TestSetup
    static void dataSetup() {
    	
    	// Créer un utilisateur avec un le champ Bypass renseigné.
    	//Schema.DescribeFieldResult fieldResult = User.BypassTriggers__c.getDescribe();
    	//List<Schema.PicklistEntry> pleList = User.BypassTriggers__c.getDescribe().getPicklistValues();
    	
    	User userWithBypass = AP04_Factory.UserStandardFactory(1, 'Test','WithPAD' , usernamePad).get(0);
    	User userWithAllBypass = AP04_Factory.UserStandardFactory(1, 'Test','WithAllPAD' , usernameAllPad).get(0);
    	User WithoutBypass = AP04_Factory.UserStandardFactory(1, 'Test','WithoutPAD' , usernameNoPad).get(0);
    	
    	userWithBypass.BypassTriggers__c = pleList.get(0).getValue();
    	userWithAllBypass.BypassAllTriggers__c = true;

		insert new List<User> {userWithBypass, userWithAllBypass, WithoutBypass};
    }
    
    @isTest
    static void testNoBypassUserBehaviour() {
    	User user = [SELECT Id FROM User WHERE Username = :usernameNoPad].get(0);
    	
    	Integer result = mockAction(user);
    	
    	// Ce user ne bypassant rien, le résultat doit valoir endValue (2)
    	System.assertEquals(endValue, result);
    }
    
    @isTest
    static void testBypassUserBehaviour() {
    	User user = [SELECT Id FROM User WHERE Username = :usernamePad].get(0);
    	
    	Integer result = mockAction(user);
    	
    	// Ce user ne bypassant rien, le résultat doit valoir startValue (1)
    	System.assertEquals(startValue, result);
    }
    
    @isTest
    static void testAllBypassUserBehaviour() {
    	User user = [SELECT Id FROM User WHERE Username = :usernameAllPad].get(0);
    	
    	Integer result = mockAction(user);
    	
    	// Ce user ne bypassant rien, le résultat doit valoir startValue (1)
    	System.assertEquals(startValue, result);
    }
    
    private static Integer mockAction(User user){
    	Integer returnValue = startValue;
    	System.runAs(user) {
    		if(PAD.canTrigger(pleList.get(0).getValue())) {
    			returnValue = endValue;
    		}
    	}
    	return returnValue;
    }
}