force-app/main/default/objects/User/fields/BypassAllTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassAllTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cocher ce champ si l&#39;utilisateur souhaite ne déclencher aucune action de type Trigger.</description>
    <label>BypassAllTriggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <description>Contient les noms des actions gérées par du code. Les valeurs sélectionnées ne seront pas déclenchées pour cet utilisateur.</description>
    <inlineHelpText>Les valeurs sélectionnées ne seront pas déclenchées pour cet utilisateur.</inlineHelpText>
    <label>BypassTriggers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP01_SetEventPhoneFromWhoId</fullName>
            </value>
            <value>
                <fullName>AP02_ContactStakeholder</fullName>
            </value>
            <value>
                <fullName>AP02_EventFromLead</fullName>
            </value>
            <value>
                <fullName>AP03_StakeHolder</fullName>
            </value>
            <value>
                <fullName>AP04_Account</fullName>
            </value>
            <value>
                <fullName>AP06_SendEmailFromLead</fullName>
            </value>
            <value>
                <fullName>AP12_UploadFile</fullName>
            </value>
            <value>
                <fullName>AP16_ManageRecordTypeFromHeroku</fullName>
            </value>
            <value>
                <fullName>AP19_MainContact</fullName>
                <isActive>false</isActive>
                <label>AP19_MainContact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PAD.cls
/**
* author:		Kévin Melliand
* date:			13/12/2018
* description:	Classe PAD pour bypasser certaines actions selon le user 
* test:			PAD_TEST (100%).
*/
public class PAD {
    
    private static User currentUser;
    
    private static Set<String> bypassedValuesSet = new Set<String>();
    
    public static boolean canTrigger(String actionValue) {
    	
    	setUpUser();
    	
    	return !(currentUser.BypassAllTriggers__c || bypassedValuesSet.contains(actionValue));
    }
    
    private static void setUpUser() {
    	
    	if(currentUser == null) {
    		
    		currentUser = [SELECT Id, BypassAllTriggers__c, BypassTriggers__c FROM User WHERE Id = :UserInfo.getUserId()];
    		
    		if(String.isNotBlank(currentUser.BypassTriggers__c)) {
    			for(String s : currentUser.BypassTriggers__c.split(Constants.CUSTOM_LABEL_INNER_SEPARATOR)) {
    				bypassedValuesSet.add(s);
    			}
    		}
    	}
    }
}