force-app/main/default/objects/LogError__c/LogError__c.object-meta.xml
<CustomObject>
    <label>Log d&#39;erreur</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Nom de Log d&#39;erreur</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>logs d&#39;erreur</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogError__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/WS04_Companeo_TEST.cls
/*@isTest*/
public class WS04_Companeo_TEST {
        
    /*@isTest
    static void testGettingNewLeads() {
    	
    	List<Lead> leads = [SELECT Id FROM Lead];
    	System.assert(leads.isEmpty());
    	
    	Test.startTest();
    	WS04_Companeo ws = new WS04_Companeo();
    	ws.req.setHeader('path', 'ok');
    	ws.getAllNewLeadsFromCompaneo();
    	Test.stopTest();
    	
    	leads = [SELECT Id FROM Lead];
    	System.assert(leads.size() == 2);
    }
    
    @isTest
    static void testGettingNewLeadsNoLeads() {
    	
    	List<Lead> leads = [SELECT Id FROM Lead];
    	System.assert(leads.isEmpty());
    	
    	Test.startTest();
    	WS04_Companeo ws = new WS04_Companeo();
    	ws.req.setHeader('path', 'none');
    	ws.getAllNewLeadsFromCompaneo();
    	Test.stopTest();
    	
    	leads = [SELECT Id FROM Lead];
    	System.assert(leads.isEmpty());
    }
    
    @isTest
    static void testGettingNewLeadsDoublon() {
    	
    	List<Lead> leads = [SELECT Id FROM Lead];
    	System.assert(leads.isEmpty());
    	List<LogError__c> errors = [SELECT Id FROM LogError__c];
    	System.assert(errors.isEmpty());
    	
    	Test.startTest();
    	WS04_Companeo ws = new WS04_Companeo();
    	ws.req.setHeader('path', 'doublon');
    	ws.getAllNewLeadsFromCompaneo();
    	
    	
    	leads = [SELECT Id, Email, Name, MobilePhone FROM Lead];
    	System.assert(leads.size() == 1);
    	errors = [SELECT Id, Message__c FROM LogError__c];
    	System.assert(errors.isEmpty());
    	
    	ws.getAllNewLeadsFromCompaneo();
    	Test.stopTest();
    	
    	leads = [SELECT Id, Email, Name, MobilePhone FROM Lead];
    	System.assert(leads.size() == 2);
    	errors = [SELECT Id, Message__c FROM LogError__c];
    	System.assert(errors.size() == 1);
    	for(LogError__c e : errors) {
    		System.debug(e.Message__c);
    	}
    }*/
}