force-app/main/default/objects/HistoryAccount__c/HistoryAccount__c.object-meta.xml
<CustomObject>
    <label>Historique de compte</label>
    <nameField>
        <label>Nom de Historique de compte</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historique de comptes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HistoryAccount__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Date d&#39;application</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HistoryAccount__c/fields/Entreprise__c.field-meta.xml
<CustomField>
    <fullName>Entreprise__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historique de comptes</relationshipLabel>
    <relationshipName>Historique_de_comptes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/HistoryAccount__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Champ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Siret__c</fullName>
            </value>
            <value>
                <fullName>ActivityStartDate__c</fullName>
            </value>
            <value>
                <fullName>BillingCity</fullName>
            </value>
            <value>
                <fullName>BillingStreet</fullName>
            </value>
            <value>
                <fullName>BillingCountry</fullName>
            </value>
            <value>
                <fullName>BillingPostalCode</fullName>
            </value>
            <value>
                <fullName>JobStartDate__c</fullName>
            </value>
            <value>
                <fullName>VatLimitDate__c</fullName>
            </value>
            <value>
                <fullName>LegalStatus__c</fullName>
            </value>
            <value>
                <fullName>OwnerId</fullName>
            </value>
            <value>
                <fullName>nbOfShares__c</fullName>
            </value>
            <value>
                <fullName>CommercialName__c</fullName>
            </value>
            <value>
                <fullName>TaxSystem__c</fullName>
            </value>
            <value>
                <fullName>VatSystem__c</fullName>
            </value>
            <value>
                <fullName>TaxingType__c</fullName>
            </value>
            <value>
                <fullName>RcsCity__c</fullName>
            </value>
            <value>
                <fullName>Team__c</fullName>
            </value>
            <value>
                <fullName>Status__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HistoryAccount__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>Nouvelle valeur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HistoryAccount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type de champ</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchMajHA.cls
global class BatchMajHA implements Database.Batchable<sObject> {
    global List<HistoryAccount__c> listHA;
    
    global BatchMajHA() {
         this.listHA = [SELECT id, Field__c, newValue__c, Entreprise__c, Type__c FROM HistoryAccount__c WHERE EffectiveDate__c = :Date.today() ORDER BY LastModifiedDate ASC];
    }
    
    global List<HistoryAccount__c> start(Database.BatchableContext bc) {
        return this.listHA;
    }
    
    global void execute(Database.BatchableContext bc, List<HistoryAccount__c> listHA) {
        if(!listHA.isEmpty()) {
            //Initialisation de la Map des comptes
            Map<Id,Account> mapAcc = new Map<Id,Account>();
            //Pour chaque HA on crée un objet de type compte en lui donnant l'id du compte au quel est rattaché
            for(HistoryAccount__c unHA : listHA) {
             	//On Vérifie si le compte qui doit être maj est dans la map, si il n'y est pas, on crée un objet de type compte et on l'ajoute à la map.
             	//Si il existe dans la map on met à jour l'attribut du compte.
                if(mapAcc.containsKey(unHA.Entreprise__c)) {
                    //On vérifie le type du champ afin d'éviter les erreurs des types (String dans le HA mais peut être un double ou une date dans le compte en fonction du champ)
                    if(unHA.Type__c == 'double') {
                        mapAcc.get(unHA.Entreprise__c).put(unHA.Field__c, decimal.valueOf(unHA.NewValue__c));
                    }
                    else if(unHA.Type__c == 'date') {
                    	mapAcc.get(unHA.Entreprise__c).put(unHA.Field__c, date.valueOf(unHA.NewValue__c));
                	}
                    else {
                        mapAcc.get(unHA.Entreprise__c).put(unHA.Field__c, unHA.NewValue__c);
                    }
                }
                else {
                    Account unAcc = new Account(Id = unHA.Entreprise__c);
                    if(unHA.Type__c == 'double') {
                        unAcc.put(unHA.Field__c, decimal.valueOf(unHA.NewValue__c));
                    }
                    else if(unHA.Type__c == 'date') {
                    	unAcc.put(unHA.Field__c, date.valueOf(unHA.NewValue__c));
                	}
                    else {
                        unAcc.put(unHA.Field__c, unHA.NewValue__c);
                    }
                    mapAcc.put(unHA.Entreprise__c, unAcc);
                }
            }
            update mapAcc.values();
            System.debug('MAP DES MAJ => ' + mapAcc);
        }
    }
    
    global void finish(Database.BatchableContext bc) {
    }
}