force-app/main/default/objects/Lead/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <description>Signatures des sms et mail</description>
    <inlineHelpText>Signatures des sms et mails</inlineHelpText>
    <label>Branding de sortie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ContactPartenariat__c.field-meta.xml
<CustomField>
    <fullName>ContactPartenariat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Le contact qui a envoyé la Lead.
C&#39;est un contact associé à l&#39;entreprise du champ référence &#39;Détail partenariat&#39;</description>
    <label>Contact - Partenariat</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partenariat</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contact - Partenariat)</relationshipLabel>
    <relationshipName>LeadsPartenariat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Echeance_de_besoin_de_creation__c.field-meta.xml
<CustomField>
    <fullName>Echeance_de_besoin_de_creation__c</fullName>
    <label>Echéance de besoin de création</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immédiat</fullName>
            </value>
            <value>
                <fullName>1 mois</fullName>
            </value>
            <value>
                <fullName>3 mois</fullName>
            </value>
            <value>
                <fullName>6 mois et plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Evaluation_a_priori__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_a_priori__c</fullName>
    <label>Qualité de la lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1Star</fullName>
                <label>⭐</label>
            </value>
            <value>
                <fullName>2Stars</fullName>
                <label>⭐⭐</label>
            </value>
            <value>
                <fullName>3Stars</fullName>
                <label>⭐⭐⭐</label>
            </value>
            <value>
                <fullName>4Stars</fullName>
                <label>⭐⭐⭐⭐</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>Forme Juridique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SASUSAS</fullName>
                <label>SASU / SAS</label>
            </value>
            <value>
                <fullName>EURLSARL</fullName>
                <label>EURL / SARL</label>
            </value>
            <value>
                <fullName>EntrepriseIndividuelle</fullName>
                <label>Entreprise Individuelle</label>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>SCI</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>NeSaitPas</fullName>
                <label>Ne sait pas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <formula>UtmSource__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TypeOfNeed__c.field-meta.xml
<CustomField>
    <fullName>TypeOfNeed__c</fullName>
    <label>Type de besoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Création</fullName>
            </value>
            <value>
                <fullName>Comptabilité</fullName>
            </value>
            <value>
                <fullName>Création et Comptabilité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/WebFormComments__c.field-meta.xml
<CustomField>
    <fullName>WebFormComments__c</fullName>
    <label>Commentaires du formulaire Web</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/WillHaveEmployes__c.field-meta.xml
<CustomField>
    <fullName>WillHaveEmployes__c</fullName>
    <label>Employés?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <label>Stakeholder</label>
    <nameField>
        <label>Nom du Stakeholder</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stakeholder__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Entreprise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stakeholders</relationshipLabel>
    <relationshipName>Parties_Prenantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stakeholder__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personne Physique</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Parties_PrenantesPP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L-Expert-Comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Tiime</fullName>
    </customValue>
    <customValue>
        <fullName>Trouver-mon-comptable.com</fullName>
    </customValue>
    <customValue>
        <fullName>Novaa</fullName>
    </customValue>
    <customValue>
        <fullName>Incityz</fullName>
    </customValue>
    <customValue>
        <fullName>Condillac</fullName>
    </customValue>
    <customValue>
        <fullName>Goneo</fullName>
    </customValue>
    <customValue>
        <fullName>Ola Compta</fullName>
    </customValue>
    <customValue>
        <fullName>Le Net Expert Comptable</fullName>
    </customValue>
    <customValue>
        <fullName>Onlicorn</fullName>
    </customValue>
    <customValue>
        <fullName>Pepit</fullName>
    </customValue>
    <customValue>
        <fullName>L-Expert-Comptable Lille</fullName>
    </customValue>
    <customValue>
        <fullName>Evocompta</fullName>
    </customValue>
    <customValue>
        <fullName>Auficom</fullName>
    </customValue>
    <customValue>
        <fullName>Proxi Compta</fullName>
    </customValue>
    <description>liste des marques</description>
    <masterLabel>Marques</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP15_ControllerLeadResume.cls
public with sharing class AP15_ControllerLeadResume {
	
	private final static Integer MAX_RESULTS = 5;

	private static Map <String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Lead').getDescribe().fields.getMap();

	private static String getLabel(String fieldName) {
		Schema.SObjectField field = fieldMap.get(fieldName);
		Schema.DescribeFieldResult describe = field.getDescribe();
		return describe.getLabel();
	}

	@AuraEnabled
	public static Map<String, String> getLabels() {
		//Workaround to get field label in lightning component
		Map<String, String> labels = new Map<String, String>();
		labels.put('MobilePhone', getLabel('MobilePhone'));
		labels.put('WebFormComments__c', getLabel('WebFormComments__c'));
		labels.put('Evaluation_a_priori__c', getLabel('Evaluation_a_priori__c'));
		labels.put('Echeance_de_besoin_de_creation__c', getLabel('Echeance_de_besoin_de_creation__c'));
		labels.put('TypeOfNeed__c', getLabel('TypeOfNeed__c'));
		labels.put('WillHaveEmployes__c', getLabel('WillHaveEmployes__c'));
		labels.put('LegalStatus__c', getLabel('LegalStatus__c'));
		labels.put('Source__c', getLabel('Source__c'));
		labels.put('ContactPartenariat__c', getLabel('ContactPartenariat__c'));
		
		return labels;
	}
	
	@AuraEnabled
	public static List<Map<String, String>> getPicklistOptions(List<String> fieldNames) {
		List<Map<String, String>> lesPickLists = new List<Map<String, String>>();
		for(String fieldName : fieldNames)
			lesPickLists.add(Utils.getPicklistOptions('Lead', fieldName));
		return lesPickLists;

	}
	
	@AuraEnabled
	public static String nextCall(Id leadId, String status, String branding) {
		
		if(String.isBlank(branding)){
			 AuraHandledException e = new AuraHandledException('Merci de renseigner le Branding.');
			 e.setMessage('Merci de renseigner le Branding.');
			 throw e;
		}
		try{
			Lead lead = [SELECT Id, Status, Branding__c FROM Lead WHERE Id=:leadId];
			lead.Status = Constants.LEAD_MAP_NEXT_STATUS.get(status);
			lead.Branding__c = branding;
			update lead;
			return lead.Status;
		}catch(Exception e){
			throw new AuraHandledException(e.getMessage());
		}
	}
	
	@AuraEnabled
	public static String getStatus(Id leadId) {
		Lead lead = [SELECT Id, Status FROM Lead WHERE Id=:leadId];
		return lead.Status;
	}
	
	@AuraEnabled
	public static List<Contact> getContactPartenariat(Id accountId){
		return [SELECT Id, Name From Contact WHERE AccountId = :accountId];
	}
  
	@AuraEnabled
	public static String getLeadEnAttenteId(){
		return [SELECT Id FROM Group WHERE Type = :Constants.FILE_ATTENTE_OBJECT_TYPE AND DeveloperName = :Constants.FILE_ATTENTE_CALL1_DEV_NAME].Id;
	}
	
	@AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds) {
        // Prepare query paramters
        searchTerm += '*';

        // Execute search query
        List<List<SObject>> searchResults = [FIND :searchTerm IN ALL FIELDS RETURNING
            Stakeholder__c (Id, Name, Company__c, Contact__c WHERE id NOT IN :selectedIds),
            Lead (Id, Name WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Stackeholder & convert them into LookupSearchResult
        String stakeIcon = 'standard:contact';
        Stakeholder__c [] Stakeholders = ((List<Stakeholder__c>) searchResults[0]);
        for (Stakeholder__c stakeholder : Stakeholders) {
            results.add(new LookupSearchResult(stakeholder.Contact__c, 'Stakeholder__c', stakeIcon, stakeholder.Name, stakeholder.Name));
        }

        // Extract Opportunities & convert them into LookupSearchResult
        String leadIcon = 'standard:lead';
        Lead [] leads = ((List<Lead>) searchResults[1]);
        for (Lead l : leads) {
            results.add(new LookupSearchResult(l.Id, 'Lead', leadIcon, l.Name, l.Name));
        }

        return results;
    }
}