force-app/main/default/objects/Lead/fields/Contact_Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Contact_Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Partenaire</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Il est indispensable de choisir un contact du Cabinet Partenaire</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Partenaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contact Partenaire)</relationshipLabel>
    <relationshipName>LeadsContactPartner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <label>Corps du mail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Appointment_Set__c.field-meta.xml
<CustomField>
    <fullName>Is_Appointment_Set__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Case système.
Cochée les champs de RDV ont été renseignés via le composant LeadAppointment.</description>
    <label>RDV planifié</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LossReason__c.field-meta.xml
<CustomField>
    <fullName>LossReason__c</fullName>
    <label>Motif de la perte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ContreLeEnLigneW</fullName>
                <label>Contre le &quot;En Ligne&quot; - W</label>
            </value>
            <value>
                <fullName>EnAttenteFinancementW</fullName>
                <label>En attente de financement - W</label>
            </value>
            <value>
                <fullName>EnAttenteRetraiteW</fullName>
                <label>En attente de sa retraite - W</label>
            </value>
            <value>
                <fullName>EncoreEngageAvecECW</fullName>
                <label>Encore engagé avec son EC - W</label>
            </value>
            <value>
                <fullName>EncoreSalariéProcessRuptureConventionnelleW</fullName>
                <label>Encore salarié - en process rupture conventionnelle - W</label>
            </value>
            <value>
                <fullName>SeRenseigneReflechitW</fullName>
                <label>Se renseigne - réfléchit - W</label>
            </value>
            <value>
                <fullName>Auto Entrepreneur</fullName>
            </value>
            <value>
                <fullName>Candidature RH</fullName>
            </value>
            <value>
                <fullName>concurrence</fullName>
                <label>Concurrence</label>
            </value>
            <value>
                <fullName>Demande à l&#39;étranger</fullName>
            </value>
            <value>
                <fullName>Demande d&#39;un salarié</fullName>
            </value>
            <value>
                <fullName>Doublon</fullName>
            </value>
            <value>
                <fullName>Expert comptable</fullName>
            </value>
            <value>
                <fullName>Hors cible</fullName>
            </value>
            <value>
                <fullName>Inbound LEC</fullName>
            </value>
            <value>
                <fullName>injoignable</fullName>
                <label>Injoignable</label>
            </value>
            <value>
                <fullName>Mauvais numéro</fullName>
            </value>
            <value>
                <fullName>Officéo</fullName>
            </value>
            <value>
                <fullName>Pas de numéro</fullName>
            </value>
            <value>
                <fullName>Projet non viable</fullName>
            </value>
            <value>
                <fullName>Questions sur les apps</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Trop en amont</fullName>
            </value>
            <value>
                <fullName>Demande HS</fullName>
            </value>
            <value>
                <fullName>Envoi vers BGE Ile de France</fullName>
            </value>
            <value>
                <fullName>hors-méthode</fullName>
                <isActive>false</isActive>
                <label>Hors méthode groupe</label>
            </value>
            <value>
                <fullName>Pas de partenaire adapté</fullName>
                <isActive>false</isActive>
                <label>Pas de partenaire adapté</label>
            </value>
            <value>
                <fullName>hors secteur géographique</fullName>
                <isActive>false</isActive>
                <label>hors secteur géographique</label>
            </value>
            <value>
                <fullName>hors-métier</fullName>
                <isActive>false</isActive>
                <label>hors-métier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Le compte partenaire doit être de type &#39;EC Partenaire&#39;. Pour les Partenariat, seuls les cabinets groupes sont valides.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>EC Partenaire</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partenariat</value>
        </filterItems>
        <filterItems>
            <field>$Source.PartnerType__c</field>
            <operation>equals</operation>
            <value>Groupe</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partenaire)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Rendez_vous__c.field-meta.xml
<CustomField>
    <fullName>Rendez_vous__c</fullName>
    <label>Date du rendez-vous</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AP06_SendEmailFromLead_TEST.cls
/**
* author:		Kévin Melliand
* date:			13/12/2018
* description:	Classe testant AP06_SendEmailFromLead. Couverture du code à 97%.
*/
@isTest
public class AP06_SendEmailFromLead_TEST {
    
    @TestSetup
    static void dataSetup() {
    	AP04_Factory.createGenericDataSample();
    	
    	List<Lead> leads = [SELECT Id FROM Lead];
    	System.assert(!leads.isEmpty());
    }
    
    @isTest
    static void proceedTest() {
    	
    	List<Lead> leads = [SELECT Id, Salutation, Name, Company, Email FROM Lead];
    	
    	List<Account> partnerAccounts = [SELECT Id, Name, (SELECT Id, Name FROM Contacts) FROM Account WHERE RecordType.DeveloperName = :Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_PARTNER];
    	
    	Test.startTest();
    	if(!partnerAccounts.isEmpty()) {
    		for(Lead l : leads) {
    			l.Partenaire__c = partnerAccounts.get(0).id;
	    		l.Contact_Partenaire__c = partnerAccounts.get(0).Contacts.get(0).id;
	    		l.Email_Body__c = 'Corps du mail pour un test';
	    		Datetime dt = Datetime.now();
	    		l.Rendez_vous__c = dt.addDays(2);
	    		l.Is_Appointment_Set__c = true;
    		}
    		
    		update leads;
    	} else {
    		System.assert(false);
    	}
    	
    	System.assert(AP06_SendEmailFromLead.hasBeenCalled);
    	System.assertEquals(4, AP06_SendEmailFromLead.nbEmail);
    	
    	Test.stopTest();
    	
    	
    }
    
    @isTest
    static void testFromProcessBuilder() {
    	List<Lead> leads = [SELECT Id, Salutation, Name, Company, Email, Status, LossReason__c FROM Lead];
    	
    	List<Account> partnerAccounts = [SELECT Id, Name, (SELECT Id, Name FROM Contacts) FROM Account WHERE RecordType.DeveloperName = :Constants.ACCOUNT_RECORDTYPE_DEVELOPERNAME_PARTNER];
    	
    	Lead lead = Leads.get(0);
    	//lead.Status = Constants.LEAD_STATUS_CALL2;
    	//update lead;
    	
    	Test.startTest();
    	lead.Status = Constants.LEAD_STATUS_PERDU;
    	lead.LossReason__c = Constants.LEAD_SUIVI_TRANSFERT_INJOIGNABLE;
    	update lead;
    	Test.stopTest();
    }
}