force-app/main/default/objects/Lead/fields/CreationProject__c.field-meta.xml
<CustomField>
    <fullName>CreationProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projet de création</label>
    <referenceTo>Start__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DateLeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackCastingError__c</fullName>
    <label>Date de retour erreur de casting</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DateLeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackTiimeCrea__c</fullName>
    <label>Date retour Créa Tiime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>LeadBackCastingError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour erreur de casting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>LeadBackTiimeCrea__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour suite Créa Tiime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/Crea__c.field-meta.xml
<CustomField>
    <fullName>Crea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/DateLeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackCastingError__c</fullName>
    <label>Date de retour erreur de casting</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/DateLeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackTiimeCrea__c</fullName>
    <label>Date retour Créa Tiime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/LeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>LeadBackCastingError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour erreur de casting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/LeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>LeadBackTiimeCrea__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour suite Créa Tiime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transfert__c/Transfert__c.object-meta.xml
<CustomObject>
    <label>Transfert</label>
    <nameField>
        <label>Nom de Transfert Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transferts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfert__c/fields/DateLeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackCastingError__c</fullName>
    <inlineHelpText>Horodatage de la case à cocher &quot;Lead renvoyer (Erreur de casting)</inlineHelpText>
    <label>Date de retour erreur de casting</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/LeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>LeadBackCastingError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si un renvoi de la Lead aux SDR à été fait pour erreur de casting, cette case sera cochée.</description>
    <label>Retour erreur de casting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LTC21_LeadBack_TEST.cls
@isTest
private class LTC21_LeadBack_TEST {
	
	@isTest
    static void horodatageLeadBackT_TEST(){		
    	Lead l = AP04_Factory.newWebLeadsFactory(1)[0];
    	insert l;
		Transfert__c t = new Transfert__c(Name = 'transfertName', Lead__c = l.Id);
		insert t;
		System.assert(t.LeadBackCastingError__c == false && t.DateLeadBackCastingError__c == null);
		System.assert(l.LeadBackCastingError__c == false && l.DateLeadBackCastingError__c == null);
		
		Test.startTest();
		LTC21_LeadBack.horodatageLeadBackT(t.Id,l.Id);
		Test.stopTest();
		
		t = [SELECT Id, LeadBackCastingError__c, DateLeadBackCastingError__c FROM Transfert__c WHERE Id = :t.Id];
		l = [SELECT Id, LeadBackCastingError__c, DateLeadBackCastingError__c FROM Lead WHERE Id = :l.Id];
		
		System.assert(t.LeadBackCastingError__c == true && t.DateLeadBackCastingError__c != null);
		System.assert(l.LeadBackCastingError__c == true && l.DateLeadBackCastingError__c != null);
	}
	
	@isTest
	static void horodatageLeadBackPC_TEST(){
    	Lead l = AP04_Factory.newWebLeadsFactory(1)[0];
        insert l;
		Start__c s = new Start__c(Name = 'startName', Crea__c = l.Id);
        insert s;
        l = [SELECT Id, CreationProject__c FROM Lead WHERE Id = :l.Id];
		l.CreationProject__c = s.Id;
		update l;
		
		System.assert(s.LeadBackTiimeCrea__c == false && s.DateLeadBackTiimeCrea__c == null);
		System.assert(l.LeadBackTiimeCrea__c == false && l.DateLeadBackTiimeCrea__c == null);
		
		Test.startTest();
		LTC21_LeadBack.horodatageLeadBackPC(s.Id,l.Id);
		Test.stopTest();
		
		s = [SELECT Id, LeadBackTiimeCrea__c, DateLeadBackTiimeCrea__c FROM Start__c WHERE Id = :s.Id];
		l = [SELECT Id, LeadBackTiimeCrea__c, DateLeadBackTiimeCrea__c FROM Lead WHERE Id = :l.Id];
		
		System.assert(s.LeadBackTiimeCrea__c == true && s.DateLeadBackTiimeCrea__c != null);
		System.assert(l.LeadBackTiimeCrea__c == true && l.DateLeadBackTiimeCrea__c != null);
	}
	
	@isTest
	static void horodatageLeadBackCastingPC_TEST(){
    	Lead l = AP04_Factory.newWebLeadsFactory(1)[0];
        insert l;
		Start__c s = new Start__c(Name = 'startName', Crea__c = l.Id);
        insert s;
        l = [SELECT Id, CreationProject__c FROM Lead WHERE Id = :l.Id];
		l.CreationProject__c = s.Id;
		update l;
		
		System.assert(s.LeadBackCastingError__c == false && s.DateLeadBackCastingError__c == null);
		System.assert(l.LeadBackCastingError__c == false && l.DateLeadBackCastingError__c == null);
		
		Test.startTest();
		LTC21_LeadBack.horodatageLeadBackCastingPC(s.Id,l.Id);
		Test.stopTest();
		
		s = [SELECT Id, LeadBackCastingError__c, DateLeadBackCastingError__c FROM Start__c WHERE Id = :s.Id];
		l = [SELECT Id, LeadBackCastingError__c, DateLeadBackCastingError__c FROM Lead WHERE Id = :l.Id];
		
		System.assert(s.LeadBackCastingError__c == true && s.DateLeadBackCastingError__c != null);
		System.assert(l.LeadBackCastingError__c == true && l.DateLeadBackCastingError__c != null);
	}
}