force-app/main/default/objects/Lead/fields/DateLeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackCastingError__c</fullName>
    <label>Date de retour erreur de casting</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DateLeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackTiimeCrea__c</fullName>
    <label>Date retour Créa Tiime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>LeadBackCastingError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour erreur de casting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>LeadBackTiimeCrea__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour suite Créa Tiime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/DateLeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackCastingError__c</fullName>
    <label>Date de retour erreur de casting</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/DateLeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackTiimeCrea__c</fullName>
    <label>Date retour Créa Tiime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/LeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>LeadBackCastingError__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour erreur de casting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Start__c/fields/LeadBackTiimeCrea__c.field-meta.xml
<CustomField>
    <fullName>LeadBackTiimeCrea__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour suite Créa Tiime</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transfert__c/Transfert__c.object-meta.xml
<CustomObject>
    <label>Transfert</label>
    <nameField>
        <label>Nom de Transfert Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transferts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfert__c/fields/DateLeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>DateLeadBackCastingError__c</fullName>
    <inlineHelpText>Horodatage de la case à cocher &quot;Lead renvoyer (Erreur de casting)</inlineHelpText>
    <label>Date de retour erreur de casting</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/LeadBackCastingError__c.field-meta.xml
<CustomField>
    <fullName>LeadBackCastingError__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si un renvoi de la Lead aux SDR à été fait pour erreur de casting, cette case sera cochée.</description>
    <label>Retour erreur de casting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LTC21_LeadBack.cls
public with sharing class LTC21_LeadBack {
	@AuraEnabled
	public static void horodatageLeadBackT(Id transferId, Id leadId){
		update new Transfert__c(Id = transferId, LeadBackCastingError__c = true, DateLeadBackCastingError__c = Datetime.now());
		update new Lead(Id = leadId, LeadBackCastingError__c = true, DateLeadBackCastingError__c = Datetime.now());
	}
	
	@AuraEnabled
	public static void horodatageLeadBackPC(Id startId, Id leadId){
		update new Start__c(Id = startId, LeadBackTiimeCrea__c = true, DateLeadBackTiimeCrea__c = Datetime.now());
		update new Lead(Id = leadId, LeadBackTiimeCrea__c = true, DateLeadBackTiimeCrea__c = Datetime.now());
	}
	
	@AuraEnabled
	public static void horodatageLeadBackCastingPC(Id startId, Id leadId){
		update new Start__c(Id = startId, LeadBackCastingError__c = true, DateLeadBackCastingError__c = Datetime.now());
		update new Lead(Id = leadId, LeadBackCastingError__c = true, DateLeadBackCastingError__c = Datetime.now());
	}
}