force-app/main/default/objects/Lead/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Le compte partenaire doit être de type &#39;EC Partenaire&#39;. Pour les Partenariat, seuls les cabinets groupes sont valides.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>EC Partenaire</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partenariat</value>
        </filterItems>
        <filterItems>
            <field>$Source.PartnerType__c</field>
            <operation>equals</operation>
            <value>Groupe</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partenaire)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Start__c/Start__c.object-meta.xml
<CustomObject>
    <label>Projet de création</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets de création</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Start__c/fields/Crea__c.field-meta.xml
<CustomField>
    <fullName>Crea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/Transfert__c.object-meta.xml
<CustomObject>
    <label>Transfert</label>
    <nameField>
        <label>Nom de Transfert Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transferts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfert__c/fields/ContactPartenaire__c.field-meta.xml
<CustomField>
    <fullName>ContactPartenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Partenaire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_Confirmation_SMS_TEST.cls
@isTest
public class Batch_Confirmation_SMS_TEST {
    
    @TestSetup
    static void prepareData() {
    	AP04_Factory.createGenericDataSample();
    	
    	// Generate an Start__c record
    	List<Lead> leads = [SELECT Id FROM Lead];
    	Start__c start = new Start__c(Crea__c = leads.get(0).Id);
    	insert start;
    	
    	// Generate an event on the start record
    	Event event = new Event(WhatId = start.Id, OwnerId = UserInfo.getUserId(), StartDateTime = DateTime.now().addHours(23).addMinutes(59), EndDateTime = Datetime.now().addHours(24));
    	insert event;
    	
    	List<Contact> contacts = [SELECT Id, AccountId FROM Contact WHERE RecordType.DeveloperName = :Constants.CONTACT_RECORDTYPE_DEVELOPERNAME_PARTNER];
    	if(!contacts.isEmpty()) {
    		Transfert__c transfert = new Transfert__c(
    			Lead__c = leads.get(0).Id, 
    			Partenaire__c = contacts.get(0).AccountId, 
    			ContactPartenaire__c = contacts.get(0).Id
    		);
    		insert transfert;
    		
    		Event transfertEvent = new Event(WhatId = transfert.Id, OwnerId = UserInfo.getUserId(), StartDateTime = DateTime.now().addHours(23).addMinutes(59), EndDateTime = Datetime.now().addHours(24));
    		insert transfertEvent;
    	} else {
    		System.assert(false);
    	}
    }
    
    @isTest
    static void testRunBatch() {
    	List<Event> events = [SELECT Id, ConfirmationSmsSend__c FROM Event];
    	System.assert(events.size() == 2);
    	System.assert(!events.get(0).ConfirmationSmsSend__c);
    	System.assert(!events.get(1).ConfirmationSmsSend__c);
    	
    	Test.startTest();
    	Test.setMock(HttpCalloutMock.class, new SMS_Test.wsSMS_Mock());
    	System.enqueueJob(new Batch_Confirmation_SMS());
    	Test.stopTest();
    	
    	events = [SELECT Id, ConfirmationSmsSend__c FROM Event];
    	System.assert(events.size() == 2);
    	System.assert(events.get(0).ConfirmationSmsSend__c);
    	System.assert(events.get(1).ConfirmationSmsSend__c);
    }
}