force-app/main/default/objects/enquetedeSatisfaction__c/enquetedeSatisfaction__c.object-meta.xml
<CustomObject>
    <label>Enquête de Satisfaction</label>
    <nameField>
        <displayFormat>SATISF-{0000}</displayFormat>
        <label>Enquête de Satisfaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquêtes de Satisfaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/notedeSatisfactionGlobale__c.field-meta.xml
<CustomField>
    <fullName>notedeSatisfactionGlobale__c</fullName>
    <label>Note de Satisfaction Globale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/NotePropale__c.field-meta.xml
<CustomField>
    <fullName>NotePropale__c</fullName>
    <description>La proposition commerciale est-elle correcte?</description>
    <label>Note Proposition commerciale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/NoteReactiviteNPSDetractor__c.field-meta.xml
<CustomField>
    <fullName>NoteReactiviteNPSDetractor__c</fullName>
    <formula>IF((ISPICKVAL(RepresentativeReactivityNote__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(RepresentativeReactivityNote__c)) &lt; 7, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note réactivité NPSDetractor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/NoteReactiviteNpsPassive__c.field-meta.xml
<CustomField>
    <fullName>NoteReactiviteNpsPassive__c</fullName>
    <formula>IF((ISPICKVAL(RepresentativeReactivityNote__c,&quot;Ne se prononce pas&quot;)),1, 
IF(AND( 
VALUE(TEXT(RepresentativeReactivityNote__c)) &gt; 6 , 
VALUE(TEXT(RepresentativeReactivityNote__c)) &lt; 9 ), 
1, 
0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note réactivité NPSPassive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/NoteReactiviteNpsPromoter__c.field-meta.xml
<CustomField>
    <fullName>NoteReactiviteNpsPromoter__c</fullName>
    <formula>IF((ISPICKVAL(RepresentativeReactivityNote__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(RepresentativeReactivityNote__c)) &gt; 8, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note réactivité NPSPromoter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/noteSatisfactionGlobaleNpsDetractor__c.field-meta.xml
<CustomField>
    <fullName>noteSatisfactionGlobaleNpsDetractor__c</fullName>
    <formula>IF((ISPICKVAL(notedeSatisfactionGlobale__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(notedeSatisfactionGlobale__c)) &lt; 7, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note Satisfaction Globale NPSDetractor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/noteSatisfactionGlobaleNpsPassive__c.field-meta.xml
<CustomField>
    <fullName>noteSatisfactionGlobaleNpsPassive__c</fullName>
    <formula>IF((ISPICKVAL(notedeSatisfactionGlobale__c,&quot;Ne se prononce pas&quot;)),1, 
IF(AND( 
VALUE(TEXT(notedeSatisfactionGlobale__c)) &gt; 6 , 
VALUE(TEXT(notedeSatisfactionGlobale__c)) &lt; 9 ), 
1, 
0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note Satisfaction Globale NPSPassive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/NoteSatisfactionGlobaleNpsPromoter__c.field-meta.xml
<CustomField>
    <fullName>NoteSatisfactionGlobaleNpsPromoter__c</fullName>
    <formula>IF((ISPICKVAL(notedeSatisfactionGlobale__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(notedeSatisfactionGlobale__c)) &gt; 8, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note Satisfaction Globale NPSPromoter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquêtes de Satisfaction</relationshipLabel>
    <relationshipName>SatisfactionSurvey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/PropaleNotesNPSDetractor__c.field-meta.xml
<CustomField>
    <fullName>PropaleNotesNPSDetractor__c</fullName>
    <formula>IF((ISPICKVAL(NotePropale__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(NotePropale__c)) &lt; 7, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note Propale NPSDetractor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/PropaleNotesNPSPassive__c.field-meta.xml
<CustomField>
    <fullName>PropaleNotesNPSPassive__c</fullName>
    <formula>IF((ISPICKVAL(NotePropale__c,&quot;Ne se prononce pas&quot;)),1, 
IF(AND( 
VALUE(TEXT(NotePropale__c)) &gt; 6 , 
VALUE(TEXT(NotePropale__c)) &lt; 9 ), 
1, 
0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note Propale NPSPassive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/PropaleNotesNPSPromoter__c.field-meta.xml
<CustomField>
    <fullName>PropaleNotesNPSPromoter__c</fullName>
    <formula>IF((ISPICKVAL(NotePropale__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(NotePropale__c)) &gt; 8, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note Propale NPSPromoter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/RepresentativeSkillsNotes__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeSkillsNotes__c</fullName>
    <label>Note Compétences</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/RepresentativeSkillsNotesNPSDetractor__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeSkillsNotesNPSDetractor__c</fullName>
    <formula>IF((ISPICKVAL(RepresentativeSkillsNotes__c,&quot;Ne se prononce pas&quot;)),
			0,
			IF( VALUE(TEXT(RepresentativeSkillsNotes__c)) &lt; 7, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note compétence NPSDetractor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/RepresentativeSkillsNotesNPSPassive__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeSkillsNotesNPSPassive__c</fullName>
    <formula>IF((ISPICKVAL(RepresentativeSkillsNotes__c,&quot;Ne se prononce pas&quot;)),1,
				IF(AND( 
VALUE(TEXT(RepresentativeSkillsNotes__c)) &gt; 6 , 
VALUE(TEXT(RepresentativeSkillsNotes__c)) &lt; 9 ), 
			1,
						0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note Compétences NPSPassive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/RepresentativeSkillsNotesNPSPromoter__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeSkillsNotesNPSPromoter__c</fullName>
    <formula>IF((ISPICKVAL(RepresentativeSkillsNotes__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(RepresentativeSkillsNotes__c)) &gt; 8, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note compétence NPSPromoter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Satisfaction1contactNotesNPSDetractor__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction1contactNotesNPSDetractor__c</fullName>
    <formula>IF((ISPICKVAL(notedeSatisfactionPrisecontact__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(notedeSatisfactionPrisecontact__c)) &lt; 7, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note de satisf contact NPSDetractor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Satisfaction1contactNotesNPSPassive__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction1contactNotesNPSPassive__c</fullName>
    <formula>IF((ISPICKVAL(notedeSatisfactionPrisecontact__c,&quot;Ne se prononce pas&quot;)),1,
				IF(AND( 
VALUE(TEXT(notedeSatisfactionPrisecontact__c)) &gt; 6 , 
VALUE(TEXT(notedeSatisfactionPrisecontact__c)) &lt; 9 ), 
			1,
						0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note de satisf contact NPSPassive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Satisfaction1contactNotesNPSPromoter__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction1contactNotesNPSPromoter__c</fullName>
    <formula>IF((ISPICKVAL(notedeSatisfactionPrisecontact__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(notedeSatisfactionPrisecontact__c)) &gt; 8, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note de satisf contact NPSPromoter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/SimplicityNotesNPSDetractor__c.field-meta.xml
<CustomField>
    <fullName>SimplicityNotesNPSDetractor__c</fullName>
    <formula>IF((ISPICKVAL(Simplicite_du_process__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(Simplicite_du_process__c)) &lt; 7, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note simplicité NPSDetractor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/SimplicityNotesNPSPassive__c.field-meta.xml
<CustomField>
    <fullName>SimplicityNotesNPSPassive__c</fullName>
    <formula>IF((ISPICKVAL(Simplicite_du_process__c,&quot;Ne se prononce pas&quot;)),1, 
IF(AND( 
VALUE(TEXT(Simplicite_du_process__c)) &gt; 6 , 
VALUE(TEXT(Simplicite_du_process__c)) &lt; 9 ), 
1, 
0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note simplicité NPSPassive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/SimplicityNotesNPSPromoter__c.field-meta.xml
<CustomField>
    <fullName>SimplicityNotesNPSPromoter__c</fullName>
    <formula>IF((ISPICKVAL(Simplicite_du_process__c,&quot;Ne se prononce pas&quot;)), 
0, 
IF( VALUE(TEXT(Simplicite_du_process__c)) &gt; 8, 1, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Note simplicité NPSPromoter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LTC13_rapportNPS.cls
public with sharing class LTC13_rapportNPS {
	
	private static Map <String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('enquetedeSatisfaction__c').getDescribe().fields.getMap();
	
    @AuraEnabled
    public static List<enquetedeSatisfaction__c> getEnquetes(String AccountId){
    	List<enquetedeSatisfaction__c> enquestes =  [Select Id, Name, noteSatisfactionGlobaleNpsPassive__c, 
    	noteSatisfactionGlobaleNpsDetractor__c, SimplicityNotesNPSPromoter__c, SimplicityNotesNPSPassive__c, SimplicityNotesNPSDetractor__c, 
    	Satisfaction1contactNotesNPSPromoter__c, Satisfaction1contactNotesNPSPassive__c, Satisfaction1contactNotesNPSDetractor__c, 
    	RepresentativeSkillsNotesNPSPromoter__c, RepresentativeSkillsNotesNPSPassive__c, RepresentativeSkillsNotesNPSDetractor__c, 
    	PropaleNotesNPSPromoter__c, PropaleNotesNPSPassive__c, PropaleNotesNPSDetractor__c, NoteSatisfactionGlobaleNpsPromoter__c, 
    	NoteReactiviteNpsPromoter__c, NoteReactiviteNpsPassive__c, NoteReactiviteNPSDetractor__c  From enquetedeSatisfaction__c Where Partner__c =:AccountId];
    	return enquestes;
    }
    
    private static String getLabel(String fieldName) {
		Schema.SObjectField field = fieldMap.get(fieldName);
		Schema.DescribeFieldResult describe = field.getDescribe();
		return describe.getLabel();
	}

	@AuraEnabled
	public static Map<String, String> getLabels() {
		//Workaround to get field label in lightning component
		Map<String, String> labels = new Map<String, String>();
		labels.put('RepresentativeSkillsNotes__c', getLabel('RepresentativeSkillsNotes__c'));
		labels.put('notedeSatisfactionGlobale__c', getLabel('notedeSatisfactionGlobale__c'));
		labels.put('NotePropale__c', getLabel('NotePropale__c'));
		labels.put('RepresentativeReactivityNote__c', getLabel('RepresentativeReactivityNote__c'));
		labels.put('Simplicite_du_process__c', getLabel('Simplicite_du_process__c'));
		labels.put('notedeSatisfactionPrisecontact__c', getLabel('notedeSatisfactionPrisecontact__c'));
		return labels;
	}
}