force-app/main/default/objects/enquetedeSatisfaction__c/enquetedeSatisfaction__c.object-meta.xml
<CustomObject>
    <label>Enquête de Satisfaction</label>
    <nameField>
        <displayFormat>SATISF-{0000}</displayFormat>
        <label>Enquête de Satisfaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquêtes de Satisfaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/ComptaSigneeCheck__c.field-meta.xml
<CustomField>
    <fullName>ComptaSigneeCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comptabilité signée?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Evaluation_a_posteriori__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_a_posteriori__c</fullName>
    <label>A l’intention de signer après échange 1?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Froid</fullName>
            </value>
            <value>
                <fullName>Tiède</fullName>
            </value>
            <value>
                <fullName>Chaud</fullName>
            </value>
            <value>
                <fullName>Bouillant</fullName>
                <label>Bouillant !</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/notedeSatisfactionGlobale__c.field-meta.xml
<CustomField>
    <fullName>notedeSatisfactionGlobale__c</fullName>
    <label>Note de Satisfaction Globale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/notedeSatisfactionPrisecontact__c.field-meta.xml
<CustomField>
    <fullName>notedeSatisfactionPrisecontact__c</fullName>
    <label>Note de satisfaction prise de contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/notedeSatisfactionPrisecontactcheck__c.field-meta.xml
<CustomField>
    <fullName>notedeSatisfactionPrisecontactcheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Satisfaction prise de contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/NotePropale__c.field-meta.xml
<CustomField>
    <fullName>NotePropale__c</fullName>
    <description>La proposition commerciale est-elle correcte?</description>
    <label>Note Proposition commerciale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Proposition_d_un_cabinet_partenaire__c.field-meta.xml
<CustomField>
    <fullName>Proposition_d_un_cabinet_partenaire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proposition d’un cabinet partenaire?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Recommandation_Tiime_Crea__c.field-meta.xml
<CustomField>
    <fullName>Recommandation_Tiime_Crea__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prêt à recommander Tiime Créa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/RecommandationPartenaireCheck__c.field-meta.xml
<CustomField>
    <fullName>RecommandationPartenaireCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prêt à recommander le partenaire?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/RepresentativeReactivityNote__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeReactivityNote__c</fullName>
    <label>Note Réactivité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/RepresentativeSkillsNotes__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeSkillsNotes__c</fullName>
    <label>Note Compétences</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/enquetedeSatisfaction__c/fields/Simplicite_du_process__c.field-meta.xml
<CustomField>
    <fullName>Simplicite_du_process__c</fullName>
    <label>Avis sur le Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Ne se prononce pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP07_SatisfactionSurvey.cls
public with sharing class AP07_SatisfactionSurvey {
	private static Map <String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('enquetedeSatisfaction__c').getDescribe().fields.getMap();

	private static String getLabel(String fieldName) {
		Schema.SObjectField field = fieldMap.get(fieldName);
		Schema.DescribeFieldResult describe = field.getDescribe();
		return describe.getLabel();
	}

	@AuraEnabled
	public static Map<String, String> getLabels() {
		//Workaround to get field label in lightning component
		Map<String, String> labels = new Map<String, String>();
		labels.put('notedeSatisfactionGlobale__c', getLabel('notedeSatisfactionGlobale__c'));
		labels.put('RepresentativeSkillsNotes__c', getLabel('RepresentativeSkillsNotes__c'));
		labels.put('RepresentativeReactivityNote__c', getLabel('RepresentativeReactivityNote__c'));
		labels.put('notedeSatisfactionPrisecontactcheck__c', getLabel('notedeSatisfactionPrisecontactcheck__c'));
		labels.put('RecommandationPartenaireCheck__c', getLabel('RecommandationPartenaireCheck__c'));
		labels.put('ComptaSigneeCheck__c', getLabel('ComptaSigneeCheck__c'));
		labels.put('NotePropale__c', getLabel('NotePropale__c'));
		labels.put('Evaluation_a_posteriori__c', getLabel('Evaluation_a_posteriori__c'));
		labels.put('notedeSatisfactionPrisecontact__c', getLabel('notedeSatisfactionPrisecontact__c'));
		labels.put('Simplicite_du_process__c', getLabel('Simplicite_du_process__c'));
		labels.put('Recommandation_Tiime_Crea__c', getLabel('Recommandation_Tiime_Crea__c'));
		labels.put('Proposition_d_un_cabinet_partenaire__c', getLabel('Proposition_d_un_cabinet_partenaire__c'));
		return labels;
	}
	
	@AuraEnabled
	public static List<Map<String, String>> getPicklistOptions(List<String> fieldNames) {
		List<Map<String, String>> lesPickLists = new List<Map<String, String>>();
		for(String fieldName : fieldNames)
			lesPickLists.add(Utils.getPicklistOptions('enquetedeSatisfaction__c', fieldName));
		return lesPickLists;
	}
	
	@AuraEnabled
	public static String getComponentTitle(Id enqueteId) {
		String title = '';
		List<EnquetedeSatisfaction__c> enquetes = [SELECT Id, RecordType.DeveloperName FROM EnquetedeSatisfaction__c WHERE Id = :enqueteId];
		if(!enquetes.isEmpty()) {
			title = Constants.ENQUETE_MAP_RECORDTYPE_DEVELOPERNAME_COMPONENT_TITLE.get(enquetes.get(0).RecordType.DeveloperName);
		}
		return title;
	}
}