force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Nom de Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/AEComments__c.field-meta.xml
<CustomField>
    <fullName>AEComments__c</fullName>
    <label>Commentaires AE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>seo</fullName>
                <label>SEO</label>
            </value>
            <value>
                <fullName>paid-search</fullName>
                <label>Paid Search</label>
            </value>
            <value>
                <fullName>native</fullName>
                <label>Native</label>
            </value>
            <value>
                <fullName>paid-social-media</fullName>
                <label>Paid Social Media</label>
            </value>
            <value>
                <fullName>affiliation</fullName>
                <label>Affiliation</label>
            </value>
            <value>
                <fullName>partenariats</fullName>
                <label>Partenariats</label>
            </value>
            <value>
                <fullName>events</fullName>
                <label>Events</label>
            </value>
            <value>
                <fullName>reco-client</fullName>
                <label>Reco client</label>
            </value>
            <value>
                <fullName>presse</fullName>
                <label>Presse</label>
            </value>
            <value>
                <fullName>webinar</fullName>
            </value>
            <value>
                <fullName>inconnu</fullName>
                <label>Inconnu</label>
            </value>
            <value>
                <fullName>inbound</fullName>
                <isActive>false</isActive>
                <label>Inbound</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CustomerRecommendation__c.field-meta.xml
<CustomField>
    <fullName>CustomerRecommendation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recommandation Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Recommandation Client)</relationshipLabel>
    <relationshipName>BAO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <label>Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>adwords</fullName>
                <label>Adwords</label>
            </value>
            <value>
                <fullName>bing</fullName>
                <label>Bing</label>
            </value>
            <value>
                <fullName>outbrain</fullName>
                <label>Outbrain</label>
            </value>
            <value>
                <fullName>ligatus</fullName>
                <label>Ligatus</label>
            </value>
            <value>
                <fullName>taboola</fullName>
                <label>Taboola</label>
            </value>
            <value>
                <fullName>facebook</fullName>
                <label>Facebook</label>
            </value>
            <value>
                <fullName>twitter</fullName>
                <label>Twitter</label>
            </value>
            <value>
                <fullName>linkedin</fullName>
                <label>LinkedIn</label>
            </value>
            <value>
                <fullName>youtube</fullName>
                <label>Youtube</label>
            </value>
            <value>
                <fullName>awin</fullName>
                <label>Awin</label>
            </value>
            <value>
                <fullName>kwanko</fullName>
                <label>Kwanko</label>
            </value>
            <value>
                <fullName>maddyness</fullName>
                <label>Maddyness</label>
            </value>
            <value>
                <fullName>french-web</fullName>
                <label>French web</label>
            </value>
            <value>
                <fullName>le-monde</fullName>
                <label>Le Monde</label>
            </value>
            <value>
                <fullName>les-echos</fullName>
                <label>Les Echos</label>
            </value>
            <value>
                <fullName>seo-direct</fullName>
                <label>Seo-direct</label>
            </value>
            <value>
                <fullName>inbound</fullName>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>newsletter</fullName>
                <label>Newsletter</label>
            </value>
            <value>
                <fullName>webinar</fullName>
                <label>Webinar</label>
            </value>
            <value>
                <fullName>blog-du-dirigeant</fullName>
                <isActive>false</isActive>
                <label>Blog du dirigeant</label>
            </value>
            <value>
                <fullName>companeo</fullName>
                <isActive>false</isActive>
                <label>Companeo</label>
            </value>
            <value>
                <fullName>qonto</fullName>
                <isActive>false</isActive>
                <label>Qonto</label>
            </value>
            <value>
                <fullName>sesame</fullName>
                <isActive>false</isActive>
                <label>Sesame</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadTemperature__c.field-meta.xml
<CustomField>
    <fullName>LeadTemperature__c</fullName>
    <label>Température de la Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1flame</fullName>
                <label>🔥</label>
            </value>
            <value>
                <fullName>2flames</fullName>
                <label>🔥🔥</label>
            </value>
            <value>
                <fullName>3flames</fullName>
                <label>🔥🔥🔥</label>
            </value>
            <value>
                <fullName>4flames</fullName>
                <label>🔥🔥🔥🔥</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/OrigineWebsite__c.field-meta.xml
<CustomField>
    <fullName>OrigineWebsite__c</fullName>
    <label>Branding d&#39;entrée</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novaa</fullName>
            </value>
            <value>
                <fullName>Incityz</fullName>
            </value>
            <value>
                <fullName>Onlicorn</fullName>
            </value>
            <value>
                <fullName>Tiime</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
                <label>Trouver mon comptable.com</label>
            </value>
            <value>
                <fullName>LEC</fullName>
                <label>L&#39;Expert-Comptable.com</label>
            </value>
            <value>
                <fullName>Sesame</fullName>
            </value>
            <value>
                <fullName>Start.fr</fullName>
            </value>
            <value>
                <fullName>Pepit</fullName>
            </value>
            <value>
                <fullName>Evocompta</fullName>
            </value>
            <value>
                <fullName>Goneo</fullName>
            </value>
            <value>
                <fullName>Ola-compta</fullName>
            </value>
            <value>
                <fullName>LNEC</fullName>
                <label>Le Net Expert Comptable</label>
            </value>
            <value>
                <fullName>LEC Lille</fullName>
                <label>L-Expert-Comptable Lille</label>
            </value>
            <value>
                <fullName>Condillac</fullName>
            </value>
            <value>
                <fullName>Auficom</fullName>
            </value>
            <value>
                <fullName>Proxicompta</fullName>
            </value>
            <value>
                <fullName>Progressive</fullName>
                <label>Progressive / Novaa</label>
            </value>
            <value>
                <fullName>Companeo</fullName>
            </value>
            <value>
                <fullName>Qonto</fullName>
            </value>
            <value>
                <fullName>TiimeAE</fullName>
            </value>
            <value>
                <fullName>Blog du dirigeant</fullName>
            </value>
            <value>
                <fullName>Ocompta</fullName>
                <isActive>false</isActive>
                <label>Ocompta</label>
            </value>
            <value>
                <fullName>Queexi</fullName>
                <isActive>false</isActive>
                <label>Queexi</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Partnership__c.field-meta.xml
<CustomField>
    <fullName>Partnership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Détail Partenariat</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur de partenariat n&#39;existe pas</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partenariat</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partenariat)</relationshipLabel>
    <relationshipName>Partenariat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TemperatureDetails__c.field-meta.xml
<CustomField>
    <fullName>TemperatureDetails__c</fullName>
    <label>Détails température</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Transfert__c/Transfert__c.object-meta.xml
<CustomObject>
    <label>Transfert</label>
    <nameField>
        <label>Nom de Transfert Lead</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transferts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfert__c/fields/AEComments__c.field-meta.xml
<CustomField>
    <fullName>AEComments__c</fullName>
    <label>Commentaire AE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Transferts</relationshipLabel>
    <relationshipName>Transferts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/LeadTemperature__c.field-meta.xml
<CustomField>
    <fullName>LeadTemperature__c</fullName>
    <label>Température de la Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>🔥</fullName>
            </value>
            <value>
                <fullName>🔥🔥</fullName>
            </value>
            <value>
                <fullName>🔥🔥🔥</fullName>
            </value>
            <value>
                <fullName>🔥🔥🔥🔥</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfert__c/fields/TemperatureDetails__c.field-meta.xml
<CustomField>
    <fullName>TemperatureDetails__c</fullName>
    <label>Détails température</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LTC26_InterviewAE.cls
public class LTC26_InterviewAE {
    
    private static final Map<String, Set<String>> objectNameToFieldsNameMap = new Map<String, Set<String>> {
    	'Transfert__c'	=> new Set<String> {'AEComments__c', 'LeadTemperature__c', 'TemperatureDetails__c', 'Lead__c'},
    	'Lead'			=> new Set<String> {'Canal__c', 'Detail__c', 'Partnership__c', 'Event__c'}
    };
    
    @AuraEnabled
	public static Map<String, String> getLabels() {
		//Workaround to get field label in lightning component
		Map<String, String> labels = new Map<String, String>();
		for(String objectName : objectNameToFieldsNameMap.keySet()) {
    		for(String fieldApiName : objectNameToFieldsNameMap.get(objectName)) {
    			labels.put(fieldApiName, Utils.getFieldLabel(objectName, fieldApiName));
    		}
    	}
		return labels;
	}
	
	@AuraEnabled
	public static Lead retrieveLead(Id transfertId) {
		return [SELECT Id, Lead__c, Lead__r.Id, Lead__r.Name, Lead__r.Canal__c, Lead__r.Detail__c, Lead__r.Partnership__c, Lead__r.Event__c, Lead__r.CustomerRecommendation__c, Lead__r.OrigineWebsite__c, Lead__r.MobilePhone, Lead__r.Email, Lead__r.LastName, Lead__r.Company 
		FROM Transfert__c WHERE Id = :transfertId].get(0).Lead__r; 
	}
}